ETOL: ETOL::eOMPL Class Reference
ETOL::eOMPL Class Reference
#include <eOMPL.hpp>
Public Member Functions
eOMPL ()
Constructor for a OMPL implementation of ETOL.
virtual ~eOMPL ()=default
void setup ()
Constructs an optimization problem from settings.
void solve ()
Solves the trajectory optimization problem.
void debug ()
Generates debug information.
void close ()
Closes all dynamically allocated resources.
void setGradient (const ompl::control::ODESolver::ODE &ode, const ompl::control::ODESolver::PostPropagationEvent &postEvent=nullptr)
Set the system dynamics x_dot = f(x,u)
void setPlanner (std::string planner_name)
Set the sampling-based path planning algorithm to be used.
Public Member Functions inherited from ETOL::TrajectoryOptimizer
TrajectoryOptimizer ()
Initializes a TrajectoryOptimizer object.
virtual ~TrajectoryOptimizer ()
const double getScore () const
void resetConfigs ()
Sets all configurations to default values.
void printConfigs ()
Prints configurations onto the console.
void loadConfigs (const char *filepath)
Loads configurations from an XML file.
void saveConfigs (const char *filepath)
Saves configurations to an XML file.
void addParams (std::list< param_t > params)
Adds a non-state or non-control variable to the problem.
void addExclZone (border_t *border)
Add an exclusion zone to the problem.
void addAdjTrack (track_t *track)
Add the track of an adjacent or nearby object.
void plotX (const int idx)
Plot the time history of a state variable.
void plotU (const int idx)
Plot the time history of a control variable.
state_t & getX0 ()
Get the initial state.
void setX0 (const state_t &x0)
Set an initial state.
state_t & getXf ()
Get the goal state.
void setXf (const state_t &xf)
Set the goal state.
const size_t getNControls () const
Get the number of control variables.
const size_t getNStates () const
Get the number of state variables.
state_t & getXlower ()
Get the states' lower bound.
void setXlower (const state_t &xlower)
Set the states' lower bound.
state_t & getXupper ()
Get the states' upper bound.
void setXupper (const state_t &xupper)
Set the states' upper bound.
state_var_t & getXvartype ()
Get the states' variable type.
void setXvartype (const state_var_t &xvartype)
Set the states' variable type.
const double getDt () const
Get the time step size.
void setDt (double dt)
Set the time step size.
const size_t getNSteps () const
Get the number of time steps.
void setNSteps (const size_t nSteps)
Set the number of steps.
state_t & getXtol ()
Get the states' error tolerance.
void setXtol (const state_t &xtol)
Set the states' error tolerance.
state_t & getUlower ()
Get the controls' lower bound.
void setUlower (const state_t &ulower)
Set the control's lower bound.
state_t & getUupper ()
Get the controls' upper bound.
void setUupper (const state_t &uupper)
Set the controls' upper bound.
state_var_t & getUvartype ()
Get the control variables' type.
void setUvartype (const state_var_t &uvartype)
Set the control variables' type.
const size_t getUrhorizon () const
Get the controls' reverse time horizon.
void setUrhorizon (const size_t nu4dyn)
Sets the reverse time horizon for control variables.
const size_t getXrhorizon () const
Get the states' reverse time horizon.
void setXrhorizon (const size_t nx4dyn)
Sets the reverse time horizon for state variables.
size_t getRhorizon () const
Get the maximium possible reverse time horizon.
void setNControls (const size_t nControls)
Get the number of control variables.
void setNStates (const size_t nStates)
Get the number of state variables.
void setEqConstraints (std::vector< f_t * > constraints)
Set the equality constraints.
void setLessEqConstraints (std::vector< f_t * > constraints)
Set the inequality constraints.
void setConstraints (std::vector< f_t * > constraints)
Set sense-agnostic constraint functions.
void setGradient (std::vector< f_t * > gradient)
Set the states' time derivative function.
void setObjective (f_t *objective)
Set the objective function.
traj_t * getUtraj ()
Get the pointer to the computed control trajectory.
traj_t * getXtraj ()
Get the pointer to the computed state trajectory.
const f_t * getObjective () const
Set the objective function.
std::vector< f_t * > * getGradient ()
Get the time derivative functions for the states.
std::vector< f_t * > * getEqConstraints ()
Get the equality constraint functions.
std::vector< f_t * > * getLessEqConstraints ()
Get the inequality constraint functions.
std::vector< f_t * > * getConstraints ()
Get the sense-agnostic constraint functions.
std::vector< border_t > * getObstacles_Raw ()
Get the pointer to the unprocessed exclusion zones.
std::list< region_t > * getObstacles ()
Get the pointer to the polygon partitioned exclusion zones.
std::list< track_t > * getTracks ()
Get the pointer to the moving exclusion zones.
bool isMaximized () const
Get the optimization direction.
void setMaximize (const bool maximize)
Set the optimization direction.
size_t getNExclZones ()
Get the number of exclusion zones.
size_t getNTracks ()
Get the number of moving exclusion zones.
Public Attributes
ompl::control::SpaceInformationPtr si_
ompl::base::ProblemDefinitionPtr pdef_
Protected Attributes
vector_t x
vector_t u
vector_t params
std::vector< std::string > pnames
std::shared_ptr< ompl::base::RealVectorStateSpace > space_
std::shared_ptr< ompl::control::RealVectorControlSpace > cspace_
ompl::base::PlannerPtr planner_
ompl::base::PlannerAllocator pa_
ompl::base::PlannerStatus last_status_
bool configured_
double planTime_
double solveTime_
const double threshold_ = std::numeric_limits<double>::epsilon()
std::string planner_name_ = "SST"
Protected Attributes inherited from ETOL::TrajectoryOptimizer
bool _maximize
double _score
double _dt
size_t _nSteps
size_t _nStates
size_t _nControls
state_t _x0
state_t _xlower
state_t _xupper
state_var_t _xvartype
state_t _xtol
state_t _xf
state_t _ulower
state_t _uupper
state_var_t _uvartype
size_t _xrhorizon
size_t _urhorizon
size_t _rhorizon
paramset_t _parmaeters
std::vector< border_t > _obstacles_raw
std::list< region_t > _obstacles
std::list< track_t > _tracks
std::vector< f_t * > _constraints
std::vector< f_t * > _eq
std::vector< f_t * > _lesseq
std::vector< f_t * > _gradient
f_t * _objective
traj_t _xtraj
traj_t _utraj
std::bad_any_cast * _eAny
Private Member Functions
void createVars ()
Add all variables to the OMPL model.
void addX0Xf ()
Add the initial and goal state constraint to the OMPL model.
void getTraj ()
Get the trajectory results from the OMPL model.
Additional Inherited Members
Static Public Member Functions inherited from ETOL::TrajectoryOptimizer
static region_t genRegion (border_t *border)
Create convex partitions.
static void calcSlopes (const region_t &region, std::vector< seg_t > *lower, std::vector< seg_t > *upper)
Computes slopes for lower and upper segments for convex partitions.
static void plot (traj_t *traj, const std::string title="Time History", const std::string tlab="t", const std::string xlab="", double tmin=DBL_MAX, double tmax=DBL_MIN, double xmin=DBL_MAX, double xmax=DBL_MIN)
Plots a trajectory.
static void plotXY (traj_t *traj, size_t xIdx=0, size_t yIdx=1, const std::string title="XY Plot", const std::string xlab="x", const std::string ylab="y", double xmin=DBL_MAX, double xmax=DBL_MIN, double ymin=DBL_MAX, double ymax=DBL_MIN)
Creates a XY-plot.
static void plotXY_wExclZones (traj_t *traj, std::list< region_t > *zones=NULL, size_t xIdx=0, size_t yIdx=1, const std::string title="XY Plot", const std::string xlab="x", const std::string ylab="y", double xmin=DBL_MAX, double xmax=DBL_MIN, double ymin=DBL_MAX, double ymax=DBL_MIN)
Creates a XY-plot wth exclusion zones.
static std::string animate2D (traj_t *traj, const int framerate=2, bool toFile=false, std::string outFile="animation.mp4", std::list< region_t > *obstacles=NULL, std::list< track_t > *tracks=NULL, size_t xIdx=0, size_t yIdx=1, const std::string title="notitle", const std::string xlab="x", const std::string ylab="y", double xmin=DBL_MAX, double xmax=DBL_MIN, double ymin=DBL_MAX, double ymax=DBL_MIN)
Creates a 2D animation with static and moving exclusion zones.
static std::string save (traj_t *traj, std::string fp="traj.csv")
Saves trajectories to a file.
Protected Member Functions inherited from ETOL::TrajectoryOptimizer
void errorHandler ()
An error handler that is called in try-catch blocks.
void setScore (const double score)
Stores the eSovler's objective function result.
Detailed Description
Definition at line 89 of file eOMPL.hpp.
Constructor & Destructor Documentation
eOMPL()
ETOL::eOMPL::eOMPL () explicit
Constructor for a OMPL implementation of ETOL.
Definition at line 114 of file eOMPL.cpp.
         : configured_(false),
           planTime_(0.),
           solveTime_(0.),
           last_status_(ompl::base::PlannerStatus::UNKNOWN) {}
~eOMPL()
virtual ETOL::eOMPL::~eOMPL () virtual default
Member Function Documentation
setup()
void ETOL::eOMPL::setup () virtual
Constructs an optimization problem from settings.
Implements ETOL::TrajectoryOptimizer.
Definition at line 121 of file eOMPL.cpp.
                       {
         if (!this->configured_ || !this->si_->isSetup() ||
                 !this->planner_->isSetup()) {
             if (!this->si_->isSetup())
                 this->si_->setup();
             if (!this->planner_) {
                 if (this->pa_)
                     this->planner_ = this->pa_(this->si_);
                 if (!this->planner_) {
                     std::string planner_usage =
                             "Using " + this->planner_name_ + ".";
                     OMPL_INFORM(planner_usage.c_str());
                     if (this->planner_name_ == "RRT")
                         this->planner_ = ompl::base::PlannerPtr(
                                 new ompl::control::RRT(this->si_));
                     else if (this->planner_name_ == "SST")
                         this->planner_ = ompl::base::PlannerPtr(
                                 new ompl::control::SST(this->si_));
                     else if (this->planner_name_ == "EST")
                         this->planner_ = ompl::base::PlannerPtr(
                                 new ompl::control::EST(this->si_));
                     else if (this->planner_name_ == "KPIECE")
                         this->planner_ = ompl::base::PlannerPtr(
                                 new ompl::control::KPIECE1(this->si_));
                     else if (this->planner_name_ == "PDST")
                         this->planner_ = ompl::base::PlannerPtr(
                                 new ompl::control::PDST(this->si_));
                     else
                         this->planner_ = ompl::base::PlannerPtr(
                                 new ompl::control::SST(this->si_));
                 }
             }
             this->planner_->setProblemDefinition(this->pdef_);
             if (!this->planner_->isSetup())
                 this->planner_->setup();
             this->configured_ = true;
         }
     }
References configured_, pa_, pdef_, planner_, planner_name_, and si_.
solve()
void ETOL::eOMPL::solve () virtual
Solves the trajectory optimization problem.
Implements ETOL::TrajectoryOptimizer.
Definition at line 161 of file eOMPL.cpp.
                       {
         this->last_status_ = ompl::base::PlannerStatus::UNKNOWN;
         ompl::time::point start = ompl::time::now();
         this->last_status_ = this->planner_->solve(this->solveTime_);
         this->planTime_ = ompl::time::seconds(ompl::time::now() - start);
         if (this->last_status_) {
             OMPL_INFORM("Solution found in %f seconds", this->planTime_);
             this->setScore(pdef_->getSolutionPath()->cost(
                     this->pdef_->getOptimizationObjective()).value());
             this->getTraj();
         } else {
             OMPL_INFORM("No solution found after %f seconds", this->planTime_);
         }
     }
References getTraj(), last_status_, pdef_, planner_, planTime_, ETOL::TrajectoryOptimizer::setScore(), and solveTime_.
debug()
void ETOL::eOMPL::debug () virtual
Generates debug information.
Implements ETOL::TrajectoryOptimizer.
Definition at line 176 of file eOMPL.cpp.
 {}
close()
void ETOL::eOMPL::close () virtual
Closes all dynamically allocated resources.
Implements ETOL::TrajectoryOptimizer.
Definition at line 178 of file eOMPL.cpp.
                       {
         if (planner_)
             planner_->clear();
         if (pdef_)
             pdef_->clearSolutionPaths();
     }
References pdef_, and planner_.
setGradient()
void ETOL::eOMPL::setGradient (const ompl::control::ODESolver::ODE & ode, const ompl::control::ODESolver::PostPropagationEvent & postEvent = nullptr)
Set the system dynamics x_dot = f(x,u)
Parameters
ode Solver to solve the differential equation
postEvent Function to execute after the integration
Definition at line 240 of file eOMPL.cpp.
{
         this->solveTime_ = this->getNSteps() * this->getDt();
         this->createVars();
         this->addX0Xf();
         ompl::control::ODESolverPtr odeSolver(
                 new ompl::control::ODEBasicSolver<> (this->si_, ode));
         this->si_->setStatePropagator(
                 ompl::control::ODESolver::getStatePropagator(
                         odeSolver, postEvent));
     }
References addX0Xf(), createVars(), ETOL::TrajectoryOptimizer::getDt(), ETOL::TrajectoryOptimizer::getNSteps(), si_, and solveTime_.
Referenced by main().
setPlanner()
void ETOL::eOMPL::setPlanner (std::string planner_name)
Set the sampling-based path planning algorithm to be used.
Parameters
planner_name Name of sampling-based path planning algorithm to be used
Definition at line 253 of file eOMPL.cpp.
{
         this->planner_name_ = planner_name;
     }
References planner_name_.
Referenced by main().
createVars()
void ETOL::eOMPL::createVars () private
Add all variables to the OMPL model.
Definition at line 186 of file eOMPL.cpp.
{
         // create state-space and its bound
         this->space_ = std::shared_ptr<ompl::base::RealVectorStateSpace>(
                 std::make_shared<ompl::base::RealVectorStateSpace>(
                         this->getNStates()));
         ompl::base::RealVectorBounds bounds(this->getNStates());
         state_t::iterator l_it, u_it;
         l_it = this->getXlower().begin();
         u_it = this->getXupper().begin();
         for (int i = 0; i < this->getNStates(); i++) {
             bounds.setLow(i, *(l_it++));
             bounds.setHigh(i, *(u_it++));
         }
         this->space_->setBounds(bounds);
         // create a control space and its bound
         this->cspace_ = std::shared_ptr<ompl::control::RealVectorControlSpace>(
                 std::make_shared<ompl::control::RealVectorControlSpace>(
                         this->space_, this->getNControls()));
         ompl::base::RealVectorBounds cbounds(this->getNControls());
         l_it = this->getUlower().begin();
         u_it = this->getUupper().begin();
         for (int i = 0; i < this->getNControls(); i++) {
             cbounds.setLow(i, *(l_it++));
             cbounds.setHigh(i, *(u_it++));
         }
         this->cspace_->setBounds(cbounds);
         // Construct a space information instance for this state space
         this->si_ = std::make_shared<ompl::control::SpaceInformation>(
                 this->cspace_->getStateSpace(), this->cspace_);
         this->pdef_ = std::make_shared<ompl::base::ProblemDefinition>(
                 this->si_);
         this->si_->setStateValidityChecker(ompl::base::StateValidityCheckerPtr(
                 new ETOL::ValidityChecker(
                         this->si_, this->getObstacles_Raw())));
     }
References cspace_, ETOL::TrajectoryOptimizer::getNControls(), ETOL::TrajectoryOptimizer::getNStates(), ETOL::TrajectoryOptimizer::getObstacles_Raw(), ETOL::TrajectoryOptimizer::getUlower(), ETOL::TrajectoryOptimizer::getUupper(), ETOL::TrajectoryOptimizer::getXlower(), ETOL::TrajectoryOptimizer::getXupper(), pdef_, si_, and space_.
Referenced by setGradient().
addX0Xf()
void ETOL::eOMPL::addX0Xf () private
Add the initial and goal state constraint to the OMPL model.
Definition at line 224 of file eOMPL.cpp.
{
         ompl::base::ScopedState<ompl::base::RealVectorStateSpace> start(
                 this->space_);
         for (int i = 0; i < this->getNStates(); i++) {
             start[i] = this->getX0().at(i);
         }
         ompl::base::ScopedState<ompl::base::RealVectorStateSpace> goal(
                 this->space_);
         for (int i = 0; i < this->getNStates(); i++) {
             goal[i] = this->getXf().at(i);
         }
         this->pdef_->setStartAndGoalStates(start, goal, this->threshold_);
     }
References ETOL::TrajectoryOptimizer::getNStates(), ETOL::TrajectoryOptimizer::getX0(), ETOL::TrajectoryOptimizer::getXf(), pdef_, space_, and threshold_.
Referenced by setGradient().
getTraj()
void ETOL::eOMPL::getTraj () private
Get the trajectory results from the OMPL model.
Definition at line 257 of file eOMPL.cpp.
{
         if (this->last_status_) {
             std::cout << this->planner_->getName()
                       << " found a solution of length "
                       << this->pdef_->getSolutionPath()->length() << std::endl;
             std::shared_ptr<ompl::control::PathControl> sol =
                     std::static_pointer_cast<ompl::control::PathControl>(
                             this->pdef_->getSolutionPath());
             sol->print(std::cout);
             std::ofstream myfile;
             myfile.open("ompl_path.txt");
             sol->printAsMatrix(myfile);
             myfile.close();
             std::ifstream myReadFile;
             myReadFile.open("ompl_path.txt");
             std::vector<std::vector<double> > data;
             std::vector<double> dat;
             double d;
             traj_t* xtraj = this->getXtraj();
             xtraj->clear();
             traj_t* utraj = this->getUtraj();
             utraj->clear();
             for (int i = 0; i < sol->getStateCount(); i++) {
                 state_t x_sol;
                 state_t u_sol;
                 double t;
                 size_t nvars = this->getNStates() + this->getNControls() + 1;
                 for (int j = 0; j < nvars; j++) {
                     myReadFile >> d;
                     if (j < this->getNStates())
                         x_sol.push_back(d);
                     else if (j < this->getNControls())
                         u_sol.push_back(d);
                     else
                         t = d;
                 }
                 xtraj->push_back(traj_elem_t(t, x_sol));
                 utraj->push_back(traj_elem_t(t, u_sol));
             }
         }
     }
References ETOL::TrajectoryOptimizer::getNControls(), ETOL::TrajectoryOptimizer::getNStates(), ETOL::TrajectoryOptimizer::getUtraj(), ETOL::TrajectoryOptimizer::getXtraj(), last_status_, pdef_, and planner_.
Referenced by solve().
Member Data Documentation
si_
ompl::control::SpaceInformationPtr ETOL::eOMPL::si_
pointer to OMPL space information
Definition at line 134 of file eOMPL.hpp.
Referenced by createVars(), main(), setGradient(), and setup().
pdef_
ompl::base::ProblemDefinitionPtr ETOL::eOMPL::pdef_
pointer to OMPL problem definition
Definition at line 136 of file eOMPL.hpp.
Referenced by addX0Xf(), close(), createVars(), getTraj(), main(), setup(), and solve().
x
vector_t ETOL::eOMPL::x protected
State Trajectory
Definition at line 141 of file eOMPL.hpp.
u
vector_t ETOL::eOMPL::u protected
Control Trajectory
Definition at line 142 of file eOMPL.hpp.
params
vector_t ETOL::eOMPL::params protected
Path constraint configs
Definition at line 143 of file eOMPL.hpp.
pnames
std::vector<std::string> ETOL::eOMPL::pnames protected
Path constraint names
Definition at line 144 of file eOMPL.hpp.
space_
std::shared_ptr<ompl::base::RealVectorStateSpace> ETOL::eOMPL::space_ protected
pointer to OMPL state space
Definition at line 146 of file eOMPL.hpp.
Referenced by addX0Xf(), and createVars().
cspace_
std::shared_ptr<ompl::control::RealVectorControlSpace> ETOL::eOMPL::cspace_ protected
pointer to OMPL control space
Definition at line 148 of file eOMPL.hpp.
Referenced by createVars().
planner_
ompl::base::PlannerPtr ETOL::eOMPL::planner_ protected
pointer to OMPL planner
Definition at line 150 of file eOMPL.hpp.
Referenced by close(), getTraj(), setup(), and solve().
pa_
ompl::base::PlannerAllocator ETOL::eOMPL::pa_ protected
OMPL planner allocator
Definition at line 152 of file eOMPL.hpp.
Referenced by setup().
last_status_
ompl::base::PlannerStatus ETOL::eOMPL::last_status_ protected
OMPL status
Definition at line 154 of file eOMPL.hpp.
Referenced by getTraj(), and solve().
configured_
bool ETOL::eOMPL::configured_ protected
OMPL configure flag
Definition at line 155 of file eOMPL.hpp.
Referenced by setup().
planTime_
double ETOL::eOMPL::planTime_ protected
OMPL planning time
Definition at line 156 of file eOMPL.hpp.
Referenced by solve().
solveTime_
double ETOL::eOMPL::solveTime_ protected
OMPL solving time
Definition at line 157 of file eOMPL.hpp.
Referenced by setGradient(), and solve().
threshold_
const double ETOL::eOMPL::threshold_ = std::numeric_limits<double>::epsilon() protected
OMPL goal state tolerant
Definition at line 158 of file eOMPL.hpp.
Referenced by addX0Xf().
planner_name_
std::string ETOL::eOMPL::planner_name_ = "SST" protected
OMPL planner name
Definition at line 160 of file eOMPL.hpp.
Referenced by setPlanner(), and setup().
The documentation for this class was generated from the following files:
C:/msys64/home/admin/ETOL/include/ETOL/eOMPL.hpp
C:/msys64/home/admin/ETOL/src/eOMPL/eOMPL.cpp