ETOL: ETOL::ValidityChecker Class Reference
ETOL::ValidityChecker Class Reference
#include <eOMPL.hpp>
Classes
struct Point
(x,y) co-ordinate for polyhedron obstacles
Public Member Functions
ValidityChecker (const ompl::base::SpaceInformationPtr &si, std::vector< border_t > *obstacles)
Constructor for a OMPL Collision checker of ETOL.
bool onSegment (Point p, Point q, Point r) const
Check if a point lies on a line segment.
int orientation (Point p, Point q, Point r) const
Find orientation of ordered triplet (p, q, r).
bool doIntersect (Point p1, Point q1, Point p2, Point q2) const
Check if two lines intersect.
bool isInside (Point polygon[], int n, Point p) const
Check if the point lies inside the polygon.
bool isValid (const ompl::base::State *state) const
Check if the state collides with obstacles.
Public Attributes
std::vector< border_t > * obstacles_
Detailed Description
Definition at line 24 of file eOMPL.hpp.
Constructor & Destructor Documentation
ValidityChecker()
ETOL::ValidityChecker::ValidityChecker (const ompl::base::SpaceInformationPtr & si, std::vector< border_t > * obstacles) inline
Constructor for a OMPL Collision checker of ETOL.
Parameters
si OMPL space information pointer
obstacles
Definition at line 31 of file eOMPL.hpp.
                                                                                                :
                 ompl::base::StateValidityChecker(si), obstacles_(obstacles)
         {}
Member Function Documentation
onSegment()
bool ETOL::ValidityChecker::onSegment (Point p, Point q, Point r) const
Check if a point lies on a line segment.
Parameters
p first colinear point
q second colinear point
r third colinear point
Returns
true if q lies on line segment 'pr'
Definition at line 22 of file eOMPL.cpp.
{
         if (q.x <= std::max(p.x, r.x) && q.x >= std::min(p.x, r.x) &&
             q.y <= std::max(p.y, r.y) && q.y >= std::min(p.y, r.y))
             return true;
         return false;
     }
References ETOL::ValidityChecker::Point::x, and ETOL::ValidityChecker::Point::y.
Referenced by doIntersect(), and isInside().
orientation()
int ETOL::ValidityChecker::orientation (Point p, Point q, Point r) const
Find orientation of ordered triplet (p, q, r).
Parameters
p first colinear point
q second colinear point
r third colinear point
Returns
0 --> p, q and r are colinear, 1 --> Clockwise, 2 --> Counterclockwise
Definition at line 29 of file eOMPL.cpp.
{
         int val = (q.y - p.y) * (r.x - q.x) -
                   (q.x - p.x) * (r.y - q.y);
         if (val == 0) return 0;     // colinear
         return (val > 0) ? 1: 2;    // clock or counterclock wise
     }
References ETOL::ValidityChecker::Point::x, and ETOL::ValidityChecker::Point::y.
Referenced by doIntersect(), and isInside().
doIntersect()
bool ETOL::ValidityChecker::doIntersect (Point p1, Point q1, Point p2, Point q2) const
Check if two lines intersect.
Parameters
p1 first point of the first line
q1 second point of the first line
p2 first point of the second line
q2 second point of the second line
Returns
true if there is an intersection
Definition at line 37 of file eOMPL.cpp.
{
         // Find the four orientations needed for general and
         // special cases
         int o1 = orientation(p1, q1, p2);
         int o2 = orientation(p1, q1, q2);
         int o3 = orientation(p2, q2, p1);
         int o4 = orientation(p2, q2, q1);
         // General case
         if (o1 != o2 && o3 != o4)
             return true;
         // Special Cases
         // p1, q1 and p2 are colinear and p2 lies on segment p1q1
         if (o1 == 0 && onSegment(p1, p2, q1)) return true;
         // p1, q1 and p2 are colinear and q2 lies on segment p1q1
         if (o2 == 0 && onSegment(p1, q2, q1)) return true;
         // p2, q2 and p1 are colinear and p1 lies on segment p2q2
         if (o3 == 0 && onSegment(p2, p1, q2)) return true;
         // p2, q2 and q1 are colinear and q1 lies on segment p2q2
         if (o4 == 0 && onSegment(p2, q1, q2)) return true;
         return false;  // Doesn't fall in any of the above cases
     }
References onSegment(), and orientation().
Referenced by isInside().
isInside()
bool ETOL::ValidityChecker::isInside (Point polygon[], int n, Point p) const
Check if the point lies inside the polygon.
Parameters
polygon set of points that forms a polygon
n the number of vertices of the polygon
p the point to be check
Returns
true if the point lies inside the polygon
Definition at line 66 of file eOMPL.cpp.
{
         // There must be at least 3 vertices in polygon[]
         if (n < 3)  return false;
         // Create a point for line segment from p to infinite
         Point extreme = {INF, p.y};
         // Count intersections of the above line with sides of polygon
         int count = 0, i = 0;
         do {
             int next = (i+1)%n;
             // Check if the line segment from 'p' to 'extreme' intersects
             // with the line segment from 'polygon[i]' to 'polygon[next]'
             if (doIntersect(polygon[i], polygon[next], p, extreme)) {
                 // If the point 'p' is colinear with line segment 'i-next',
                 // then check if it lies on segment. If it lies, return true,
                 // otherwise false
                 if (orientation(polygon[i], p, polygon[next]) == 0)
                     return onSegment(polygon[i], p, polygon[next]);
                 count++;
             }
             i = next;
         } while (i != 0);
         // Return true if count is odd, false otherwise
         return count&1;  // Same as (count%2 == 1)
     }
References doIntersect(), INF, onSegment(), orientation(), and ETOL::ValidityChecker::Point::y.
Referenced by isValid().
isValid()
bool ETOL::ValidityChecker::isValid (const ompl::base::State * state) const
Check if the state collides with obstacles.
Parameters
state generated point from sampling-based path planning algorithm
Returns
true if the state does NOT collide with obstacles
Definition at line 95 of file eOMPL.cpp.
{
         bool res = true;
         const auto *s = state->
                 as<ompl::base::RealVectorStateSpace::StateType>();
         Point p = {s->values[0], s->values[1]};
         for (const auto& obs : *this->obstacles_) {
             int n = obs.size();
             std::vector<Point> polygons;
             int i = 0;
             for (const auto& corner : obs) {
                 polygons.push_back({corner[0], corner[1]});
                 i++;
             }
             res = res & !isInside(&polygons[0], n, p);
         }
         return res;
     }
References isInside(), and obstacles_.
Member Data Documentation
obstacles_
std::vector<border_t>* ETOL::ValidityChecker::obstacles_
Definition at line 86 of file eOMPL.hpp.
Referenced by isValid().
The documentation for this class was generated from the following files:
C:/Users/admin/git/ETOL/include/ETOL/eOMPL.hpp
C:/Users/admin/git/ETOL/src/eOMPL/eOMPL.cpp