ETOL: ETOL::eGLPK Class Reference
ETOL::eGLPK Class Reference
#include <eGLPK.hpp>
Public Member Functions
eGLPK ()
Constructor for a GLPK implementation of ETOL.
virtual ~eGLPK ()
void setup ()
Constructs an optimization problem from settings.
void solve ()
Solves the trajectory optimization problem.
void debug ()
Generates debug information.
void close ()
Closes all dynamically allocated resources.
void read_lp (const char *lp_file)
Get the model from an lp file.
void write_lp ()
Write the model to an lp file.
void write_sol ()
Write the solution to a text file.
void solve_lp (const char *lp_file)
Solve the problem from an lp file.
int getVarByName (const std::string &name)
Provides a consistent variable index.
Public Member Functions inherited from ETOL::TrajectoryOptimizer
TrajectoryOptimizer ()
Initializes a TrajectoryOptimizer object.
virtual ~TrajectoryOptimizer ()
const double getScore () const
void resetConfigs ()
Sets all configurations to default values.
void printConfigs ()
Prints configurations onto the console.
void loadConfigs (const char *filepath)
Loads configurations from an XML file.
void saveConfigs (const char *filepath)
Saves configurations to an XML file.
void addParams (std::list< param_t > params)
Adds a non-state or non-control variable to the problem.
void addExclZone (border_t *border)
Add an exclusion zone to the problem.
void addAdjTrack (track_t *track)
Add the track of an adjacent or nearby object.
void plotX (const int idx)
Plot the time history of a state variable.
void plotU (const int idx)
Plot the time history of a control variable.
state_t & getX0 ()
Get the initial state.
void setX0 (const state_t &x0)
Set an initial state.
state_t & getXf ()
Get the goal state.
void setXf (const state_t &xf)
Set the goal state.
const size_t getNControls () const
Get the number of control variables.
const size_t getNStates () const
Get the number of state variables.
state_t & getXlower ()
Get the states' lower bound.
void setXlower (const state_t &xlower)
Set the states' lower bound.
state_t & getXupper ()
Get the states' upper bound.
void setXupper (const state_t &xupper)
Set the states' upper bound.
state_var_t & getXvartype ()
Get the states' variable type.
void setXvartype (const state_var_t &xvartype)
Set the states' variable type.
const double getDt () const
Get the time step size.
void setDt (double dt)
Set the time step size.
const size_t getNSteps () const
Get the number of time steps.
void setNSteps (const size_t nSteps)
Set the number of steps.
state_t & getXtol ()
Get the states' error tolerance.
void setXtol (const state_t &xtol)
Set the states' error tolerance.
state_t & getUlower ()
Get the controls' lower bound.
void setUlower (const state_t &ulower)
Set the control's lower bound.
state_t & getUupper ()
Get the controls' upper bound.
void setUupper (const state_t &uupper)
Set the controls' upper bound.
state_var_t & getUvartype ()
Get the control variables' type.
void setUvartype (const state_var_t &uvartype)
Set the control variables' type.
const size_t getUrhorizon () const
Get the controls' reverse time horizon.
void setUrhorizon (const size_t nu4dyn)
Sets the reverse time horizon for control variables.
const size_t getXrhorizon () const
Get the states' reverse time horizon.
void setXrhorizon (const size_t nx4dyn)
Sets the reverse time horizon for state variables.
size_t getRhorizon () const
Get the maximium possible reverse time horizon.
void setNControls (const size_t nControls)
Get the number of control variables.
void setNStates (const size_t nStates)
Get the number of state variables.
void setEqConstraints (std::vector< f_t * > constraints)
Set the equality constraints.
void setLessEqConstraints (std::vector< f_t * > constraints)
Set the inequality constraints.
void setConstraints (std::vector< f_t * > constraints)
Set sense-agnostic constraint functions.
void setGradient (std::vector< f_t * > gradient)
Set the states' time derivative function.
void setObjective (f_t *objective)
Set the objective function.
traj_t * getUtraj ()
Get the pointer to the computed control trajectory.
traj_t * getXtraj ()
Get the pointer to the computed state trajectory.
const f_t * getObjective () const
Set the objective function.
std::vector< f_t * > * getGradient ()
Get the time derivative functions for the states.
std::vector< f_t * > * getEqConstraints ()
Get the equality constraint functions.
std::vector< f_t * > * getLessEqConstraints ()
Get the inequality constraint functions.
std::vector< f_t * > * getConstraints ()
Get the sense-agnostic constraint functions.
std::vector< border_t > * getObstacles_Raw ()
Get the pointer to the unprocessed exclusion zones.
std::list< region_t > * getObstacles ()
Get the pointer to the polygon partitioned exclusion zones.
std::list< track_t > * getTracks ()
Get the pointer to the moving exclusion zones.
bool isMaximized () const
Get the optimization direction.
void setMaximize (const bool maximize)
Set the optimization direction.
size_t getNExclZones ()
Get the number of exclusion zones.
size_t getNTracks ()
Get the number of moving exclusion zones.
Static Public Member Functions
static int getGLPKType (var_t varType)
Converts the variable type to a GLPK compliant type.
static std::string getStateName (const size_t &tIdx, const size_t &sIdx)
Provides a consistent state variable name.
static std::string getControlName (const size_t &tIdx, const size_t &sIdx)
Provides a consistent control variable name.
static std::string getParamName (std::string name, const size_t &tIdx)
Provides a consistent name for a custom variable.
static std::string getParamName (std::string name, const size_t &tIdx, const size_t &sIdx)
Provides a consistent name for a custom variable.
static std::string getParamName (std::string name, const size_t &Idx1, const size_t &Idx2, const size_t &Idx3)
Provides a consistent name for a custom variable.
static std::vector< closure_t > createObstacles (TrajectoryOptimizer *t)
Add obstacles.
static std::vector< track_t > createTracks (TrajectoryOptimizer *t, int NSIDES)
Add tracks.
static std::vector< std::pair< std::vector< glpk_t >, glpk_bnd_t > > addObstacleSides (seg_t seg, int sign, const std::string &name, int ind_i, int ind_j, int tIdx, std::vector< std::string > pnames, int BigM)
Adds the side of an obstacle to the constraint set.
static std::vector< std::pair< std::vector< glpk_t >, glpk_bnd_t > > addObstacleSum (const std::string &name, int ind_i, int ind_j, int tIdx, std::vector< std::string > pnames, int NSIDES)
Adds the sum of binary variables for an obstacle.
Static Public Member Functions inherited from ETOL::TrajectoryOptimizer
static region_t genRegion (border_t *border)
Create convex partitions.
static void calcSlopes (const region_t &region, std::vector< seg_t > *lower, std::vector< seg_t > *upper)
Computes slopes for lower and upper segments for convex partitions.
static void plot (traj_t *traj, const std::string title="Time History", const std::string tlab="t", const std::string xlab="", double tmin=DBL_MAX, double tmax=DBL_MIN, double xmin=DBL_MAX, double xmax=DBL_MIN)
Plots a trajectory.
static void plotXY (traj_t *traj, size_t xIdx=0, size_t yIdx=1, const std::string title="XY Plot", const std::string xlab="x", const std::string ylab="y", double xmin=DBL_MAX, double xmax=DBL_MIN, double ymin=DBL_MAX, double ymax=DBL_MIN)
Creates a XY-plot.
static void plotXY_wExclZones (traj_t *traj, std::list< region_t > *zones=NULL, size_t xIdx=0, size_t yIdx=1, const std::string title="XY Plot", const std::string xlab="x", const std::string ylab="y", double xmin=DBL_MAX, double xmax=DBL_MIN, double ymin=DBL_MAX, double ymax=DBL_MIN)
Creates a XY-plot wth exclusion zones.
static std::string animate2D (traj_t *traj, const int framerate=2, bool toFile=false, std::string outFile="animation.mp4", std::list< region_t > *obstacles=NULL, std::list< track_t > *tracks=NULL, size_t xIdx=0, size_t yIdx=1, const std::string title="notitle", const std::string xlab="x", const std::string ylab="y", double xmin=DBL_MAX, double xmax=DBL_MIN, double ymin=DBL_MAX, double ymax=DBL_MIN)
Creates a 2D animation with static and moving exclusion zones.
static std::string save (traj_t *traj, std::string fp="traj.csv")
Saves trajectories to a file.
Protected Attributes
glp_prob * _model
glp_iocp _params
int _status_relax
int _status_mip
int _var_cnt
int _const_cnt
int _ind_cnt
std::vector< int > _ia {0}
std::vector< int > _ja {0}
std::vector< double > _ar {0}
std::map< std::string, int > _var_map
vector_t x
vector_t u
vector_t params
std::vector< std::string > pnames
Protected Attributes inherited from ETOL::TrajectoryOptimizer
bool _maximize
double _score
double _dt
size_t _nSteps
size_t _nStates
size_t _nControls
state_t _x0
state_t _xlower
state_t _xupper
state_var_t _xvartype
state_t _xtol
state_t _xf
state_t _ulower
state_t _uupper
state_var_t _uvartype
size_t _xrhorizon
size_t _urhorizon
size_t _rhorizon
paramset_t _parmaeters
std::vector< border_t > _obstacles_raw
std::list< region_t > _obstacles
std::list< track_t > _tracks
std::vector< f_t * > _constraints
std::vector< f_t * > _eq
std::vector< f_t * > _lesseq
std::vector< f_t * > _gradient
f_t * _objective
traj_t _xtraj
traj_t _utraj
std::bad_any_cast * _eAny
Private Member Functions
void createVars ()
Add all variables to the GLPK model.
void addX0 ()
Add the initial state constraint to the GLPK model.
void addXf ()
Add the goal state constraint to the GLPK model.
void addConstr ()
Add the path constraints to the GLPK model.
void addDyn ()
Add the state dynamics to the GLPK model.
void addObj ()
Add the objective function to the GLPK model.
void getTraj ()
Get the trajectory results from the GLPK model.
Additional Inherited Members
Protected Member Functions inherited from ETOL::TrajectoryOptimizer
void errorHandler ()
An error handler that is called in try-catch blocks.
void setScore (const double score)
Stores the eSovler's objective function result.
Detailed Description
Definition at line 24 of file eGLPK.hpp.
Constructor & Destructor Documentation
eGLPK()
ETOL::eGLPK::eGLPK ()
Constructor for a GLPK implementation of ETOL.
Definition at line 24 of file eGLPK.cpp.
              : eGLPK::TrajectoryOptimizer() {
     this->_model = glp_create_prob();
     glp_init_iocp(&this->_params);
     this->_params.presolve = GLP_ON;
     this->_var_cnt = 0;
     this->_const_cnt = 0;
     this->_ind_cnt = 0;
     this->_status_mip = 0;
     this->_status_relax = 0;
 }
References _const_cnt, _ind_cnt, _model, _params, _status_mip, _status_relax, and _var_cnt.
~eGLPK()
ETOL::eGLPK::~eGLPK () virtual
Definition at line 36 of file eGLPK.cpp.
 {}
Member Function Documentation
setup()
void ETOL::eGLPK::setup () virtual
Constructs an optimization problem from settings.
Implements ETOL::TrajectoryOptimizer.
Definition at line 39 of file eGLPK.cpp.
                   {
     assert(this->getX0().size() == this->getNStates());
     assert(this->getXf().size() == this->getNStates());
     assert(this->getXlower().size() == this->getNStates());
     assert(this->getXupper().size() == this->getNStates());
     assert(this->getXvartype().size() == this->getNStates());
     try {
         this->x.resize(this->getNStates());
         this->u.resize(this->getNControls());
         this->createVars();
         this->addX0();
         this->addXf();
         this->addDyn();
         this->addConstr();
         this->addObj();
         glp_load_matrix(this->_model, this->_ind_cnt, &this->_ia[0],
                 &this->_ja[0], &this->_ar[0]);
     } catch (...) {
         std::cout << "Exception occurred at setup";
         exit(EXIT_FAILURE);
     }
 }
References _ar, _ia, _ind_cnt, _ja, _model, addConstr(), addDyn(), addObj(), addX0(), addXf(), createVars(), ETOL::TrajectoryOptimizer::getNControls(), ETOL::TrajectoryOptimizer::getNStates(), ETOL::TrajectoryOptimizer::getX0(), ETOL::TrajectoryOptimizer::getXf(), ETOL::TrajectoryOptimizer::getXlower(), ETOL::TrajectoryOptimizer::getXupper(), ETOL::TrajectoryOptimizer::getXvartype(), u, and x.
solve()
void ETOL::eGLPK::solve () virtual
Solves the trajectory optimization problem.
Implements ETOL::TrajectoryOptimizer.
Definition at line 64 of file eGLPK.cpp.
                   {
     try {
         this->_status_relax = glp_intopt(this->_model, &this->_params);
         this->_status_mip = glp_mip_status(this->_model);
         if (this->_status_mip == GLP_OPT) {
             this->write_sol();
             this->setScore(glp_mip_obj_val(this->_model));
             this->getTraj();
         }
     } catch (...) {
         std::cout << "Exception occurred at solve";
         exit(EXIT_FAILURE);
     }
 }
References _model, _params, _status_mip, _status_relax, getTraj(), ETOL::TrajectoryOptimizer::setScore(), and write_sol().
debug()
void ETOL::eGLPK::debug () virtual
Generates debug information.
Implements ETOL::TrajectoryOptimizer.
Definition at line 79 of file eGLPK.cpp.
                   {
     this->write_lp();
 }
References write_lp().
close()
void ETOL::eGLPK::close () virtual
Closes all dynamically allocated resources.
Implements ETOL::TrajectoryOptimizer.
Definition at line 83 of file eGLPK.cpp.
                   {
     glp_delete_prob(this->_model);
     glp_free_env();
 }
References _model.
read_lp()
void ETOL::eGLPK::read_lp (const char * lp_file)
Get the model from an lp file.
Parameters
lp_file path to lp file
Definition at line 253 of file eGLPK.cpp.
{
     glp_read_lp(this->_model, NULL, lp_file);
 }
write_lp()
void ETOL::eGLPK::write_lp ()
Write the model to an lp file.
Definition at line 257 of file eGLPK.cpp.
                      {
     glp_write_lp(this->_model, NULL, "debug_glpk.lp");
 }
Referenced by debug().
write_sol()
void ETOL::eGLPK::write_sol ()
Write the solution to a text file.
Definition at line 261 of file eGLPK.cpp.
                       {
     glp_write_mip(this->_model, "sol_glpk_compact.txt");
     glp_print_mip(this->_model, "sol_glpk_verbose.txt");
 }
Referenced by solve().
solve_lp()
void ETOL::eGLPK::solve_lp (const char * lp_file)
Solve the problem from an lp file.
Parameters
lp_file path to lp file
Definition at line 266 of file eGLPK.cpp.
{
     this->read_lp(lp_file);
     this->debug();
     this->solve();
     this->write_sol();
     this->close();
 }
getGLPKType()
int ETOL::eGLPK::getGLPKType (var_t varType) static
Converts the variable type to a GLPK compliant type.
Parameters
varType a ETOL variable type
Returns
a Gurobi variable type
Definition at line 89 of file eGLPK.cpp.
{
     switch (varType) {
         case var_t::CONTINUOUS:
             return GLP_CV;
         case var_t::INTERGER:
             return     GLP_IV;
         case var_t::BINARY:
             return GLP_BV;
         default :
             assert(true);  // Type not implemented
     }
     return GLP_CV;
 }
References ETOL::BINARY, ETOL::CONTINUOUS, and ETOL::INTERGER.
getStateName()
std::string ETOL::eGLPK::getStateName (const size_t & tIdx, const size_t & sIdx) static
Provides a consistent state variable name.
Parameters
tIdx a time index
sIdx a state index
Returns
a state variable name
Definition at line 103 of file eGLPK.cpp.
{
     return("x_" + std::to_string(tIdx) + "_" + std::to_string(sIdx));
 }
getControlName()
std::string ETOL::eGLPK::getControlName (const size_t & tIdx, const size_t & sIdx) static
Provides a consistent control variable name.
Parameters
tIdx a time index
sIdx a control index
Returns
a control variable name
Definition at line 107 of file eGLPK.cpp.
{
     return("u_" + std::to_string(tIdx) + "_" + std::to_string(sIdx));
 }
getParamName() [1/3]
std::string ETOL::eGLPK::getParamName (std::string name, const size_t & tIdx) static
Provides a consistent name for a custom variable.
Parameters
name a base name for the variable
tIdx a time index
Returns
a custom variable name
Definition at line 111 of file eGLPK.cpp.
{
     return(name + "_" + std::to_string(tIdx));
 }
Referenced by createObstacles(), and saaConstraint().
getParamName() [2/3]
std::string ETOL::eGLPK::getParamName (std::string name, const size_t & tIdx, const size_t & sIdx) static
Provides a consistent name for a custom variable.
Parameters
name a base name for the variable
tIdx a time index
sIdx a state index
Returns
a custom variable name
Definition at line 115 of file eGLPK.cpp.
{
     return(name + "_" + std::to_string(tIdx) + "_" + std::to_string(sIdx));
 }
getParamName() [3/3]
std::string ETOL::eGLPK::getParamName (std::string name, const size_t & Idx1, const size_t & Idx2, const size_t & Idx3) static
Provides a consistent name for a custom variable.
Parameters
name a base name for the variable
Idx1 a time index
Idx2 a state index
Idx3 an index
Returns
Definition at line 120 of file eGLPK.cpp.
{
     return(name + "_" + std::to_string(Idx1) + "_" + std::to_string(Idx2) +
             "_" + std::to_string(Idx3));
 }
getVarByName()
int ETOL::eGLPK::getVarByName (const std::string & name)
Provides a consistent variable index.
Parameters
name a base name for the variable
Returns
idx a variable index
Definition at line 249 of file eGLPK.cpp.
{
     return this->_var_map[name];
 }
createObstacles()
std::vector< closure_t > ETOL::eGLPK::createObstacles (TrajectoryOptimizer * t) static
Add obstacles.
Parameters
t TrajectoryOptimizer class pointer
Returns
a collection of obstacles
Definition at line 126 of file eGLPK.cpp.
{
     double tspan = t->getDt() * t->getNSteps();
     std::vector<closure_t> obstacles;
     int i = 0;
     for (const auto& obs : *t->getObstacles()) {
         std::vector<seg_t> lowers, uppers;
         // Compute slopes of obstacle
         TrajectoryOptimizer::calcSlopes(obs, &lowers, &uppers);
         obstacles.emplace_back(lowers, uppers);
         int j = 0;
         for (const auto& lower : lowers) {
             for (int k = 0; k < lower.size(); k++)
                 t->addParams({std::pair<PARAM_PAIR>(
                         getParamName("bot", i, j, k),
                         {var_t::BINARY, 0., 1., 0., tspan})});
             seg_t upper = uppers.at(j);
             for (int k = 0; k < upper.size(); k++)
                 t->addParams({std::pair<PARAM_PAIR>(
                         getParamName("top", i, j, k),
                         {var_t::BINARY, 0., 1., 0., tspan})});
             j++;
         }
         i++;
     }
     return obstacles;
 }
References ETOL::TrajectoryOptimizer::addParams(), ETOL::BINARY, ETOL::TrajectoryOptimizer::calcSlopes(), ETOL::TrajectoryOptimizer::getDt(), ETOL::TrajectoryOptimizer::getNSteps(), ETOL::TrajectoryOptimizer::getObstacles(), getParamName(), and obstacles.
Referenced by obsConstraint().
createTracks()
std::vector< track_t > ETOL::eGLPK::createTracks (TrajectoryOptimizer * t, int NSIDES) static
Add tracks.
Parameters
t TrajectoryOptimizer class pointer
NSIDES number of sides for a polygon approximation of a circle
Returns
a collection of tracks
Definition at line 157 of file eGLPK.cpp.
{
     double tspan = t->getDt() * t->getNSteps();
     std::vector<track_t> tracks;
     assert(NSIDES > 2);
     assert((NSIDES % 2) == 0);
     int i = 0;
     for (auto track : *t->getTracks()) {
         int j = 0;
         traj_t::iterator it;
         it = track.trajectory.begin();
         for (const auto& elem : track.trajectory) {
             double t0, tf;
             t0 = elem.first;
             std::advance(it, 1);
             if (it != track.trajectory.end())
                 tf = (*it).first;
             else
                 tf = tspan;
             param_configs_t configs = {var_t::BINARY, 0., 1., t0, tf};
             for (int k = 0; k < NSIDES; k++ )
                 t->addParams({std::pair<PARAM_PAIR>(
                                         getParamName("d", i, j, k), configs)});
             j++;
         }
         tracks.push_back(track);
         i++;
     }
     return tracks;
 }
References ETOL::TrajectoryOptimizer::addParams(), ETOL::BINARY, ETOL::TrajectoryOptimizer::getDt(), ETOL::TrajectoryOptimizer::getNSteps(), ETOL::TrajectoryOptimizer::getTracks(), NSIDES, and tracks.
Referenced by saaConstraint().
addObstacleSides()
std::vector< std::pair< std::vector< glpk_t >, glpk_bnd_t > > ETOL::eGLPK::addObstacleSides (seg_t seg, int sign, const std::string & name, int ind_i, int ind_j, int tIdx, std::vector< std::string > pnames, int BigM) static
Adds the side of an obstacle to the constraint set.
Parameters
seg a segment
name a base name for the constraint
ind_i an index
ind_j an index
tIdx a time index
pnames a set of parameter names
sign the sign of the edge's slope
BigM an arbitrary large scalar
Returns
parameters for a constraint
Definition at line 191 of file eGLPK.cpp.
                   {
     int ind_k = 0;
     std::vector<glpk_t> abs_obs;
     std::vector<std::pair<std::vector<glpk_t>, glpk_bnd_t>> abs_obsv;
     for (auto side : seg) {
         std::string r(eGLPK::getParamName(
                 eGLPK::getParamName(name, ind_i, ind_j, ind_k), tIdx));
         bool found(false);
         int i = 0;
         for (const auto& pname : pnames) {
             if (re2::RE2::FullMatch(pname, r)) {
                 abs_obs.emplace_back(pname, tIdx, -1, sign*BigM);
                 found = true;
                 break;
             }
             i++;
         }
         if (!found)
             break;
         double m = seg.at(ind_k).second.slope;
         abs_obs.emplace_back("x", tIdx, 0, -m);  // x
         abs_obs.emplace_back("x", tIdx, 1, 1);  // y
         double xa = std::get<0>(seg.at(ind_k).first);
         double ya = std::get<1>(seg.at(ind_k).first);
         double rhs = ya - m * xa;
         if (sign < 0)
             abs_obsv.emplace_back(abs_obs, glpk_bnd_t(GLPK_UNBOUND, rhs));
         else
             abs_obsv.emplace_back(abs_obs, glpk_bnd_t(rhs, GLPK_UNBOUND));
         abs_obs.clear();
         ind_k++;
     }
     return abs_obsv;
 }
References GLPK_UNBOUND.
Referenced by obsConstraint().
addObstacleSum()
std::vector< std::pair< std::vector< glpk_t >, glpk_bnd_t > > ETOL::eGLPK::addObstacleSum (const std::string & name, int ind_i, int ind_j, int tIdx, std::vector< std::string > pnames, int NSIDES) static
Adds the sum of binary variables for an obstacle.
Parameters
name a base name for the constraint
tIdx a time index
ind_i and index
ind_j an index
pnames a list of parameter names
NSIDES number of sides for a polygon approximation of a circle
Returns
parameters for a constraint
Definition at line 230 of file eGLPK.cpp.
{
     std::vector<glpk_t> abs;
     std::vector<std::pair<std::vector<glpk_t>, glpk_bnd_t>> abs_v;
     std::string r(eGLPK::getParamName(name, ind_i, ind_j) + "_[0-9]*_" +
                                             std::to_string(tIdx) + "$");
     for (const auto& pname : pnames) {
         if (re2::RE2::FullMatch(pname, r)) {
             abs.emplace_back(pname, tIdx, -1, 1);
         }
     }
     if (NSIDES > 0)
         abs_v.emplace_back(abs, glpk_bnd_t(GLPK_UNBOUND, NSIDES-0.5));
     else
         abs_v.emplace_back(abs, glpk_bnd_t(GLPK_UNBOUND, abs.size()-0.5));
     return abs_v;
 }
References GLPK_UNBOUND, and NSIDES.
Referenced by obsConstraint(), and saaConstraint().
createVars()
void ETOL::eGLPK::createVars () private
Add all variables to the GLPK model.
Definition at line 275 of file eGLPK.cpp.
{
     state_t::iterator l_it, u_it;
     state_var_t::iterator vt_it;
     try {
         for (int i = 0; i <= this->getNSteps(); i++) {
             // x_time#_state#
             l_it = this->getXlower().begin();
             u_it = this->getXupper().begin();
             vt_it = this->getXvartype().begin();
             for (int j = 0; j < this->getNStates(); j++) {
                 this->_var_cnt += 1;
                 this->_var_map.insert(std::pair<std::string, int>(
                         this->getStateName(i, j), this->_var_cnt));
                 glp_add_cols(this->_model, 1);
                 glp_set_col_name(this->_model, this->_var_cnt,
                                     this->getStateName(i, j).c_str());
                 glp_set_col_kind(this->_model, this->_var_cnt,
                                     this->getGLPKType(*(vt_it++)));
                 glp_set_col_bnds(this->_model, this->_var_cnt, GLP_DB,
                                     *(l_it++), *(u_it++));
             }
             // u_time#_state#
             l_it = this->getUlower().begin();
             u_it = this->getUupper().begin();
             vt_it = this->getUvartype().begin();
             for (int j = 0; j < this->getNControls(); j++) {  // ignore u_0
                 this->_var_cnt += 1;
                 this->_var_map.insert(std::pair<std::string, int>(
                         this->getControlName(i, j), this->_var_cnt));
                 glp_add_cols(this->_model, 1);
                 glp_set_col_name(this->_model, this->_var_cnt,
                         this->getControlName(i, j).c_str());
                 glp_set_col_kind(this->_model, this->_var_cnt,
                         this->getGLPKType(*(vt_it++)));
                 glp_set_col_bnds(this->_model, this->_var_cnt, GLP_DB,
                                     *(l_it++), *(u_it++));
             }
             // varName_time#
             double t = i * this->getDt();
             for (const auto& param : this->_parmaeters) {
                 if ((t >= param.second.tStart) && (t <= param.second.tStop)) {
                     this->_var_cnt += 1;
                     this->_var_map.insert(std::pair<std::string, int>(
                         this->getParamName(param.first, i), this->_var_cnt));
                     glp_add_cols(this->_model, 1);
                     glp_set_col_name(this->_model, this->_var_cnt,
                             this->getParamName(param.first, i).c_str());
                     glp_set_col_kind(this->_model, this->_var_cnt,
                             this->getGLPKType(param.second.varType));
                     glp_set_col_bnds(this->_model, this->_var_cnt, GLP_DB,
                             param.second.lbnd, param.second.ubnd);
                     this->params.push_back(this->_var_cnt);
                     this->pnames.push_back(this->getParamName(param.first, i));
                 }
             }
         }
     } catch (...) {
         std::cout << "Exception occurred at createVars";
         exit(EXIT_FAILURE);
     }
 }
Referenced by setup().
addX0()
void ETOL::eGLPK::addX0 () private
Add the initial state constraint to the GLPK model.
Definition at line 339 of file eGLPK.cpp.
                   {
     try {
         for (int i = 0; i < this->getRhorizon(); i++) {
             for (int j = 0; j < this->getNStates(); j++) {
                 if (!std::isnan(this->getX0().at(j))) {
                     this->_ind_cnt += 1;
                     this->_const_cnt += 1;
                     glp_add_rows(this->_model, 1);
                     glp_set_row_bnds(this->_model, this->_const_cnt, GLP_FX,
                             this->getX0().at(j), this->getX0().at(j));
                     this->_ia.push_back(this->_const_cnt);
                     this->_ja.push_back(this->getVarByName(
                                                     this->getStateName(i, j)));
                     this->_ar.push_back(1);
                 }
             }
         }
     } catch (...) {
         std::cout << "Exception occurred at addX0";
         exit(EXIT_FAILURE);
     }
 }
Referenced by setup().
addXf()
void ETOL::eGLPK::addXf () private
Add the goal state constraint to the GLPK model.
Definition at line 362 of file eGLPK.cpp.
                   {
     try {
         int i = this->getNSteps();
         for (int j = 0; j < this->getNStates(); j++) {
             if (!std::isnan(this->getXf().at(j))) {
                 this->_ind_cnt += 1;
                 this->_const_cnt += 1;
                 glp_add_rows(this->_model, 1);
                 glp_set_row_bnds(this->_model, this->_const_cnt, GLP_UP,
                                  this->getXf().at(j) - this->getXtol().at(j),
                                  this->getXf().at(j) + this->getXtol().at(j));
                 this->_ia.push_back(this->_const_cnt);
                 this->_ja.push_back(this->getVarByName(
                                         this->getStateName(i, j)));
                 this->_ar.push_back(1);
                 this->_ind_cnt += 1;
                 this->_const_cnt += 1;
                 glp_add_rows(this->_model, 1);
                 glp_set_row_bnds(this->_model, this->_const_cnt, GLP_LO,
                                  this->getXf().at(j) - this->getXtol().at(j),
                                  this->getXf().at(j) + this->getXtol().at(j));
                 this->_ia.push_back(this->_const_cnt);
                 this->_ja.push_back(this->getVarByName(
                                         this->getStateName(i, j)));
                 this->_ar.push_back(1);
             }
         }
     } catch (...) {
         std::cout << "Exception occurred at addXf";
         exit(EXIT_FAILURE);
     }
 }
Referenced by setup().
addConstr()
void ETOL::eGLPK::addConstr () private
Add the path constraints to the GLPK model.
Definition at line 396 of file eGLPK.cpp.
                       {
     try {
         std::any f_val;
         f_t* f;
         std::vector<std::pair<std::vector<glpk_t>, glpk_bnd_t>> Constr;
         for (int c = 0; c < this->_constraints.size(); c++) {
             f = this->_constraints.at(c);
             for (int k = 0; k <= this->getNSteps(); k++) {
                 f_val = (*f)(this->x, this->u, this->params, this->pnames, k,
                         this->getDt());
                 Constr = std::any_cast<std::vector<std::pair
                         <std::vector<glpk_t>, glpk_bnd_t>>>(f_val);
                 for (int i = 0; i < Constr.size(); i++) {
                     if (Constr[i].second._lb != GLPK_UNBOUND) {
                         this->_const_cnt += 1;
                         glp_add_rows(this->_model, 1);
                         glp_set_row_bnds(this->_model, this->_const_cnt,
                                 GLP_LO, Constr[i].second._lb,
                                          Constr[i].second._ub);
                         for (auto &j : Constr[i].first) {
                             this->_ind_cnt += 1;
                             this->_ia.push_back(this->_const_cnt);
                             if (j._sIdx >= 0) {
                                 this->_ja.push_back(
                                         this->getVarByName(
                                                 this->getParamName(j._name,
                                                         j._tIdx, j._sIdx)));
                             } else {
                                 this->_ja.push_back(
                                         this->getVarByName(j._name));
                             }
                             this->_ar.push_back(j._obj_coeff);
                         }
                     }
                     if (Constr[i].second._ub != GLPK_UNBOUND) {
                         this->_const_cnt += 1;
                         glp_add_rows(this->_model, 1);
                         glp_set_row_bnds(this->_model, this->_const_cnt,
                                 GLP_UP, Constr[i].second._lb,
                                          Constr[i].second._ub);
                         for (auto &j : Constr[i].first) {
                             this->_ind_cnt += 1;
                             this->_ia.push_back(this->_const_cnt);
                             if (j._sIdx >= 0) {
                                 this->_ja.push_back(
                                         this->getVarByName(
                                                 this->getParamName(j._name,
                                                         j._tIdx, j._sIdx)));
                             } else {
                                 this->_ja.push_back(
                                         this->getVarByName(j._name));
                             }
                             this->_ar.push_back(j._obj_coeff);
                         }
                     }
                 }
             }
         }
     } catch (...) {
         std::cout << "Exception occurred at addConstr";
         exit(EXIT_FAILURE);
     }
 }
References GLPK_UNBOUND.
Referenced by setup().
addDyn()
void ETOL::eGLPK::addDyn () private
Add the state dynamics to the GLPK model.
Definition at line 460 of file eGLPK.cpp.
                    {
     try {
         std::any f_val;
         f_t* f;
         std::vector<glpk_t> Dyn;
         for (int i = 0; i < this->getNStates(); i++) {
             f = this->_gradient.at(i);
             for (int k = this->getRhorizon(); k <= this->getNSteps(); k++) {
                 f_val = (*f)(this->x, this->u, this->params, this->pnames, k,
                         this->getDt());
                 Dyn = std::any_cast<std::vector<glpk_t>>(f_val);
                 this->_const_cnt += 1;
                 glp_add_rows(this->_model, 1);
                 glp_set_row_bnds(this->_model, this->_const_cnt, GLP_FX, 0, 0);
                 for (auto &j : Dyn) {
                     this->_ind_cnt += 1;
                     this->_ia.push_back(this->_const_cnt);
                     this->_ja.push_back(this->getVarByName(
                             this->getParamName(j._name, j._tIdx, j._sIdx)));
                     this->_ar.push_back(j._obj_coeff);
                 }
             }
         }
     } catch (...) {
         std::cout << "Exception occurred at addDyn";
         exit(EXIT_FAILURE);
     }
 }
Referenced by setup().
addObj()
void ETOL::eGLPK::addObj () private
Add the objective function to the GLPK model.
Definition at line 489 of file eGLPK.cpp.
                    {
     try {
         std::any f_val;
         std::vector<glpk_t> Obj;
         for (int k = 1; k <= this->getNSteps(); k++) {
             f_val = (*this->_objective)(this->x, this->u, this->params,
                     this->pnames, k, this->getDt());
             Obj = std::any_cast<std::vector<glpk_t>>(f_val);
             for (auto &i : Obj) {
                 glp_set_obj_coef(this->_model,
                         this->getVarByName(this->getParamName(i._name,
                                 i._tIdx, i._sIdx)), i._obj_coeff);
             }
         }
         if (this->isMaximized())
             glp_set_obj_dir(this->_model, GLP_MAX);
         else
             glp_set_obj_dir(this->_model, GLP_MIN);
     } catch (...) {
         std::cout << "Exception occurred at addObj";
         exit(EXIT_FAILURE);
     }
 }
Referenced by setup().
getTraj()
void ETOL::eGLPK::getTraj () private
Get the trajectory results from the GLPK model.
Definition at line 513 of file eGLPK.cpp.
                     {
     try {
         int var;
         traj_t* xtraj = this->getXtraj();
         xtraj->clear();
         for (int i = 0; i <= this->getNSteps(); i++) {
             state_t x_sol;
             double t = i * this->getDt();
             for (int j = 0; j < this->getNStates(); j++) {
                 var = this->getVarByName(this->getStateName(i, j));
                 x_sol.push_back(glp_mip_col_val(this->_model, var));
             }
             xtraj->push_back(traj_elem_t(t, x_sol));
         }
         traj_t* utraj = this->getUtraj();
         utraj->clear();
         for (int i = 0; i <= this->getNSteps(); i++) {
             state_t u_sol;
             double t = i * this->getDt();
             for (int j = 0; j < this->getNControls(); j++) {
                 var = this->getVarByName(this->getControlName(i, j));
                 u_sol.push_back(glp_mip_col_val(this->_model, var));
             }
             utraj->push_back(traj_elem_t(t, u_sol));
         }
     } catch (...) {
         std::cout << "Exception occurred at getTraj";
         exit(EXIT_FAILURE);
     }
 }
Referenced by solve().
Member Data Documentation
_model
glp_prob* ETOL::eGLPK::_model protected
Pointer to a GLPK model
Definition at line 186 of file eGLPK.hpp.
Referenced by close(), eGLPK(), setup(), and solve().
_params
glp_iocp ETOL::eGLPK::_params protected
GLPK parameters
Definition at line 187 of file eGLPK.hpp.
Referenced by eGLPK(), and solve().
_status_relax
int ETOL::eGLPK::_status_relax protected
status of integer-relaxed problem
Definition at line 188 of file eGLPK.hpp.
Referenced by eGLPK(), and solve().
_status_mip
int ETOL::eGLPK::_status_mip protected
status of integer problem
Definition at line 189 of file eGLPK.hpp.
Referenced by eGLPK(), and solve().
_var_cnt
int ETOL::eGLPK::_var_cnt protected
counter for the number of variables
Definition at line 190 of file eGLPK.hpp.
Referenced by eGLPK().
_const_cnt
int ETOL::eGLPK::_const_cnt protected
counter for the number of constraints
Definition at line 191 of file eGLPK.hpp.
Referenced by eGLPK().
_ind_cnt
int ETOL::eGLPK::_ind_cnt protected
counter for the number of non-zero element in constraint matrix
Definition at line 192 of file eGLPK.hpp.
Referenced by eGLPK(), and setup().
_ia
std::vector<int> ETOL::eGLPK::_ia {0} protected
The first index of non-zero element in constraint matrix
Definition at line 193 of file eGLPK.hpp.
Referenced by setup().
_ja
std::vector<int> ETOL::eGLPK::_ja {0} protected
The second index of non-zero element in constraint matrix
Definition at line 194 of file eGLPK.hpp.
Referenced by setup().
_ar
std::vector<double> ETOL::eGLPK::_ar {0} protected
The value of non-zero element in constraint matrix
Definition at line 195 of file eGLPK.hpp.
Referenced by setup().
_var_map
std::map<std::string, int> ETOL::eGLPK::_var_map protected
map between name and value of non-zero element in constraint matrix
Definition at line 196 of file eGLPK.hpp.
x
vector_t ETOL::eGLPK::x protected
State Trajectory
Definition at line 198 of file eGLPK.hpp.
Referenced by setup().
u
vector_t ETOL::eGLPK::u protected
Control Trajectory
Definition at line 199 of file eGLPK.hpp.
Referenced by setup().
params
vector_t ETOL::eGLPK::params protected
Path constraint configs
Definition at line 200 of file eGLPK.hpp.
pnames
std::vector<std::string> ETOL::eGLPK::pnames protected
Path constraint names
Definition at line 201 of file eGLPK.hpp.
The documentation for this class was generated from the following files:
C:/msys64/home/admin/ETOL/include/ETOL/eGLPK.hpp
C:/msys64/home/admin/ETOL/src/eGLPK/eGLPK.cpp