ETOL: ETOL::eGurobi Class Reference
ETOL::eGurobi Class Reference
#include <eGurobi.hpp>
Public Member Functions
eGurobi ()
Constructor for a Gurobi interface.
virtual ~eGurobi ()
void setup ()
Constructs an optimization problem from settings.
void solve ()
Solves the trajectory optimization problem.
void debug ()
Generates debug information.
void close ()
Closes all dynamically allocated resources.
const size_t getNConstr () const
Returns the cached number of constraints.
Public Member Functions inherited from ETOL::TrajectoryOptimizer
TrajectoryOptimizer ()
Initializes a TrajectoryOptimizer object.
virtual ~TrajectoryOptimizer ()
const double getScore () const
void resetConfigs ()
Sets all configurations to default values.
void printConfigs ()
Prints configurations onto the console.
void loadConfigs (const char *filepath)
Loads configurations from an XML file.
void saveConfigs (const char *filepath)
Saves configurations to an XML file.
void addParams (std::list< param_t > params)
Adds a non-state or non-control variable to the problem.
void addExclZone (border_t *border)
Add an exclusion zone to the problem.
void addAdjTrack (track_t *track)
Add the track of an adjacent or nearby object.
void plotX (const int idx)
Plot the time history of a state variable.
void plotU (const int idx)
Plot the time history of a control variable.
state_t & getX0 ()
Get the initial state.
void setX0 (const state_t &x0)
Set an initial state.
state_t & getXf ()
Get the goal state.
void setXf (const state_t &xf)
Set the goal state.
const size_t getNControls () const
Get the number of control variables.
const size_t getNStates () const
Get the number of state variables.
state_t & getXlower ()
Get the states' lower bound.
void setXlower (const state_t &xlower)
Set the states' lower bound.
state_t & getXupper ()
Get the states' upper bound.
void setXupper (const state_t &xupper)
Set the states' upper bound.
state_var_t & getXvartype ()
Get the states' variable type.
void setXvartype (const state_var_t &xvartype)
Set the states' variable type.
const double getDt () const
Get the time step size.
void setDt (double dt)
Set the time step size.
const size_t getNSteps () const
Get the number of time steps.
void setNSteps (const size_t nSteps)
Set the number of steps.
state_t & getXtol ()
Get the states' error tolerance.
void setXtol (const state_t &xtol)
Set the states' error tolerance.
state_t & getUlower ()
Get the controls' lower bound.
void setUlower (const state_t &ulower)
Set the control's lower bound.
state_t & getUupper ()
Get the controls' upper bound.
void setUupper (const state_t &uupper)
Set the controls' upper bound.
state_var_t & getUvartype ()
Get the control variables' type.
void setUvartype (const state_var_t &uvartype)
Set the control variables' type.
const size_t getUrhorizon () const
Get the controls' reverse time horizon.
void setUrhorizon (const size_t nu4dyn)
Sets the reverse time horizon for control variables.
const size_t getXrhorizon () const
Get the states' reverse time horizon.
void setXrhorizon (const size_t nx4dyn)
Sets the reverse time horizon for state variables.
size_t getRhorizon () const
Get the maximium possible reverse time horizon.
void setNControls (const size_t nControls)
Get the number of control variables.
void setNStates (const size_t nStates)
Get the number of state variables.
void setEqConstraints (std::vector< f_t * > constraints)
Set the equality constraints.
void setLessEqConstraints (std::vector< f_t * > constraints)
Set the inequality constraints.
void setConstraints (std::vector< f_t * > constraints)
Set sense-agnostic constraint functions.
void setGradient (std::vector< f_t * > gradient)
Set the states' time derivative function.
void setObjective (f_t *objective)
Set the objective function.
traj_t * getUtraj ()
Get the pointer to the computed control trajectory.
traj_t * getXtraj ()
Get the pointer to the computed state trajectory.
const f_t * getObjective () const
Set the objective function.
std::vector< f_t * > * getGradient ()
Get the time derivative functions for the states.
std::vector< f_t * > * getEqConstraints ()
Get the equality constraint functions.
std::vector< f_t * > * getLessEqConstraints ()
Get the inequality constraint functions.
std::vector< f_t * > * getConstraints ()
Get the sense-agnostic constraint functions.
std::vector< border_t > * getObstacles_Raw ()
Get the pointer to the unprocessed exclusion zones.
std::list< region_t > * getObstacles ()
Get the pointer to the polygon partitioned exclusion zones.
std::list< track_t > * getTracks ()
Get the pointer to the moving exclusion zones.
bool isMaximized () const
Get the optimization direction.
void setMaximize (const bool maximize)
Set the optimization direction.
size_t getNExclZones ()
Get the number of exclusion zones.
size_t getNTracks ()
Get the number of moving exclusion zones.
Static Public Member Functions
static char getGRBType (var_t varType)
Converts the variable type to a Gurobi compliant type.
static std::string getStateName (const size_t &tIdx, const size_t &sIdx)
Provides a consistent state variable name.
static std::string getControlName (const size_t &tIdx, const size_t &sIdx)
Provides a consistent control variable name.
static std::string getParamName (const std::string name, const size_t &tIdx)
Provides a consistent name for a custom variable.
Static Public Member Functions inherited from ETOL::TrajectoryOptimizer
static region_t genRegion (border_t *border)
Create convex partitions.
static void calcSlopes (const region_t &region, std::vector< seg_t > *lower, std::vector< seg_t > *upper)
Computes slopes for lower and upper segments for convex partitions.
static void plot (traj_t *traj, const std::string title="Time History", const std::string tlab="t", const std::string xlab="", double tmin=DBL_MAX, double tmax=DBL_MIN, double xmin=DBL_MAX, double xmax=DBL_MIN)
Plots a trajectory.
static void plotXY (traj_t *traj, size_t xIdx=0, size_t yIdx=1, const std::string title="XY Plot", const std::string xlab="x", const std::string ylab="y", double xmin=DBL_MAX, double xmax=DBL_MIN, double ymin=DBL_MAX, double ymax=DBL_MIN)
Creates a XY-plot.
static void plotXY_wExclZones (traj_t *traj, std::list< region_t > *zones=NULL, size_t xIdx=0, size_t yIdx=1, const std::string title="XY Plot", const std::string xlab="x", const std::string ylab="y", double xmin=DBL_MAX, double xmax=DBL_MIN, double ymin=DBL_MAX, double ymax=DBL_MIN)
Creates a XY-plot wth exclusion zones.
static std::string animate2D (traj_t *traj, const int framerate=2, bool toFile=false, std::string outFile="animation.mp4", std::list< region_t > *obstacles=NULL, std::list< track_t > *tracks=NULL, size_t xIdx=0, size_t yIdx=1, const std::string title="notitle", const std::string xlab="x", const std::string ylab="y", double xmin=DBL_MAX, double xmax=DBL_MIN, double ymin=DBL_MAX, double ymax=DBL_MIN)
Creates a 2D animation with static and moving exclusion zones.
static std::string save (traj_t *traj, std::string fp="traj.csv")
Saves trajectories to a file.
Protected Member Functions
GRBLinExpr _objfunc (const size_t &tIdx)
Converts the objective function to a Gurobi expression.
GRBLinExpr _dynConstr (const size_t &tIdx, const size_t &sIdx)
Converts the gradient function to a Gurobi expression.
fout_grb_t _pathConstr (const size_t &tIdx, const size_t &kIdx)
Converts the constraint functions to a Gurobi expression.
Protected Member Functions inherited from ETOL::TrajectoryOptimizer
void errorHandler ()
An error handler that is called in try-catch blocks.
void setScore (const double score)
Stores the eSovler's objective function result.
Protected Attributes
GRBEnv * _env
GRBModel * _model
GRBException * _eGRB
vector_t _params
std::vector< std::string > _pnames
std::atomic< size_t > _nConstr
Protected Attributes inherited from ETOL::TrajectoryOptimizer
bool _maximize
double _score
double _dt
size_t _nSteps
size_t _nStates
size_t _nControls
state_t _x0
state_t _xlower
state_t _xupper
state_var_t _xvartype
state_t _xtol
state_t _xf
state_t _ulower
state_t _uupper
state_var_t _uvartype
size_t _xrhorizon
size_t _urhorizon
size_t _rhorizon
paramset_t _parmaeters
std::vector< border_t > _obstacles_raw
std::list< region_t > _obstacles
std::list< track_t > _tracks
std::vector< f_t * > _constraints
std::vector< f_t * > _eq
std::vector< f_t * > _lesseq
std::vector< f_t * > _gradient
f_t * _objective
traj_t _xtraj
traj_t _utraj
std::bad_any_cast * _eAny
Private Member Functions
void errorHandler ()
An error handler for Gurobi exceptions.
void createVars ()
Add all variables to the Gurobi model.
void addX0 ()
Add the initial state constraint to the Gurobi model.
void addXf ()
Add the goal state constraint to the Gurobi model.
void addConstr ()
Add the path constraints to the Gurobi model.
void addDyn ()
Add the state dynamics to the Gurobi model.
void addObj ()
Add the objective function to the Gurobi model.
void getTraj ()
Get the trajectory results from the Gurobi model.
Private Attributes
GRBEnv env_
GRBModel model_
Detailed Description
Definition at line 24 of file eGurobi.hpp.
Constructor & Destructor Documentation
eGurobi()
ETOL::eGurobi::eGurobi ()
Constructor for a Gurobi interface.
Definition at line 23 of file eGurobi.cpp.
     : eGurobi::TrajectoryOptimizer(), env_(GRBEnv()), model_(GRBModel(env_)),
       _nConstr(ATOMIC_VAR_INIT(0)), _eGRB(NULL)  {
     this->_env = &env_;
     this->_model = &model_;
 }
References _env, _model, env_, and model_.
~eGurobi()
ETOL::eGurobi::~eGurobi () virtual
Definition at line 32 of file eGurobi.cpp.
 {}
Member Function Documentation
setup()
void ETOL::eGurobi::setup () virtual
Constructs an optimization problem from settings.
Implements ETOL::TrajectoryOptimizer.
Definition at line 71 of file eGurobi.cpp.
                     {
     // Vector size must match number of states
     // Fill unused vector entries with nan
     assert(this->getX0().size() == this->getNStates());
     assert(this->getXf().size() == this->getNStates());
     assert(this->getXlower().size() == this->getNStates());
     assert(this->getXupper().size() == this->getNStates());
     assert(this->getXvartype().size() == this->getNStates());
     try {
         this->_model->reset();
         this->createVars();
         this->addX0();
         this->addXf();
         this->addDyn();
         this->addConstr();
         this->addObj();
     } catch(GRBException& e) {
         this->_eGRB = &e;
         this->errorHandler();
     }
 }
References _eGRB, _model, addConstr(), addDyn(), addObj(), addX0(), addXf(), createVars(), errorHandler(), ETOL::TrajectoryOptimizer::getNStates(), ETOL::TrajectoryOptimizer::getX0(), ETOL::TrajectoryOptimizer::getXf(), ETOL::TrajectoryOptimizer::getXlower(), ETOL::TrajectoryOptimizer::getXupper(), and ETOL::TrajectoryOptimizer::getXvartype().
solve()
void ETOL::eGurobi::solve () virtual
Solves the trajectory optimization problem.
Implements ETOL::TrajectoryOptimizer.
Definition at line 94 of file eGurobi.cpp.
                     {
     try {
         this->_model->optimize();
         if (this->_model->get(GRB_IntAttr_Status) == GRB_OPTIMAL) {
             setScore(_model->get(::GRB_DoubleAttr_ObjVal));
             this->getTraj();
         }
     } catch(GRBException& e) {
         this->_eGRB = &e;
         this->errorHandler();
     }
 }
References _eGRB, _model, errorHandler(), getTraj(), and ETOL::TrajectoryOptimizer::setScore().
debug()
void ETOL::eGurobi::debug () virtual
Generates debug information.
Implements ETOL::TrajectoryOptimizer.
Definition at line 107 of file eGurobi.cpp.
                     {
     this->_model->write("debug.lp");
     std::cout << "Debug information written to 'debug.lp'" << std::endl;
 }
References _model.
close()
void ETOL::eGurobi::close () virtual
Closes all dynamically allocated resources.
Implements ETOL::TrajectoryOptimizer.
Definition at line 112 of file eGurobi.cpp.
 {}
getNConstr()
const size_t ETOL::eGurobi::getNConstr () const
Returns the cached number of constraints.
Returns
an integer number of constraints
Definition at line 65 of file eGurobi.cpp.
{
     return _nConstr;
 }
References _nConstr.
getGRBType()
char ETOL::eGurobi::getGRBType (var_t varType) static
Converts the variable type to a Gurobi compliant type.
Parameters
varType a ETOL variable type
Returns
a Gurobi variable type
Definition at line 49 of file eGurobi.cpp.
{
     switch (varType) {
         case var_t::CONTINUOUS:
             return GRB_CONTINUOUS;
         case var_t::INTERGER:
             return GRB_INTEGER;
         case var_t::BINARY:
             return GRB_BINARY;
         default :
             assert(true);  // Type not implemented
     }
     return GRB_CONTINUOUS;
 }
References ETOL::BINARY, ETOL::CONTINUOUS, and ETOL::INTERGER.
Referenced by createVars().
getStateName()
std::string ETOL::eGurobi::getStateName (const size_t & tIdx, const size_t & sIdx) static
Provides a consistent state variable name.
Parameters
tIdx a time index
sIdx a state index
Returns
a state vairable name
Definition at line 36 of file eGurobi.cpp.
{
     return("x_" + std::to_string(tIdx) + "_" + std::to_string(sIdx));
 }
Referenced by _dynConstr(), _objfunc(), _pathConstr(), addX0(), addXf(), createVars(), and getTraj().
getControlName()
std::string ETOL::eGurobi::getControlName (const size_t & tIdx, const size_t & sIdx) static
Provides a consistent control variable name.
Parameters
tIdx a time index
sIdx a control index
Returns
a control variable name
Definition at line 40 of file eGurobi.cpp.
{
     return("u_" + std::to_string(tIdx) + "_" + std::to_string(sIdx));
 }
Referenced by _dynConstr(), _objfunc(), _pathConstr(), createVars(), and getTraj().
getParamName()
std::string ETOL::eGurobi::getParamName (const std::string name, const size_t & tIdx) static
Provides a consistent name for a custom variable.
Parameters
name a base name for the variable
tIdx a time index
Returns
a custom variable name
Definition at line 44 of file eGurobi.cpp.
{
     return(name + "_" + std::to_string(kIdx));
 }
Referenced by createVars(), and saaConstraint().
_objfunc()
GRBLinExpr ETOL::eGurobi::_objfunc (const size_t & tIdx) protected
Converts the objective function to a Gurobi expression.
Parameters
tIdx a time index
Returns
a Gurobi linear expression
This function is called for each time index and added to objective function in the Gurobi model
Definition at line 116 of file eGurobi.cpp.
{
     std::any f_val;
     GRBLinExpr expr;
     vector_t x;
     vector_t u;
     for (size_t j(0); j < this->_nStates; j++) {
         GRBVar var = (*this->_model).getVarByName(getStateName(tIdx, j));
         x.push_back(var);
     }
     for (size_t j(0); j < this->_nControls; j++) {
         GRBVar var = (*this->_model).getVarByName(getControlName(tIdx, j));
         u.push_back(var);
     }
     f_val = (*this->_objective)(
             x, u, this->_params, this->_pnames, tIdx, this->getDt());
     try {
         expr = std::any_cast<GRBLinExpr>(f_val);
     } catch(std::bad_any_cast& e) {
         this->_eAny = &e;
         errorHandler();
     }
     return expr;
 }
References ETOL::TrajectoryOptimizer::_eAny, _model, ETOL::TrajectoryOptimizer::_nControls, ETOL::TrajectoryOptimizer::_nStates, ETOL::TrajectoryOptimizer::_objective, _params, _pnames, errorHandler(), getControlName(), ETOL::TrajectoryOptimizer::getDt(), and getStateName().
Referenced by addObj().
_dynConstr()
GRBLinExpr ETOL::eGurobi::_dynConstr (const size_t & tIdx, const size_t & sIdx) protected
Converts the gradient function to a Gurobi expression.
Parameters
tIdx a time index
sIdx a state index
Returns
a Gurobi linear expression
This function is called for each time index and added to as a nex constraint to the Gurobi model
Definition at line 141 of file eGurobi.cpp.
{
     std::any f_val;
     GRBLinExpr expr;
     vector_t x;
     vector_t u;
     for (size_t k(0); k <= this->getXrhorizon(); k++) {
         for (size_t j(0); j < this->_nStates; j++) {
             size_t i = tIdx-k;
             GRBVar var = (*this->_model).getVarByName(getStateName(i, j));
             x.push_back(var);
         }
     }
     for (size_t k(0); k <= this->getUrhorizon(); k ++) {
         for (size_t j(0) ; j < this->_nControls; j++) {
             size_t i = tIdx-k;
             GRBVar var = (*this->_model).getVarByName(getControlName(i, j));
             u.push_back(var);
         }
     }
     f_t* f = _gradient.at(sIdx);
     f_val = (*f)(x, u, this->_params, this->_pnames, tIdx, this->getDt());
     try {
         expr = std::any_cast<GRBLinExpr>(f_val);
     } catch(std::bad_any_cast& e) {
         this->_eAny = &e;
         errorHandler();
     }
     return expr;
 }
References ETOL::TrajectoryOptimizer::_eAny, ETOL::TrajectoryOptimizer::_gradient, _model, ETOL::TrajectoryOptimizer::_nControls, ETOL::TrajectoryOptimizer::_nStates, _params, _pnames, errorHandler(), getControlName(), ETOL::TrajectoryOptimizer::getDt(), getStateName(), ETOL::TrajectoryOptimizer::getUrhorizon(), and ETOL::TrajectoryOptimizer::getXrhorizon().
_pathConstr()
fout_grb_t ETOL::eGurobi::_pathConstr (const size_t & tIdx, const size_t & kIdx) protected
Converts the constraint functions to a Gurobi expression.
Parameters
tIdx a time index
kIdx a path constraint index
Returns
parameters for a Gurobi constraint
This function is called for each time index and path constraint. The result is added as a new constraint to the Gurobi model.
Definition at line 172 of file eGurobi.cpp.
{
     std::any p_val;
     fout_grb_t fout;
     vector_t x;
     vector_t u;
     for (size_t j(0); j < this->_nStates; j++) {
         GRBVar var = (*this->_model).getVarByName(getStateName(tIdx, j));
         x.push_back(var);
     }
     for (size_t j(0); j < this->_nControls; j++) {
         GRBVar var = (*this->_model).getVarByName(getControlName(tIdx, j));
         u.push_back(var);
     }
     f_t* p = this->_constraints.at(kIdx);
     p_val = (*p)(x, u, this->_params, this->_pnames, tIdx, this->getDt());
     try {
         fout = std::any_cast<fout_grb_t>(p_val);
     } catch(std::bad_any_cast& e) {
         this->_eAny = &e;
         errorHandler();
     }
     return fout;
 }
References ETOL::TrajectoryOptimizer::_constraints, ETOL::TrajectoryOptimizer::_eAny, _model, ETOL::TrajectoryOptimizer::_nControls, ETOL::TrajectoryOptimizer::_nStates, _params, _pnames, errorHandler(), getControlName(), ETOL::TrajectoryOptimizer::getDt(), and getStateName().
Referenced by addConstr().
errorHandler()
void ETOL::eGurobi::errorHandler () private
An error handler for Gurobi exceptions.
Prints a Gurobi error message to the console
Definition at line 200 of file eGurobi.cpp.
{
     TrajectoryOptimizer::errorHandler();
     if (this->_eGRB != NULL) {
         std::string msg = this->_eGRB->getMessage();
         fprintf(stderr, "%s", msg.c_str());
         assert(true);
         exit(EXIT_FAILURE);
     }
 }
References _eGRB, and ETOL::TrajectoryOptimizer::errorHandler().
Referenced by _dynConstr(), _objfunc(), _pathConstr(), addConstr(), addDyn(), addObj(), addX0(), addXf(), createVars(), getTraj(), setup(), and solve().
createVars()
void ETOL::eGurobi::createVars () private
Add all variables to the Gurobi model.
State variables names are x_time::_state#. Control variable names are u_time::_state#. Path constraint variable names are varName_time#
Definition at line 215 of file eGurobi.cpp.
{
     state_t::iterator l_it, u_it;
     state_var_t::iterator vt_it;
     try {
         for (size_t k(0); k <= this->getNSteps(); k++) {
             // x_time#_state#
             l_it = this->getXlower().begin();
             u_it = this->getXupper().begin();
             vt_it = this->getXvartype().begin();
             for (size_t j(0); j < this->getNStates(); j++) {
                 this->_model->addVar(*(l_it++), *(u_it++), 0.0,
                         getGRBType(*(vt_it++)), getStateName(k, j));
             }
             // u_time#_state#
             l_it = this->getUlower().begin();
             u_it = this->getUupper().begin();
             vt_it = this->getUvartype().begin();
             for (size_t j(0); j < this->getNControls(); j++) {
                 this->_model->addVar(*(l_it++), *(u_it++), 0.0,
                         getGRBType(*(vt_it++)), getControlName(k, j));
             }
             // varName_time#
             double t = static_cast<double>(k) * this->getDt();
             for (auto param : this->_parmaeters) {
                 if ((t >= param.second.tStart) && (t <= param.second.tStop)) {
                     GRBVar var;
                     var = (this->_model->addVar(
                             param.second.lbnd, param.second.ubnd, 0.0,
                             getGRBType(param.second.varType),
                             getParamName(param.first, k)));
                     this->_params.push_back(var);
                     this->_pnames.push_back(getParamName(param.first, k));
                 }
             }
         }
         this->_model->update();
     } catch (GRBException& ex) {
         this->_eGRB = &ex;
         errorHandler();
     }
 }
References _eGRB, _model, _params, ETOL::TrajectoryOptimizer::_parmaeters, _pnames, errorHandler(), getControlName(), ETOL::TrajectoryOptimizer::getDt(), getGRBType(), ETOL::TrajectoryOptimizer::getNControls(), ETOL::TrajectoryOptimizer::getNStates(), ETOL::TrajectoryOptimizer::getNSteps(), getParamName(), getStateName(), ETOL::TrajectoryOptimizer::getUlower(), ETOL::TrajectoryOptimizer::getUupper(), ETOL::TrajectoryOptimizer::getUvartype(), ETOL::TrajectoryOptimizer::getXlower(), ETOL::TrajectoryOptimizer::getXupper(), and ETOL::TrajectoryOptimizer::getXvartype().
Referenced by setup().
addX0()
void ETOL::eGurobi::addX0 () private
Add the initial state constraint to the Gurobi model.
Definition at line 259 of file eGurobi.cpp.
                     {
     try {
         GRBLinExpr expr = GRBLinExpr();
         double coeff = 1.0;
         for (size_t i(0); i < this->getRhorizon(); i++) {
             for (size_t j(0); j < this->getNStates(); j++) {
                 if (!std::isnan(this->getX0().at(j))) {
                     GRBVar var = this->_model->getVarByName(getStateName(i, j));
                     GRBVar* varptr = &var;
                     expr.addTerms(&coeff, varptr, 1);
                     this->_model->addConstr(
                             expr, GRB_EQUAL, this->getX0().at(j),
                             "c" + std::to_string((size_t)(this->_nConstr++)));
                     expr.clear();
                 }
             }
         }
         this->_model->update();
     } catch (GRBException& ex) {
         this->_eGRB = &ex;
         errorHandler();
     }
 }
References _eGRB, _model, _nConstr, errorHandler(), ETOL::TrajectoryOptimizer::getNStates(), ETOL::TrajectoryOptimizer::getRhorizon(), getStateName(), and ETOL::TrajectoryOptimizer::getX0().
Referenced by setup().
addXf()
void ETOL::eGurobi::addXf () private
Add the goal state constraint to the Gurobi model.
Definition at line 283 of file eGurobi.cpp.
                     {
     GRBLinExpr expr = GRBLinExpr();
     double coeff = 1.0;
     size_t i = this->getNSteps();
     std::string n(std::to_string(this->getNSteps()) + "_");
     try {
         for (size_t j(0); j < this->getNStates(); j++) {
             if (!std::isnan(this->getXf().at(j))) {
                 GRBVar var = this->_model->getVarByName(
                         getStateName(i, j));
                 expr.addTerms(&coeff, &var, 1);
                 this->_model->addConstr(expr, GRB_LESS_EQUAL,
                         this->getXf().at(j) + this->getXtol().at(j),
                         "c" + std::to_string((size_t)(this->_nConstr++)));
                 this->_model->addConstr(expr, GRB_GREATER_EQUAL,
                             this->getXf().at(j) - this->getXtol().at(j),
                             "c" + std::to_string((size_t)(this->_nConstr++)));
                 expr.clear();
             }
         }
         this->_model->update();
     } catch (GRBException& ex) {
         this->_eGRB = &ex;
         errorHandler();
     }
 }
References _eGRB, _model, _nConstr, errorHandler(), ETOL::TrajectoryOptimizer::getNStates(), ETOL::TrajectoryOptimizer::getNSteps(), getStateName(), ETOL::TrajectoryOptimizer::getXf(), and ETOL::TrajectoryOptimizer::getXtol().
Referenced by setup().
addConstr()
void ETOL::eGurobi::addConstr () private
Add the path constraints to the Gurobi model.
Definition at line 310 of file eGurobi.cpp.
{
     try {
         for (size_t k(0); k < this->_constraints.size(); k++) {
             for (size_t i(0); i <= this->getNSteps(); i++) {
                 fout_grb_t fout = this->_pathConstr(i, k);
                 for (auto grb : fout) {
                     this->_model->addConstr(grb.expr, grb.sense, grb.rhs,
                             "c" + std::to_string((size_t)(this->_nConstr++)));
                 }
             }
         }
         this->_model->update();
     } catch (GRBException& ex) {
         this->_eGRB = &ex;
         errorHandler();
     }
 }
References ETOL::TrajectoryOptimizer::_constraints, _eGRB, _model, _pathConstr(), errorHandler(), and ETOL::TrajectoryOptimizer::getNSteps().
Referenced by setup().
addDyn()
void ETOL::eGurobi::addDyn () private
Add the state dynamics to the Gurobi model.
Definition at line 328 of file eGurobi.cpp.
                      {
     try {
         for (size_t i = this->getRhorizon(); i <= this->getNSteps(); i++) {
             for (size_t j(0); j < this->getNStates(); j++)
                 this->_model->addConstr(this->_dynConstr(i, j), GRB_EQUAL, 0.0,
                         "c" + std::to_string((size_t)(this->_nConstr++)));
         }
         this->_model->update();
     } catch (GRBException& ex) {
         this->_eGRB = &ex;
         errorHandler();
     }
 }
References _eGRB, _model, _nConstr, errorHandler(), ETOL::TrajectoryOptimizer::getNStates(), ETOL::TrajectoryOptimizer::getNSteps(), and ETOL::TrajectoryOptimizer::getRhorizon().
Referenced by setup().
addObj()
void ETOL::eGurobi::addObj () private
Add the objective function to the Gurobi model.
Definition at line 342 of file eGurobi.cpp.
                      {
     try {
         GRBLinExpr expr = this->_objfunc(0);
         for (size_t i(1); i <= this->getNSteps(); i++)
             expr += this->_objfunc(i);
         if (this->isMaximized())
             this->_model->setObjective(expr, GRB_MAXIMIZE);
         else
             this->_model->setObjective(expr, GRB_MINIMIZE);
         this->_model->update();
     } catch (GRBException& ex) {
         this->_eGRB = &ex;
         errorHandler();
     }
 }
References _eGRB, _model, _objfunc(), errorHandler(), ETOL::TrajectoryOptimizer::getNSteps(), and ETOL::TrajectoryOptimizer::isMaximized().
Referenced by setup().
getTraj()
void ETOL::eGurobi::getTraj () private
Get the trajectory results from the Gurobi model.
Definition at line 360 of file eGurobi.cpp.
                       {
     try    {
         traj_t* xtraj = this->getXtraj();
         xtraj->clear();
         for (size_t i(0); i <= this->getNSteps(); i++) {
             state_t x;
             double t = static_cast<double>(i) * this->getDt();
             for (size_t j(0); j < this->getNStates(); j++) {
                 GRBVar var = this->_model->getVarByName(getStateName(i, j));
                 x.push_back(var.get(GRB_DoubleAttr_X));
             }
             xtraj->push_back(traj_elem_t(t, x));
         }
         traj_t* utraj = this->getUtraj();
         utraj->clear();
         for (size_t i(0); i <= this->getNSteps(); i++) {
             state_t u;
             double t = static_cast<double>(i) * this->getDt();
             for (size_t j(0); j < this->getNControls(); j++) {
                 GRBVar var = this->_model->getVarByName(getControlName(i, j));
                 u.push_back(var.get(GRB_DoubleAttr_X));
             }
             utraj->push_back(traj_elem_t(t, u));
         }
     } catch (GRBException& ex) {
         this->_eGRB = &ex;
         errorHandler();
     }
 }
References _eGRB, _model, errorHandler(), getControlName(), ETOL::TrajectoryOptimizer::getDt(), ETOL::TrajectoryOptimizer::getNControls(), ETOL::TrajectoryOptimizer::getNStates(), ETOL::TrajectoryOptimizer::getNSteps(), getStateName(), ETOL::TrajectoryOptimizer::getUtraj(), and ETOL::TrajectoryOptimizer::getXtraj().
Referenced by solve().
Member Data Documentation
_env
GRBEnv* ETOL::eGurobi::_env protected
Pointer to a Gurobi environment
Definition at line 94 of file eGurobi.hpp.
Referenced by eGurobi().
_model
GRBModel* ETOL::eGurobi::_model protected
Pointer to a Gurobi model
Definition at line 95 of file eGurobi.hpp.
Referenced by _dynConstr(), _objfunc(), _pathConstr(), addConstr(), addDyn(), addObj(), addX0(), addXf(), createVars(), debug(), eGurobi(), getTraj(), setup(), and solve().
_eGRB
GRBException* ETOL::eGurobi::_eGRB protected
Pointer to a Gurobi exception
Definition at line 96 of file eGurobi.hpp.
Referenced by addConstr(), addDyn(), addObj(), addX0(), addXf(), createVars(), errorHandler(), getTraj(), setup(), and solve().
_params
vector_t ETOL::eGurobi::_params protected
Path constraint configs
Definition at line 97 of file eGurobi.hpp.
Referenced by _dynConstr(), _objfunc(), _pathConstr(), and createVars().
_pnames
std::vector<std::string> ETOL::eGurobi::_pnames protected
Path constraint names
Definition at line 98 of file eGurobi.hpp.
Referenced by _dynConstr(), _objfunc(), _pathConstr(), and createVars().
_nConstr
std::atomic<size_t> ETOL::eGurobi::_nConstr protected
Number of path constraints
Definition at line 99 of file eGurobi.hpp.
Referenced by addDyn(), addX0(), addXf(), and getNConstr().
env_
GRBEnv ETOL::eGurobi::env_ private
Gurobi environment
Definition at line 136 of file eGurobi.hpp.
Referenced by eGurobi().
model_
GRBModel ETOL::eGurobi::model_ private
Gurobi model
Definition at line 137 of file eGurobi.hpp.
Referenced by eGurobi().
The documentation for this class was generated from the following files:
C:/Users/admin/git/ETOL/include/ETOL/eGurobi.hpp
C:/Users/admin/git/ETOL/src/eGurobi/eGurobi.cpp