ETOL: ETOL::ePSOPT Class Reference
ETOL::ePSOPT Class Reference
#include <ePSOPT.hpp>
Public Member Functions
ePSOPT ()
Constructor for a PSOPT interface.
virtual ~ePSOPT ()
void setup ()
Constructs an optimization problem from settings.
void solve ()
Solves the trajectory optimization problem.
void debug ()
Generates debug information.
void close ()
Closes all dynamically allocated resources.
Alg * getAlgorithm ()
Get pointer to PSOPT algorithm.
Sol * getSolution ()
Get pointer to PSOPT solution.
Prob * getProblem ()
Get pointer to the PSOPT problem.
Public Member Functions inherited from ETOL::TrajectoryOptimizer
TrajectoryOptimizer ()
Initializes a TrajectoryOptimizer object.
virtual ~TrajectoryOptimizer ()
const double getScore () const
void resetConfigs ()
Sets all configurations to default values.
void printConfigs ()
Prints configurations onto the console.
void loadConfigs (const char *filepath)
Loads configurations from an XML file.
void saveConfigs (const char *filepath)
Saves configurations to an XML file.
void addParams (std::list< param_t > params)
Adds a non-state or non-control variable to the problem.
void addExclZone (border_t *border)
Add an exclusion zone to the problem.
void addAdjTrack (track_t *track)
Add the track of an adjacent or nearby object.
void plotX (const int idx)
Plot the time history of a state variable.
void plotU (const int idx)
Plot the time history of a control variable.
state_t & getX0 ()
Get the initial state.
void setX0 (const state_t &x0)
Set an initial state.
state_t & getXf ()
Get the goal state.
void setXf (const state_t &xf)
Set the goal state.
const size_t getNControls () const
Get the number of control variables.
const size_t getNStates () const
Get the number of state variables.
state_t & getXlower ()
Get the states' lower bound.
void setXlower (const state_t &xlower)
Set the states' lower bound.
state_t & getXupper ()
Get the states' upper bound.
void setXupper (const state_t &xupper)
Set the states' upper bound.
state_var_t & getXvartype ()
Get the states' variable type.
void setXvartype (const state_var_t &xvartype)
Set the states' variable type.
const double getDt () const
Get the time step size.
void setDt (double dt)
Set the time step size.
const size_t getNSteps () const
Get the number of time steps.
void setNSteps (const size_t nSteps)
Set the number of steps.
state_t & getXtol ()
Get the states' error tolerance.
void setXtol (const state_t &xtol)
Set the states' error tolerance.
state_t & getUlower ()
Get the controls' lower bound.
void setUlower (const state_t &ulower)
Set the control's lower bound.
state_t & getUupper ()
Get the controls' upper bound.
void setUupper (const state_t &uupper)
Set the controls' upper bound.
state_var_t & getUvartype ()
Get the control variables' type.
void setUvartype (const state_var_t &uvartype)
Set the control variables' type.
const size_t getUrhorizon () const
Get the controls' reverse time horizon.
void setUrhorizon (const size_t nu4dyn)
Sets the reverse time horizon for control variables.
const size_t getXrhorizon () const
Get the states' reverse time horizon.
void setXrhorizon (const size_t nx4dyn)
Sets the reverse time horizon for state variables.
size_t getRhorizon () const
Get the maximium possible reverse time horizon.
void setNControls (const size_t nControls)
Get the number of control variables.
void setNStates (const size_t nStates)
Get the number of state variables.
void setEqConstraints (std::vector< f_t * > constraints)
Set the equality constraints.
void setLessEqConstraints (std::vector< f_t * > constraints)
Set the inequality constraints.
void setConstraints (std::vector< f_t * > constraints)
Set sense-agnostic constraint functions.
void setGradient (std::vector< f_t * > gradient)
Set the states' time derivative function.
void setObjective (f_t *objective)
Set the objective function.
traj_t * getUtraj ()
Get the pointer to the computed control trajectory.
traj_t * getXtraj ()
Get the pointer to the computed state trajectory.
const f_t * getObjective () const
Set the objective function.
std::vector< f_t * > * getGradient ()
Get the time derivative functions for the states.
std::vector< f_t * > * getEqConstraints ()
Get the equality constraint functions.
std::vector< f_t * > * getLessEqConstraints ()
Get the inequality constraint functions.
std::vector< f_t * > * getConstraints ()
Get the sense-agnostic constraint functions.
std::vector< border_t > * getObstacles_Raw ()
Get the pointer to the unprocessed exclusion zones.
std::list< region_t > * getObstacles ()
Get the pointer to the polygon partitioned exclusion zones.
std::list< track_t > * getTracks ()
Get the pointer to the moving exclusion zones.
bool isMaximized () const
Get the optimization direction.
void setMaximize (const bool maximize)
Set the optimization direction.
size_t getNExclZones ()
Get the number of exclusion zones.
size_t getNTracks ()
Get the number of moving exclusion zones.
Static Public Member Functions
static adouble endpoint_cost (adouble *initial_states, adouble *final_states, adouble *parameters, adouble &t0, adouble &tf, adouble *xad, int iphase, Workspace *workspace)
Specifies the terminal costs.
static adouble integrand_cost (adouble *states, adouble *controls, adouble *parameters, adouble &time, adouble *xad, int iphase, Workspace *workspace)
Specifies the integrand costs.
static void dae (adouble *derivatives, adouble *path, adouble *states, adouble *controls, adouble *parameters, adouble &time, adouble *xad, int iphase, Workspace *workspace)
Specifies the time derivatives of the states.
static void events (adouble *e, adouble *initial_states, adouble *final_states, adouble *parameters, adouble &t0, adouble &tf, adouble *xad, int iphase, Workspace *workspace)
Specifies the values of the event constraint functions.
static void linkages (adouble *linkages, adouble *xad, Workspace *workspace)
Specifies the values of the phase linkage constraint functions.
Static Public Member Functions inherited from ETOL::TrajectoryOptimizer
static region_t genRegion (border_t *border)
Create convex partitions.
static void calcSlopes (const region_t &region, std::vector< seg_t > *lower, std::vector< seg_t > *upper)
Computes slopes for lower and upper segments for convex partitions.
static void plot (traj_t *traj, const std::string title="Time History", const std::string tlab="t", const std::string xlab="", double tmin=DBL_MAX, double tmax=DBL_MIN, double xmin=DBL_MAX, double xmax=DBL_MIN)
Plots a trajectory.
static void plotXY (traj_t *traj, size_t xIdx=0, size_t yIdx=1, const std::string title="XY Plot", const std::string xlab="x", const std::string ylab="y", double xmin=DBL_MAX, double xmax=DBL_MIN, double ymin=DBL_MAX, double ymax=DBL_MIN)
Creates a XY-plot.
static void plotXY_wExclZones (traj_t *traj, std::list< region_t > *zones=NULL, size_t xIdx=0, size_t yIdx=1, const std::string title="XY Plot", const std::string xlab="x", const std::string ylab="y", double xmin=DBL_MAX, double xmax=DBL_MIN, double ymin=DBL_MAX, double ymax=DBL_MIN)
Creates a XY-plot wth exclusion zones.
static std::string animate2D (traj_t *traj, const int framerate=2, bool toFile=false, std::string outFile="animation.mp4", std::list< region_t > *obstacles=NULL, std::list< track_t > *tracks=NULL, size_t xIdx=0, size_t yIdx=1, const std::string title="notitle", const std::string xlab="x", const std::string ylab="y", double xmin=DBL_MAX, double xmax=DBL_MIN, double ymin=DBL_MAX, double ymax=DBL_MIN)
Creates a 2D animation with static and moving exclusion zones.
static std::string save (traj_t *traj, std::string fp="traj.csv")
Saves trajectories to a file.
Protected Attributes
Alg _algorithm
Sol _solution
Prob _problem
Protected Attributes inherited from ETOL::TrajectoryOptimizer
bool _maximize
double _score
double _dt
size_t _nSteps
size_t _nStates
size_t _nControls
state_t _x0
state_t _xlower
state_t _xupper
state_var_t _xvartype
state_t _xtol
state_t _xf
state_t _ulower
state_t _uupper
state_var_t _uvartype
size_t _xrhorizon
size_t _urhorizon
size_t _rhorizon
paramset_t _parmaeters
std::vector< border_t > _obstacles_raw
std::list< region_t > _obstacles
std::list< track_t > _tracks
std::vector< f_t * > _constraints
std::vector< f_t * > _eq
std::vector< f_t * > _lesseq
std::vector< f_t * > _gradient
f_t * _objective
traj_t _xtraj
traj_t _utraj
std::bad_any_cast * _eAny
Private Member Functions
void addBounds ()
Add the lower and upper bounds to PSOPT problem.
void getTraj ()
Additional Inherited Members
Protected Member Functions inherited from ETOL::TrajectoryOptimizer
void errorHandler ()
An error handler that is called in try-catch blocks.
void setScore (const double score)
Stores the eSovler's objective function result.
Detailed Description
Definition at line 22 of file ePSOPT.hpp.
Constructor & Destructor Documentation
ePSOPT()
ETOL::ePSOPT::ePSOPT ()
Constructor for a PSOPT interface.
Pointer to this class' object is stored in PSOPT's problem data structure
Definition at line 24 of file ePSOPT.cpp.
                : ePSOPT::TrajectoryOptimizer() {
     _problem.name = "ETOL Problem";
     _problem.outfilename = "ePSOPT.txt";
     _problem.nphases = 1;
     _problem.nlinkages = 0;
     ::psopt_level1_setup(this->_problem);
     _problem.user_data = reinterpret_cast<void*>(this);
 }
References _problem.
~ePSOPT()
virtual ETOL::ePSOPT::~ePSOPT () inline virtual
Definition at line 29 of file ePSOPT.hpp.
 {}
Member Function Documentation
setup()
void ETOL::ePSOPT::setup () virtual
Constructs an optimization problem from settings.
Sets all initial guesses to 0, except the time guess. The time guess is a equally set from 0 to dt*nstep. Configures the algorithm to use IPOPT to solve a NLP problem that is formed from enforcing constraints at Legendre nodes and with derivative computed with automatic differentiation.
Implements ETOL::TrajectoryOptimizer.
Definition at line 40 of file ePSOPT.cpp.
                    {
     this->_problem.phases(1).nstates = this->getNStates();
     this->_problem.phases(1).ncontrols = this->getNControls();
     this->_problem.phases(1).nevents = 2 * static_cast<int>(this->getNStates());
     this->_problem.phases(1).nodes = (std::string("[") +
             std::to_string(this->getNSteps()+1) + "]").c_str();
     if (this->_problem.phases(1).guess.controls.GetNoRows() < 1)
         this->_problem.phases(1).guess.controls = ::zeros(getNStates(),
                                                             getNSteps()+1);
     if (this->_problem.phases(1).guess.states.GetNoRows() < 1)
         this->_problem.phases(1).guess.states = ::zeros(getNControls(),
                                                         getNSteps()+1);
     if (this->_problem.phases(1).guess.time.GetNoRows() < 1)
         this->_problem.phases(1).guess.time = ::linspace(0.,
                 getNSteps()*getDt(), getNSteps()+1);
     _problem.phases(1).npath = static_cast<int>(this->_parmaeters.size());
     ::psopt_level2_setup(_problem, _algorithm);
     _algorithm.nlp_method           = "IPOPT";
     _algorithm.scaling              = "automatic";
     _algorithm.derivatives          = "automatic";
     _algorithm.hessian              = "exact";
     _algorithm.nlp_iter_max         = 200;
     _algorithm.nlp_tolerance        = 1.e-6;
     _algorithm.collocation_method   = "Legendre";
     _algorithm.mesh_refinement      = "automatic";
     _algorithm.mr_max_iterations    = 10;
     _algorithm.ode_tolerance        = 1.e-4;
     _algorithm.print_level          = 0;
     this->addBounds();
     _problem.integrand_cost         = &ePSOPT::integrand_cost;
     _problem.endpoint_cost          = &ePSOPT::endpoint_cost;
     _problem.dae                    = &ePSOPT::dae;
     _problem.events                 = &ePSOPT::events;
     _problem.linkages               = &ePSOPT::linkages;
 }
References _algorithm, ETOL::TrajectoryOptimizer::_parmaeters, _problem, addBounds(), dae(), endpoint_cost(), events(), ETOL::TrajectoryOptimizer::getDt(), ETOL::TrajectoryOptimizer::getNControls(), ETOL::TrajectoryOptimizer::getNStates(), ETOL::TrajectoryOptimizer::getNSteps(), integrand_cost(), and linkages().
solve()
void ETOL::ePSOPT::solve () virtual
Solves the trajectory optimization problem.
Implements ETOL::TrajectoryOptimizer.
Definition at line 83 of file ePSOPT.cpp.
                    {
     ::psopt(_solution, _problem, _algorithm);
     if (_solution.error_flag) {
         std::cout << "!!!!!Problem failed!!!!!" << std::endl
             << _solution.error_msg << std::endl;
     } else {
         this->setScore(_solution.cost);
         getTraj();
     }
     return;
 }
References _algorithm, _problem, _solution, getTraj(), and ETOL::TrajectoryOptimizer::setScore().
debug()
void ETOL::ePSOPT::debug () virtual
Generates debug information.
Enables IPOPT console messages. This feature is disabled by setup(). Therefore, call this function after setup(), but before solve()
Implements ETOL::TrajectoryOptimizer.
Definition at line 100 of file ePSOPT.cpp.
                    {
     _algorithm.print_level = 5;
 }
References _algorithm.
close()
void ETOL::ePSOPT::close () virtual
Closes all dynamically allocated resources.
Not used
Implements ETOL::TrajectoryOptimizer.
Definition at line 107 of file ePSOPT.cpp.
 {}
getAlgorithm()
Alg * ETOL::ePSOPT::getAlgorithm ()
Get pointer to PSOPT algorithm.
Returns
the pointer to the PSOPT algorithm
Definition at line 115 of file ePSOPT.cpp.
{
     return &_algorithm;
 }
References _algorithm.
Referenced by editAlgo().
getSolution()
Sol * ETOL::ePSOPT::getSolution ()
Get pointer to PSOPT solution.
Returns
the pointer to the PSOPT solution
Definition at line 119 of file ePSOPT.cpp.
{
     return &_solution;
 }
References _solution.
getProblem()
Prob * ETOL::ePSOPT::getProblem ()
Get pointer to the PSOPT problem.
Returns
the pointer to the PSOPT problem
Definition at line 111 of file ePSOPT.cpp.
{
     return &_problem;
 }
References _problem.
endpoint_cost()
adouble ETOL::ePSOPT::endpoint_cost (adouble * initial_states, adouble * final_states, adouble * parameters, adouble & t0, adouble & tf, adouble * xad, int iphase, Workspace * workspace) static
Specifies the terminal costs.
Parameters
initial_states array of initial states within a phase
final_states array of final states within a phase
parameters array of static parameters within a phase
t0 initial phase time
tf final phase time
xad vector of scaled decision variables
iphase phase index (starting from 1)Phase index (starting from 1)
workspace pointer to PSOPT's workspace structure
Returns
Always returns 0 because Lagrange form of the optimal control problem is used
Definition at line 301 of file ePSOPT.cpp.
{
     return 0.0;
 }
Referenced by setup().
integrand_cost()
adouble ETOL::ePSOPT::integrand_cost (adouble * states, adouble * controls, adouble * parameters, adouble & time, adouble * xad, int iphase, Workspace * workspace) static
Specifies the integrand costs.
Parameters
states array of instantaneous states within a phase
controls array of instantaneous controls
parameters array of static parameters within a phase
time instant of time within a phase
xad vector of scaled decision variables
iphase phase index (starting from 1)Phase index (starting from 1)
workspace pointer to PSOPT's workspace structure
Returns
Definition at line 189 of file ePSOPT.cpp.
{
     adouble f_val;
     scalar_t fout;
     ePSOPT* ptr = reinterpret_cast<ePSOPT *>(
                                                 workspace->problem->user_data);
     vector_t x, u;
     for (size_t i(0); i < ptr->getNStates(); i++)
             x.push_back(&states[i]);
     for (size_t i(0); i < ptr->getNControls(); i++)
         u.push_back(&controls[i]);
     fout = (*ptr->_objective)(x, u, {""}, {""}, time,
                                 ptr->getDt());
      try {
         f_val = std::any_cast<adouble>(fout);
     } catch(std::bad_any_cast& e) {
         ptr->_eAny = &e;
         cout << "Error in PSOPT Integrand Cost" << std::endl;
         ptr->errorHandler();
     }
     if (ptr->isMaximized())
         f_val = -1.0 * f_val;
     return f_val;
 }
References ETOL::TrajectoryOptimizer::_eAny, ETOL::TrajectoryOptimizer::_objective, ETOL::TrajectoryOptimizer::errorHandler(), ETOL::TrajectoryOptimizer::getDt(), ETOL::TrajectoryOptimizer::getNControls(), ETOL::TrajectoryOptimizer::getNStates(), and ETOL::TrajectoryOptimizer::isMaximized().
Referenced by setup().
dae()
void ETOL::ePSOPT::dae (adouble * derivatives, adouble * path, adouble * states, adouble * controls, adouble * parameters, adouble & time, adouble * xad, int iphase, Workspace * workspace) static
Specifies the time derivatives of the states.
Parameters
derivatives array of intantaneous state derivatives
path array of instantaneous path constraint values within a phase
states array of instantaneous states within a phase
controls array of instantaneous controls
parameters array of static parameters within a phase
time instant of time within a phase
xad vector of scaled decision variables
iphase phase index (starting from 1)Phase index (starting from 1)
workspace
Definition at line 220 of file ePSOPT.cpp.
{
     scalar_t f_val, p_val;
     vector_t x, u;
     ePSOPT* ptr = reinterpret_cast<ePSOPT *>(
                                                 workspace->problem->user_data);
     for (size_t i(0); i < ptr->getNStates(); i++)
         x.push_back(&states[i]);
     for (size_t i(0); i < ptr->getNControls(); i++)
         u.push_back(&controls[i]);
     for (size_t i(1); i<= ptr->getXrhorizon(); i++) {
         double delay = ptr->getDt()*i;
         for (int j(1); j <= static_cast<int>(ptr->getNStates()); j++) {
             adouble state_prev[1];
             get_delayed_state(state_prev, j, iphase, t, delay, xad, workspace);
             x.push_back(state_prev);
         }
     }
     for (size_t i(1); i<= ptr->getUrhorizon(); i++) {
         double delay = ptr->getDt()*i;
         for (int j(1); j <= static_cast<int>(ptr->getNControls()); j++) {
             adouble control_prev[1];
             get_delayed_control(control_prev, j, iphase, t, delay, xad,
                                     workspace);
             u.push_back(control_prev);
         }
     }
     try {
         adouble *tval  = &t;
         for (size_t i(0); i < ptr->getNStates(); i++) {
             f_t* f = ptr->_gradient.at(i);
             f_val = (*f)(x, u, {""}, {""}, tval, ptr->getDt());
             adouble out;
             out = std::any_cast<adouble>(f_val);
             derivatives[i] = out;
         }
         size_t j(0);
         for (size_t i(0); i < ptr->_constraints.size(); i++) {
             f_t* p = ptr->_constraints.at(i);
             p_val = (*p)(x, u, {""}, {""}, tval, ptr->getDt());
             fout_psopt_t out = std::any_cast<fout_psopt_t>(p_val);
             for (adouble val : out)
                 path[j++] = val;
         }
     } catch(std::bad_any_cast& e) {
         ptr->_eAny = &e;
         cout << "Error in PSOPT DAE" << std::endl;
         ptr->errorHandler();
     }
 }
References ETOL::TrajectoryOptimizer::_constraints, ETOL::TrajectoryOptimizer::_eAny, ETOL::TrajectoryOptimizer::_gradient, ETOL::TrajectoryOptimizer::errorHandler(), ETOL::TrajectoryOptimizer::getDt(), ETOL::TrajectoryOptimizer::getNControls(), ETOL::TrajectoryOptimizer::getNStates(), ETOL::TrajectoryOptimizer::getUrhorizon(), and ETOL::TrajectoryOptimizer::getXrhorizon().
Referenced by setup().
events()
void ETOL::ePSOPT::events (adouble * e, adouble * initial_states, adouble * final_states, adouble * parameters, adouble & t0, adouble & tf, adouble * xad, int iphase, Workspace * workspace) static
Specifies the values of the event constraint functions.
Parameters
e array of event constraints
initial_states array of initial states within a phase
final_states Array of final states within a phase
parameters array of static parameters within a phase
t0 initial phase time
tf final phase time
xad vector of scaled decision variables
iphase phase index (starting from 1)Phase index (starting from 1)
workspace pointer to PSOPT's workspace structure
Sets the initial state and final state constraints
Definition at line 280 of file ePSOPT.cpp.
{
     size_t i(0), j(0);
     ePSOPT* ptr = reinterpret_cast<ePSOPT *>(
                                                 workspace->problem->user_data);
     for (; i < ptr->getNStates(); i++)
         e[ i ] = initial_states[i];
     for (; i < 2 * ptr->getNStates(); i++)
         e[ i ] = final_states[j++];
 }
References ETOL::TrajectoryOptimizer::getNStates().
Referenced by setup().
linkages()
void ETOL::ePSOPT::linkages (adouble * linkages, adouble * xad, Workspace * workspace) static
Specifies the values of the phase linkage constraint functions.
Parameters
linkages array of linkage constraints
xad vector of scaled decision variables
workspace pointer to PSOPT's workspace structure
Does nothing because this PSOPT interface creates a single phase problem
Definition at line 295 of file ePSOPT.cpp.
                               {}
Referenced by setup().
addBounds()
void ETOL::ePSOPT::addBounds () private
Add the lower and upper bounds to PSOPT problem.
Definition at line 125 of file ePSOPT.cpp.
{
     paramset_t::iterator param = this->_parmaeters.begin();
     state_t::iterator xlow(getXlower().begin()), xup(getXupper().begin()),
             ulow(getUlower().begin()), uup(getUupper().begin()),
             x0(getX0().begin()), xf(getXf().begin()), xtol(getXtol().begin());
     int offset = static_cast<int>(this->getNStates()) +1;
     for (size_t i= 0; i < this->getNStates(); i++) {
         int ii = static_cast<int>(i);
         _problem.phases(1).bounds.lower.states(ii+1) = *(xlow++);
         _problem.phases(1).bounds.upper.states(ii+1) = *(xup++);
         _problem.phases(1).bounds.lower.events(ii+1) = *x0 - *xtol;
         _problem.phases(1).bounds.upper.events(ii+1) = *(x0++) + *xtol;
         _problem.phases(1).bounds.lower.events(ii+offset) = *xf - *xtol;
         _problem.phases(1).bounds.upper.events(ii+offset)=*(xf++)+*(xtol++);
     }
     for (size_t i= 0; i < this->getNControls(); i++) {
         int ii = static_cast<int>(i);
         _problem.phases(1).bounds.lower.controls(ii+1) = *(ulow++);
         _problem.phases(1).bounds.upper.controls(ii+1) =  *(uup++);
     }
     for (size_t i= 0; i < this->_parmaeters.size(); i++) {
         int ii = static_cast<int>(i);
         _problem.phases(1).bounds.lower.path(ii+1) = param->second.lbnd;
         _problem.phases(1).bounds.upper.path(ii+1) = (param++)->second.ubnd;
     }
     _problem.phases(1).bounds.lower.StartTime = 0.;
     _problem.phases(1).bounds.upper.StartTime = 0.;
     _problem.phases(1).bounds.lower.EndTime = getNSteps() * getDt();
     _problem.phases(1).bounds.upper.EndTime = getNSteps() * getDt();
 }
References ETOL::TrajectoryOptimizer::_parmaeters, _problem, ETOL::TrajectoryOptimizer::getDt(), ETOL::TrajectoryOptimizer::getNControls(), ETOL::TrajectoryOptimizer::getNStates(), ETOL::TrajectoryOptimizer::getNSteps(), ETOL::TrajectoryOptimizer::getUlower(), ETOL::TrajectoryOptimizer::getUupper(), ETOL::TrajectoryOptimizer::getX0(), ETOL::TrajectoryOptimizer::getXf(), ETOL::TrajectoryOptimizer::getXlower(), ETOL::TrajectoryOptimizer::getXtol(), and ETOL::TrajectoryOptimizer::getXupper().
Referenced by setup().
getTraj()
void ETOL::ePSOPT::getTraj () private
Get the trajectory results from the PSOPT solution
Definition at line 160 of file ePSOPT.cpp.
                      {
     DMatrix xmat         = _solution.get_states_in_phase(1);
     DMatrix umat         = _solution.get_controls_in_phase(1);
     DMatrix tmat         = _solution.get_time_in_phase(1);
     traj_t* xtraj = this->getXtraj();
     xtraj->clear();
     traj_t* utraj = this->getUtraj();
     utraj->clear();
     for (int32_t j(1); j <= tmat.GetNoCols(); j++) {
         double t;
         state_t x, u;
         t = tmat.element(1, j);
         for (int32_t i(1); i <= xmat.GetNoRows(); i++)
             x.push_back(xmat.elem(i, j));
         xtraj->push_back(traj_elem_t(t, x));
         for (int32_t i(1); i <= umat.GetNoRows(); i++)
             u.push_back(umat.elem(i, j));
         utraj->push_back(traj_elem_t(t, u));
     }
 }
References _solution, ETOL::TrajectoryOptimizer::getUtraj(), and ETOL::TrajectoryOptimizer::getXtraj().
Referenced by solve().
Member Data Documentation
_algorithm
Alg ETOL::ePSOPT::_algorithm protected
PSOPT algorithm
Definition at line 148 of file ePSOPT.hpp.
Referenced by debug(), getAlgorithm(), setup(), and solve().
_solution
Sol ETOL::ePSOPT::_solution protected
PSOPT solution
Definition at line 149 of file ePSOPT.hpp.
Referenced by getSolution(), getTraj(), and solve().
_problem
Prob ETOL::ePSOPT::_problem protected
PSOPT problem
Definition at line 150 of file ePSOPT.hpp.
Referenced by addBounds(), ePSOPT(), getProblem(), setup(), and solve().
The documentation for this class was generated from the following files:
C:/Users/admin/git/ETOL/include/ETOL/ePSOPT.hpp
C:/Users/admin/git/ETOL/src/ePSOPT/ePSOPT.cpp