ETOL: ETOL::TrajectoryOptimizer Class Reference
ETOL::TrajectoryOptimizer Class Reference abstract
An abstract class for defining a trajectory optimization problem.
#include <TrajectoryOptimizer.hpp>
Public Member Functions
TrajectoryOptimizer ()
Initializes a TrajectoryOptimizer object.
virtual ~TrajectoryOptimizer ()
virtual void setup ()=0
Constructs a trajectory optimization problem.
virtual void solve ()=0
Solves a trajectory optimization problem.
virtual void debug ()=0
Generates debug information.
virtual void close ()=0
Releases all dynamically allocated resources.
const double getScore () const
void resetConfigs ()
Sets all configurations to default values.
void printConfigs ()
Prints configurations onto the console.
void loadConfigs (const char *filepath)
Loads configurations from an XML file.
void saveConfigs (const char *filepath)
Saves configurations to an XML file.
void addParams (std::list< param_t > params)
Adds a non-state or non-control variable to the problem.
void addExclZone (border_t *border)
Add an exclusion zone to the problem.
void addAdjTrack (track_t *track)
Add the track of an adjacent or nearby object.
void plotX (const int idx)
Plot the time history of a state variable.
void plotU (const int idx)
Plot the time history of a control variable.
state_t & getX0 ()
Get the initial state.
void setX0 (const state_t &x0)
Set an initial state.
state_t & getXf ()
Get the goal state.
void setXf (const state_t &xf)
Set the goal state.
const size_t getNControls () const
Get the number of control variables.
const size_t getNStates () const
Get the number of state variables.
state_t & getXlower ()
Get the states' lower bound.
void setXlower (const state_t &xlower)
Set the states' lower bound.
state_t & getXupper ()
Get the states' upper bound.
void setXupper (const state_t &xupper)
Set the states' upper bound.
state_var_t & getXvartype ()
Get the states' variable type.
void setXvartype (const state_var_t &xvartype)
Set the states' variable type.
const double getDt () const
Get the time step size.
void setDt (double dt)
Set the time step size.
const size_t getNSteps () const
Get the number of time steps.
void setNSteps (const size_t nSteps)
Set the number of steps.
state_t & getXtol ()
Get the states' error tolerance.
void setXtol (const state_t &xtol)
Set the states' error tolerance.
state_t & getUlower ()
Get the controls' lower bound.
void setUlower (const state_t &ulower)
Set the control's lower bound.
state_t & getUupper ()
Get the controls' upper bound.
void setUupper (const state_t &uupper)
Set the controls' upper bound.
state_var_t & getUvartype ()
Get the control variables' type.
void setUvartype (const state_var_t &uvartype)
Set the control variables' type.
const size_t getUrhorizon () const
Get the controls' reverse time horizon.
void setUrhorizon (const size_t nu4dyn)
Sets the reverse time horizon for control variables.
const size_t getXrhorizon () const
Get the states' reverse time horizon.
void setXrhorizon (const size_t nx4dyn)
Sets the reverse time horizon for state variables.
size_t getRhorizon () const
Get the maximium possible reverse time horizon.
void setNControls (const size_t nControls)
Get the number of control variables.
void setNStates (const size_t nStates)
Get the number of state variables.
void setEqConstraints (std::vector< f_t * > constraints)
Set the equality constraints.
void setLessEqConstraints (std::vector< f_t * > constraints)
Set the inequality constraints.
void setConstraints (std::vector< f_t * > constraints)
Set sense-agnostic constraint functions.
void setGradient (std::vector< f_t * > gradient)
Set the states' time derivative function.
void setObjective (f_t *objective)
Set the objective function.
traj_t * getUtraj ()
Get the pointer to the computed control trajectory.
traj_t * getXtraj ()
Get the pointer to the computed state trajectory.
const f_t * getObjective () const
Set the objective function.
std::vector< f_t * > * getGradient ()
Get the time derivative functions for the states.
std::vector< f_t * > * getEqConstraints ()
Get the equality constraint functions.
std::vector< f_t * > * getLessEqConstraints ()
Get the inequality constraint functions.
std::vector< f_t * > * getConstraints ()
Get the sense-agnostic constraint functions.
std::vector< border_t > * getObstacles_Raw ()
Get the pointer to the unprocessed exclusion zones.
std::list< region_t > * getObstacles ()
Get the pointer to the polygon partitioned exclusion zones.
std::list< track_t > * getTracks ()
Get the pointer to the moving exclusion zones.
bool isMaximized () const
Get the optimization direction.
void setMaximize (const bool maximize)
Set the optimization direction.
size_t getNExclZones ()
Get the number of exclusion zones.
size_t getNTracks ()
Get the number of moving exclusion zones.
Static Public Member Functions
static region_t genRegion (border_t *border)
Create convex partitions.
static void calcSlopes (const region_t &region, std::vector< seg_t > *lower, std::vector< seg_t > *upper)
Computes slopes for lower and upper segments for convex partitions.
static void plot (traj_t *traj, const std::string title="Time History", const std::string tlab="t", const std::string xlab="", double tmin=DBL_MAX, double tmax=DBL_MIN, double xmin=DBL_MAX, double xmax=DBL_MIN)
Plots a trajectory.
static void plotXY (traj_t *traj, size_t xIdx=0, size_t yIdx=1, const std::string title="XY Plot", const std::string xlab="x", const std::string ylab="y", double xmin=DBL_MAX, double xmax=DBL_MIN, double ymin=DBL_MAX, double ymax=DBL_MIN)
Creates a XY-plot.
static void plotXY_wExclZones (traj_t *traj, std::list< region_t > *zones=NULL, size_t xIdx=0, size_t yIdx=1, const std::string title="XY Plot", const std::string xlab="x", const std::string ylab="y", double xmin=DBL_MAX, double xmax=DBL_MIN, double ymin=DBL_MAX, double ymax=DBL_MIN)
Creates a XY-plot wth exclusion zones.
static std::string animate2D (traj_t *traj, const int framerate=2, bool toFile=false, std::string outFile="animation.mp4", std::list< region_t > *obstacles=NULL, std::list< track_t > *tracks=NULL, size_t xIdx=0, size_t yIdx=1, const std::string title="notitle", const std::string xlab="x", const std::string ylab="y", double xmin=DBL_MAX, double xmax=DBL_MIN, double ymin=DBL_MAX, double ymax=DBL_MIN)
Creates a 2D animation with static and moving exclusion zones.
static std::string save (traj_t *traj, std::string fp="traj.csv")
Saves trajectories to a file.
Protected Member Functions
void errorHandler ()
An error handler that is called in try-catch blocks.
void setScore (const double score)
Stores the eSovler's objective function result.
Protected Attributes
bool _maximize
double _score
double _dt
size_t _nSteps
size_t _nStates
size_t _nControls
state_t _x0
state_t _xlower
state_t _xupper
state_var_t _xvartype
state_t _xtol
state_t _xf
state_t _ulower
state_t _uupper
state_var_t _uvartype
size_t _xrhorizon
size_t _urhorizon
size_t _rhorizon
paramset_t _parmaeters
std::vector< border_t > _obstacles_raw
std::list< region_t > _obstacles
std::list< track_t > _tracks
std::vector< f_t * > _constraints
std::vector< f_t * > _eq
std::vector< f_t * > _lesseq
std::vector< f_t * > _gradient
f_t * _objective
traj_t _xtraj
traj_t _utraj
std::bad_any_cast * _eAny
Detailed Description
An abstract class for defining a trajectory optimization problem.
Provides a common API and utility functions for trajectory optimization
Definition at line 27 of file TrajectoryOptimizer.hpp.
Constructor & Destructor Documentation
TrajectoryOptimizer()
ETOL::TrajectoryOptimizer::TrajectoryOptimizer ()
Initializes a TrajectoryOptimizer object.
Definition at line 49 of file TrajectoryOptimizer.cpp.
{
     this->_score = 0.;
     this->_nControls = 0;
     this->_nStates = 0;
     this->_dt = 0.0;
     this->_nSteps = 0;
     this->_xrhorizon = 0;
     this->_urhorizon = 0;
     this->_rhorizon = 0;
     this->_x0 = {};
     this->_xf = {};
     this->_xtol = {};
     this->_xlower = {};
     this->_xupper = {};
     this->_xvartype = {};
     this->_ulower = {};
     this->_uupper = {};
     this->_uvartype = {};
     this->_xtraj = traj_t();
     this->_utraj = traj_t();
     this->_maximize = false;
     this->_objective = NULL;
     this->_obstacles_raw = {};
     this->_obstacles = {};
     this->_tracks = {};
     this->_eAny = NULL;
 }
References _dt, _eAny, _maximize, _nControls, _nStates, _nSteps, _objective, _obstacles, _obstacles_raw, _rhorizon, _score, _tracks, _ulower, _urhorizon, _utraj, _uupper, _uvartype, _x0, _xf, _xlower, _xrhorizon, _xtol, _xtraj, _xupper, and _xvartype.
~TrajectoryOptimizer()
virtual ETOL::TrajectoryOptimizer::~TrajectoryOptimizer () inline virtual
Definition at line 34 of file TrajectoryOptimizer.hpp.
 {}
Member Function Documentation
setup()
virtual void ETOL::TrajectoryOptimizer::setup () pure virtual
Constructs a trajectory optimization problem.
Implemented in ETOL::eOMPL, ETOL::eDymos, ETOL::eGLPK, ETOL::eGurobi, and ETOL::ePSOPT.
Referenced by main().
solve()
virtual void ETOL::TrajectoryOptimizer::solve () pure virtual
Solves a trajectory optimization problem.
Implemented in ETOL::eOMPL, ETOL::eDymos, ETOL::eGLPK, ETOL::eGurobi, and ETOL::ePSOPT.
Referenced by main().
debug()
virtual void ETOL::TrajectoryOptimizer::debug () pure virtual
Generates debug information.
Implemented in ETOL::eOMPL, ETOL::eDymos, ETOL::eGLPK, ETOL::eGurobi, and ETOL::ePSOPT.
Referenced by main().
close()
virtual void ETOL::TrajectoryOptimizer::close () pure virtual
Releases all dynamically allocated resources.
Implemented in ETOL::eOMPL, ETOL::eDymos, ETOL::eGLPK, ETOL::eGurobi, and ETOL::ePSOPT.
Referenced by main().
getScore()
const double ETOL::TrajectoryOptimizer::getScore () const
Definition at line 1636 of file TrajectoryOptimizer.cpp.
{
     return _score;
 }
References _score.
Referenced by main().
resetConfigs()
void ETOL::TrajectoryOptimizer::resetConfigs ()
Sets all configurations to default values.
Definition at line 657 of file TrajectoryOptimizer.cpp.
{
     this->setNStates(0);
     this->setNControls(0);
     this->setDt(0);
     this->setXrhorizon(0);
     this->_xvartype.clear();
     this->_x0.clear();
     this->_xf.clear();
     this->_xtol.clear();
     this->setUrhorizon(0);
     this->_uvartype.clear();
     this->_ulower.clear();
     this->_uupper.clear();
     this->_obstacles_raw.clear();
     this->_obstacles.clear();
     this->_tracks.clear();
 }
References _obstacles, _obstacles_raw, _tracks, _ulower, _uupper, _uvartype, _x0, _xf, _xtol, _xvartype, setDt(), setNControls(), setNStates(), setUrhorizon(), and setXrhorizon().
Referenced by loadConfigs().
printConfigs()
void ETOL::TrajectoryOptimizer::printConfigs ()
Prints configurations onto the console.
Definition at line 678 of file TrajectoryOptimizer.cpp.
{
     using std::cout;
     using std::endl;
     cout << endl << "ETOL Information" << endl;
     cout << "# Steps:\t" << this->getNSteps() <<endl;
     cout << "dt:\t\t" << this->getDt() <<endl;
     cout << "# States:\t" << this->getNStates() <<endl;
     cout << "# Controls:\t" << this->getNControls() <<endl;
     cout << "Xrhorizon:\t" << this->getXrhorizon() <<endl;
     cout << "Urhorizon:\t" << this->getUrhorizon() <<endl;
     cout << "#Obstacles:\t" << this->getNExclZones() <<endl;
     cout << "#Tracks:\t" << this->getNTracks() <<endl;
     cout << endl;
     size_t i(0);
     cout <<"\t\tvartype\tlower\tupper\tinitial\tfinal\ttol"    <<endl;
     for (auto vartype : this->_xvartype) {
         char vtype;
         switch (vartype) {
         case var_t::CONTINUOUS:
             vtype = 'C';
             break;
         case var_t::BINARY:
             vtype = 'B';
             break;
         case var_t::INTERGER:
             vtype = 'I';
             break;
         default:
             break;
         }
         cout << "XInfo:\t\t" << vtype << "\t" << this->_xlower.at(i) << "\t" <<
                 this->_xupper.at(i) << "\t" << this->_x0.at(i) << "\t"
                 << this->_xf.at(i) << "\t" << this->_xtol.at(i) << endl;
         i++;
     }
     i = 0;
     for (auto vartype : this->_uvartype) {
         char vtype;
         switch (vartype) {
         case var_t::CONTINUOUS:
             vtype = 'C';
             break;
         case var_t::BINARY:
             vtype = 'B';
             break;
         case var_t::INTERGER:
             vtype = 'I';
             break;
         default:
             break;
         }
         cout <<"UInfo:\t\t" << vtype <<"\t" << this->_ulower.at(i)
                 << "\t"    << this->_uupper.at(i) << endl;
         i++;
     }
     cout << endl;
     cout << "\t\tExclusion Zone Corners..." <<endl;
     for (auto obs : *this->getObstacles()) {
         for (auto bd : obs) {
             cout << "Bottom\t\t";
             for (auto corner : bd.lower)
                 cout << "(" << corner.at(0) << "," << corner.at(1)  << ","
                         <<corner.at(2) << ")  ";
             cout << endl;
             cout << "Top\t\t";
             for (auto corner : bd.upper)
                 cout << "(" << corner.at(0) << "," << corner.at(1)  << ","
                                         <<corner.at(2) << ")  ";
             cout << endl;
         }
         cout << endl;
     }
     for (auto track : *this->getTracks()) {
         cout << "\t\tradius\t#points"<< endl;
         cout << "TrackInfo\t" << track.radius <<
                 "\t" << track.trajectory.size() <<endl << endl;
         cout << "\t\ttime\tElements..." << endl;
         for (auto elem : track.trajectory) {
             cout << "Waypoint\t" <<elem.first << "\t";
             for (auto datum : elem.second)
                 cout << datum  << "\t";
             cout << endl;
         }
         cout << endl;
     }
 }
References _ulower, _uupper, _uvartype, _x0, _xf, _xlower, _xtol, _xupper, _xvartype, ETOL::BINARY, ETOL::CONTINUOUS, getDt(), getNControls(), getNExclZones(), getNStates(), getNSteps(), getNTracks(), getObstacles(), getTracks(), getUrhorizon(), getXrhorizon(), and ETOL::INTERGER.
Referenced by main().
loadConfigs()
void ETOL::TrajectoryOptimizer::loadConfigs (const char * filepath)
Loads configurations from an XML file.
Parameters
filepath an absolute or relative path to an XML file
Definition at line 766 of file TrajectoryOptimizer.cpp.
{
     using std::string;
     resetConfigs();
     LIBXML_TEST_VERSION
     xmlDoc *doc = xmlutils::getdoc(string(filepath));
     xmlChar* rootPath = reinterpret_cast<xmlChar*>(
                             const_cast<char*>("//etol"));
     xmlXPathObjectPtr root = xmlutils::getnodeset(doc, rootPath);
     {
         xmlAttrPtr attr = root->nodesetval->nodeTab[0]->properties;
         while (attr) {
             string  nname = string((const char*)attr->name);
             xmlChar* val = xmlNodeListGetString(
                                 attr->doc, attr->children, 1);
             if (nname == "nsteps")
                 this->setNSteps((size_t) xmlXPathCastStringToNumber(val));
             else if (nname == "dt")
                 this->setDt(xmlXPathCastStringToNumber(val));
             attr = attr->next;
             xmlFree(val);
         }
         xmlFree(attr);
     }
     assert(this->getNSteps() != 0);
     assert(this->getDt() != 0);
     xmlNodePtr nodes = root->nodesetval->nodeTab[0]->children;
     while (nodes) {
         string nname = string((const char*)nodes->name);
         size_t nstates = 0;
         // State Data
         if (nname == "states") {
             {
                 xmlAttrPtr attr = nodes->properties;
                 while (attr) {
                     string nname = string((const char*)attr->name);
                     xmlChar* val = xmlNodeListGetString(
                                     attr->doc, attr->children, 1);
                     if (nname == "nstates")
                         nstates =    (size_t) xmlXPathCastStringToNumber(val);
                     else if (nname == "rhorizon")
                         setXrhorizon(std::max(getXrhorizon(), (size_t)
                                 xmlXPathCastStringToNumber(val)));
                     attr = attr->next;
                     xmlFree(val);
                 }
                 xmlFree(attr);
             }
             xmlNodePtr state = nodes->children;
             while (state) {
                 if (nstates > this->getNStates()) {
                     xmlAttrPtr attr = state->properties;
                     while (attr) {
                         string nname = string((const char*)attr->name);
                         xmlChar* val = xmlNodeListGetString(
                                 attr->doc, attr->children, 1);
                         if (nname == "vartype") {
                             this->setNStates(this->getNStates() + 1);
                             switch (*reinterpret_cast<char*>(val)) {
                             case 'C':
                                 this->_xvartype.push_back(var_t::CONTINUOUS);
                                 break;
                             case 'B':
                                 this->_xvartype.push_back(var_t::BINARY);
                                 break;
                             case 'I':
                                 this->_xvartype.push_back(var_t::INTERGER);
                                 break;
                             default:
                                 std::cout << "Invalid xVartype" << std::endl;
                                 exit(EXIT_FAILURE);
                             }
                         } else if (nname == "lower") {
                             _xlower.push_back(xmlXPathCastStringToNumber(val));
                         } else if (string((const char*)attr->name) == "upper") {
                             _xupper.push_back(xmlXPathCastStringToNumber(val));
                         } else if (string((const char*)attr->name)
                                                                 == "initial") {
                             _x0.push_back(xmlXPathCastStringToNumber(val));
                         } else if (string((const char*)attr->name)
                                                                 == "terminal") {
                             _xf.push_back(xmlXPathCastStringToNumber(val));
                         } else if (string((const char*)attr->name)
                                                             == "tolerance") {
                             _xtol.push_back(xmlXPathCastStringToNumber(val));
                         }
                         attr = attr->next;
                         xmlFree(val);
                     }
                     xmlFree(attr);
                 }
                 state = state->next;
             }
             xmlFree(state);
         } else if (nname == "controls") {
             size_t ncontrols = 0;
             {
                 xmlAttrPtr attr = nodes->properties;
                 while (attr) {
                     string nname = string((const char*)attr->name);
                     xmlChar* val = xmlNodeListGetString(
                             attr->doc, attr->children, 1);
                     if (nname == "ncontrols")
                         ncontrols = (size_t) xmlXPathCastStringToNumber(val);
                     else if (nname == "rhorizon")
                         setUrhorizon(std::max(getUrhorizon(), (size_t)
                                 xmlXPathCastStringToNumber(val)));
                     attr = attr->next;
                     xmlFree(val);
                 }
                 xmlFree(attr);
             }
             xmlNodePtr control =  nodes->children;
             while (control) {
                 if (ncontrols > this->getNControls()) {
                     xmlAttrPtr attr = control->properties;
                     while (attr) {
                         string nname = string((const char*)attr->name);
                         xmlChar* val = xmlNodeListGetString(
                                 attr->doc, attr->children, 1);
                         if (nname == "vartype") {
                             this->setNControls(this->getNControls() + 1);
                             switch (*reinterpret_cast<char*>(val)) {
                             case 'C':
                                 this->_uvartype.push_back(var_t::CONTINUOUS);
                                 break;
                             case 'B':
                                 this->_uvartype.push_back(var_t::BINARY);
                                 break;
                             case 'I':
                                 this->_uvartype.push_back(var_t::INTERGER);
                                 break;
                             default:
                                 std::cout << "Invalid uVartype" << std::endl;
                                 exit(EXIT_FAILURE);
                             }
                         } else if (string((const char*)attr->name) == "lower") {
                             _ulower.push_back(xmlXPathCastStringToNumber(val));
                         } else if (string((const char*)attr->name) == "upper") {
                             _uupper.push_back(xmlXPathCastStringToNumber(val));
                         }
                         attr = attr->next;
                         xmlFree(val);
                     }
                     xmlFree(attr);
                 }
                 control = control->next;
             }
             xmlFree(control);
         } else if (nname == "exzones") {
             size_t nexzones(SIZE_MAX);
             {
                 xmlAttrPtr attr = nodes->properties;
                 while (attr) {
                     string nname = string((const char*)attr->name);
                     xmlChar* val = xmlNodeListGetString(
                             attr->doc, attr->children, 1);
                     if (nname == "nzones")
                         nexzones = (size_t) xmlXPathCastStringToNumber(val);
                     attr = attr->next;
                     xmlFree(val);
                 }
                 xmlFree(attr);
             }
             size_t i(0);
             xmlNodePtr border =  nodes->children;
             while (border) {
                 size_t ncorners(SIZE_MAX);
                 {
                     xmlAttrPtr attr = border->properties;
                     while (attr) {
                         string nname = string((const char*)attr->name);
                         xmlChar* val = xmlNodeListGetString(
                                 attr->doc, attr->children, 1);
                         if (nname == "ncorners")
                             ncorners = (size_t) xmlXPathCastStringToNumber(val);
                         attr = attr->next;
                         xmlFree(val);
                     }
                     xmlFree(attr);
                 }
                 border_t border_val = border_t();
                 xmlNodePtr corner = border->children;
                 while (corner) {
                     xmlAttrPtr attr = corner->properties;
                     double x(DBL_MIN), y(DBL_MIN), z(DBL_MIN);
                     while (attr) {
                         string nname = string((const char*)attr->name);
                         xmlChar* val = xmlNodeListGetString(
                                         attr->doc, attr->children, 1);
                         if (nname == "x")
                             x = xmlXPathCastStringToNumber(val);
                         else if (nname == "y")
                             y = xmlXPathCastStringToNumber(val);
                         else if (nname == "z")
                             z = xmlXPathCastStringToNumber(val);
                         attr = attr->next;
                         xmlFree(val);
                     }
                     if (x != DBL_MIN && y != DBL_MIN && z != DBL_MIN &&
                             !(border_val.size() > ncorners)) {
                         xmlFree(attr);
                         corner_t corner_val {x, y, z};
                         border_val.push_back(corner_val);
                     }
                     corner = corner->next;
                 }
                 xmlFree(corner);
                 if (!border_val.empty() && (nexzones > i)) {
                     this->addExclZone(&border_val);
                     i++;
                 }
                 border = border->next;
             }
             xmlFree(border);
         } else if (nname == "mexzones") {
             double nmexzones = 0;
             {
                 xmlAttrPtr attr = nodes->properties;
                 while (attr) {
                     string nname = string((const char*)attr->name);
                     xmlChar* val = xmlNodeListGetString(
                                     attr->doc, attr->children, 1);
                     if (nname == "nzones")
                         nmexzones = (size_t) xmlXPathCastStringToNumber(val);
                     attr = attr->next;
                     xmlFree(val);
                 }
                 xmlFree(attr);
             }
             size_t i = 0;
             xmlNodePtr mexzone = nodes->children;
             while (mexzone) {
                 size_t nway = 0;
                 track_t track = track_t();
                 {
                     xmlAttrPtr attr = mexzone->properties;
                     while (attr) {
                         string nname = string((const char*)attr->name);
                         xmlChar* val = xmlNodeListGetString(
                                 attr->doc, attr->children, 1);
                         if (nname == "radius")
                             track.radius = xmlXPathCastStringToNumber(val);
                         else if (nname == "nwaypoints")
                             nway = (size_t) xmlXPathCastStringToNumber(val);
                         attr = attr->next;
                         xmlFree(val);
                     }
                     xmlFree(attr);
                 }
                 size_t j(0);
                 traj_t traj;
                 xmlNodePtr waypoint = mexzone->children;
                 while (waypoint) {
                     size_t ndatums = 0;
                     traj_elem_t traj_elem;
                     double t = 0.;
                     {
                         xmlAttrPtr attr = waypoint->properties;
                         while (attr) {
                             string nname = string((const char*) attr->name);
                             xmlChar* val = xmlNodeListGetString(
                                             attr->doc, attr->children, 1);
                             if (nname == "t")
                                 traj_elem.first =
                                         xmlXPathCastStringToNumber(val);
                             else if (nname == "ndatums")
                                 ndatums = (size_t)
                                             xmlXPathCastStringToNumber(val);
                             attr = attr->next;
                             xmlFree(val);
                         }
                         xmlFree(attr);
                     }
                     state_t state;
                     xmlNodePtr datum = waypoint->children;
                     while (datum) {
                         string nname = string((const char*) datum->name);
                         xmlChar* val = xmlNodeListGetString(
                                         datum->doc, datum->children, 1);
                         if (nname == "datum" &&
                                 !(ndatums !=0 && state.size() >= ndatums))
                             state.push_back(
                                     xmlXPathCastStringToNumber(val));
                         xmlFree(val);
                         datum = datum->next;
                     }
                     xmlFree(datum);
                     if (!state.empty() && (nway > traj.size())) {
                         traj_elem.second = state;
                         traj.push_back(traj_elem);
                     }
                     waypoint = waypoint->next;
                 }
                 xmlFree(waypoint);
                 if (!traj.empty() && (nmexzones > this->getTracks()->size())) {
                     track.trajectory = traj;
                     this->addAdjTrack(&track);
                 }
                 mexzone = mexzone->next;
             }
             xmlFree(mexzone);
         }
         nodes = nodes->next;
     }
     xmlFree(nodes);
     xmlXPathFreeObject(root);
     xmlFreeDoc(doc);
     xmlCleanupParser();
     xmlMemoryDump();
 }
References _ulower, _uupper, _uvartype, _x0, _xf, _xlower, _xtol, _xupper, _xvartype, addAdjTrack(), addExclZone(), ETOL::BINARY, ETOL::CONTINUOUS, xmlutils::getdoc(), getDt(), getNControls(), xmlutils::getnodeset(), getNStates(), getNSteps(), getUrhorizon(), getXrhorizon(), ETOL::INTERGER, ETOL::track_t::radius, resetConfigs(), setDt(), setNControls(), setNStates(), setNSteps(), setUrhorizon(), setXrhorizon(), and ETOL::track_t::trajectory.
Referenced by main().
saveConfigs()
void ETOL::TrajectoryOptimizer::saveConfigs (const char * filepath)
Saves configurations to an XML file.
Parameters
filepath an absolute or relative path to an XML file
Definition at line 1100 of file TrajectoryOptimizer.cpp.
{
     /*
      * this initialize the library and check potential ABI mismatches
      * between the version it was compiled for and the actual shared
      * library used.
      */
     using std::to_string;
     LIBXML_TEST_VERSION
     int rc;
     xmlTextWriterPtr writer;
     xmlChar *tmp;
     size_t i, j, nzones;
     char str[MAXLENGTH];
     /* Create a new XmlWriter for uri, with no compression. */
     writer = xmlNewTextWriterFilename(filepath, 0);
     if (writer == NULL) {
         printf("testXmlwriterFilename: Error creating the xml writer\n");
         return;
     }
     rc = xmlTextWriterSetIndent(writer, 1);
     if (rc < 0) {
         printf("saveConfigs: Error at xmlTextWriterSetIndent\n");
         return;
     }
     memset(str, '\0', 10*sizeof(char));
     snprintf(str, sizeof(str), "\t");
     rc = xmlTextWriterSetIndentString(writer, BAD_CAST str);
     if (rc < 0) {
         printf("saveConfigs: Error at xmlTextWriterSetIndent\n");
         return;
     }
     // Start the document with the xml default for the version,
     // encoding and the default for the standalone declaration.
     rc = xmlTextWriterStartDocument(writer, NULL, MY_ENCODING, NULL);
     if (rc < 0) {
         printf("saveConfigs: Error at xmlTextWriterStartDocument\n");
         return;
     }
     // Make ETOL the root node of the tree
     rc = xmlTextWriterStartElement(writer, BAD_CAST "etol");
     if (rc < 0) {
         printf("saveConfigs: Error at xmlTextWriterStartElement\n");
         return;
     }
     memset(str, '\0', 10*sizeof(char));
     snprintf(str, sizeof(str), "%zu", this->getNSteps());
     rc = xmlTextWriterWriteAttribute(writer, BAD_CAST "nsteps", BAD_CAST str);
     if (rc < 0) {
         printf("saveConfigs: Error at xmlTextWriterWriteAttribute\n");
         return;
     }
     memset(str, '\0', 10*sizeof(char));
     snprintf(str, sizeof(str), "%.02f", this->getDt());
     rc = xmlTextWriterWriteAttribute(writer, BAD_CAST "dt", BAD_CAST str);
     if (rc < 0) {
         printf("saveConfigs: Error at xmlTextWriterWriteAttribute\n");
         return;
     }
     // Start an element named "states" as child of ETOL.
     rc = xmlTextWriterStartElement(writer, BAD_CAST "states");
     if (rc < 0) {
         printf("saveConfigs: Error at xmlTextWriterStartElement\n");
         return;
     }
     memset(str, '\0', 10*sizeof(char));
     snprintf(str, sizeof(str), "%zu", this->getNStates());
     rc = xmlTextWriterWriteAttribute(writer, BAD_CAST "nstates", BAD_CAST str);
     if (rc < 0) {
         printf("saveConfigs: Error at xmlTextWriterWriteAttribute\n");
         return;
     }
     memset(str, '\0', 10*sizeof(char));
     snprintf(str, sizeof(str), "%zu", this->getXrhorizon());
     rc = xmlTextWriterWriteAttribute(writer, BAD_CAST "rhorizon", BAD_CAST str);
     if (rc < 0) {
         printf("saveConfigs: Error at xmlTextWriterWriteAttribute\n");
         return;
     }
     for (i =0 ; i < this->getNStates(); i++) {
         // Start an element named "states" as child of ETOL.
         rc = xmlTextWriterStartElement(writer, BAD_CAST "state");
         if (rc < 0) {
             printf("saveConfigs: Error at xmlTextWriterStartElement\n");
             return;
         }
         memset(str, '\0', 10*sizeof(char));
         snprintf(str, sizeof(str), "%s",
                     std::string("x" + to_string(i)).c_str());
         rc = xmlTextWriterWriteAttribute(writer, BAD_CAST "name", BAD_CAST str);
         if (rc < 0) {
             printf("saveConfigs: Error at xmlTextWriterWriteAttribute\n");
             return;
         }
         char vtype = 'C';
         switch (this->getXvartype().at(i))    {
             case var_t::CONTINUOUS:
                 vtype = 'C';
                 break;
             case var_t::BINARY:
                 vtype = 'B';
                 break;
             case var_t::INTERGER:
                 vtype = 'I';
                 break;
             default:
                 break;
         }
         memset(str, '\0', 10*sizeof(char));
         snprintf(str, sizeof(str), "%c", vtype);
         rc = xmlTextWriterWriteAttribute(writer, BAD_CAST "vartype",
                                             BAD_CAST str);
         if (rc < 0) {
             printf("saveConfigs: Error at xmlTextWriterWriteAttribute\n");
             return;
         }
         memset(str, '\0', 10*sizeof(char));
         snprintf(str, sizeof(str), "%.2f", getXlower().at(i));
         rc = xmlTextWriterWriteAttribute(writer, BAD_CAST "lower",
                                             BAD_CAST str);
         if (rc < 0) {
             printf("saveConfigs: Error at xmlTextWriterWriteAttribute\n");
             return;
         }
         memset(str, '\0', 10*sizeof(char));
         snprintf(str, sizeof(str), "%.2f", getXupper().at(i));
         rc = xmlTextWriterWriteAttribute(writer, BAD_CAST "upper",
                                             BAD_CAST str);
         if (rc < 0) {
             printf("saveConfigs: Error at xmlTextWriterWriteAttribute\n");
             return;
         }
         memset(str, '\0', 10*sizeof(char));
         snprintf(str, sizeof(str), "%.2f", this->getX0().at(i));
         rc = xmlTextWriterWriteAttribute(writer, BAD_CAST "initial",
                                             BAD_CAST str);
         if (rc < 0) {
             printf("saveConfigs: Error at xmlTextWriterWriteAttribute\n");
             return;
         }
         memset(str, '\0', 10*sizeof(char));
         snprintf(str, sizeof(str), "%.2f", this->getXf().at(i));
         rc = xmlTextWriterWriteAttribute(writer, BAD_CAST "terminal",
                                                     BAD_CAST str);
         if (rc < 0) {
             printf("saveConfigs: Error at xmlTextWriterWriteAttribute\n");
             return;
         }
         memset(str, '\0', 10*sizeof(char));
         snprintf(str, sizeof(str), "%.2f", this->getXtol().at(i));
         rc = xmlTextWriterWriteAttribute(writer, BAD_CAST "tolerance",
                                                  BAD_CAST str);
         if (rc < 0) {
             printf("saveConfigs: Error at xmlTextWriterWriteAttribute\n");
             return;
         }
         // Close the element named state.
         rc = xmlTextWriterEndElement(writer);
         if (rc < 0) {
             printf("saveConfigs: Error at xmlTextWriterEndElement\n");
             return;
         }
     }
     // Close the element named states.
     rc = xmlTextWriterEndElement(writer);
     if (rc < 0) {
         printf("saveConfigs: Error at xmlTextWriterEndElement\n");
         return;
     }
     // Start an element named "states" as child of ETOL.
     rc = xmlTextWriterStartElement(writer, BAD_CAST "controls");
     if (rc < 0) {
         printf("saveConfigs: Error at xmlTextWriterStartElement\n");
         return;
     }
     memset(str, '\0', 10*sizeof(char));
     snprintf(str, sizeof(str), "%zu", this->getNControls());
     rc = xmlTextWriterWriteAttribute(writer, BAD_CAST "ncontrols",
                                         BAD_CAST str);
     if (rc < 0) {
         printf("saveConfigs: Error at xmlTextWriterWriteAttribute\n");
         return;
     }
     memset(str, '\0', 10*sizeof(char));
     snprintf(str, sizeof(str), "%zu", this->getUrhorizon());
     rc = xmlTextWriterWriteAttribute(writer, BAD_CAST "rhorizon", BAD_CAST str);
     if (rc < 0) {
         printf("saveConfigs: Error at xmlTextWriterWriteAttribute\n");
         return;
     }
     for (i =0; i < this->getNStates(); i++) {
         // Start an element named "controls" as child of ETOL.
         rc = xmlTextWriterStartElement(writer, BAD_CAST "control");
         if (rc < 0) {
             printf("saveConfigs: Error at xmlTextWriterStartElement\n");
             return;
         }
         memset(str, '\0', 10*sizeof(char));
         snprintf(str, sizeof(str), "%s",
                     std::string("u" + to_string(i)).c_str());
         rc = xmlTextWriterWriteAttribute(writer, BAD_CAST "name", BAD_CAST str);
         if (rc < 0) {
             printf("saveConfigs: Error at xmlTextWriterWriteAttribute\n");
             return;
         }
         char vtype = 'C';
         switch (this->getUvartype().at(i))    {
             case var_t::CONTINUOUS:
                 vtype = 'C';
                 break;
             case var_t::BINARY:
                 vtype = 'B';
                 break;
             case var_t::INTERGER:
                 vtype = 'I';
                 break;
             default:
                 break;
         }
         memset(str, '\0', 10*sizeof(char));
         snprintf(str, sizeof(str), "%c", vtype);
         rc = xmlTextWriterWriteAttribute(writer, BAD_CAST "vartype",
                                             BAD_CAST str);
         if (rc < 0) {
             printf("saveConfigs: Error at xmlTextWriterWriteAttribute\n");
             return;
         }
         memset(str, '\0', 10*sizeof(char));
         snprintf(str, sizeof(str), "%.2f", getUlower().at(i));
         rc = xmlTextWriterWriteAttribute(writer, BAD_CAST "lower",
                                             BAD_CAST str);
         if (rc < 0) {
             printf("saveConfigs: Error at xmlTextWriterWriteAttribute\n");
             return;
         }
         memset(str, '\0', 10*sizeof(char));
         snprintf(str, sizeof(str), "%.2f", getUupper().at(i));
         rc = xmlTextWriterWriteAttribute(writer, BAD_CAST "upper",
                                             BAD_CAST str);
         if (rc < 0) {
             printf("saveConfigs: Error at xmlTextWriterWriteAttribute\n");
             return;
         }
         // Close the element named control.
         rc = xmlTextWriterEndElement(writer);
         if (rc < 0) {
             printf("saveConfigs: Error at xmlTextWriterEndElement\n");
             return;
         }
     }
     // Close the element named controls.
     rc = xmlTextWriterEndElement(writer);
     if (rc < 0) {
         printf("saveConfigs: Error at xmlTextWriterEndElement\n");
         return;
     }
     // Start an element named "exzones" as child of ETOL.
     rc = xmlTextWriterStartElement(writer, BAD_CAST "exzones");
     if (rc < 0) {
         printf("saveConfigs: Error at xmlTextWriterStartElement\n");
         return;
     }
     nzones = 0;
     for (region_t obs : *this->getObstacles())
         nzones +=obs.size();
     memset(str, '\0', 10*sizeof(char));
     snprintf(str, sizeof(str), "%zu", nzones);
     rc = xmlTextWriterWriteAttribute(writer, BAD_CAST "nzones", BAD_CAST str);
     if (rc < 0) {
         printf("saveConfigs: Error at xmlTextWriterWriteAttribute\n");
         return;
     }
     i = 0;
     for (region_t obs : *this->getObstacles()) {
         for (auto bd : obs) {
             border_t corners;
             // Start an element named "border" as child of exzones.
             rc = xmlTextWriterStartElement(writer, BAD_CAST "border");
             if (rc < 0) {
                 printf("saveConfigs: Error at xmlTextWriterStartElement\n");
                 return;
             }
             memset(str, '\0', 10*sizeof(char));
             snprintf(str, sizeof(str), "%s",
                     std::string("exz" + to_string(i)).c_str());
             rc = xmlTextWriterWriteAttribute(writer, BAD_CAST "name",
                                                 BAD_CAST str);
             if (rc < 0) {
                 printf("saveConfigs: Error at xmlTextWriterWriteAttribute\n");
                 return;
             }
             for (auto corn : bd.lower) {
                 corners.push_back(corn);
             }
             corners.erase(std::prev(corners.end()));
             for_each(bd.upper.rbegin(), bd.upper.rend(),
                     [&corners](corner_t corn) {
                 corners.push_back(corn);
             });
             corners.erase(std::prev(corners.end()));
             memset(str, '\0', 10*sizeof(char));
             snprintf(str, sizeof(str), "%zu", corners.size());
             rc = xmlTextWriterWriteAttribute(writer, BAD_CAST "ncorners",
                                                 BAD_CAST str);
             if (rc < 0) {
                 printf("saveConfigs: Error at xmlTextWriterWriteAttribute\n");
                 return;
             }
             for (auto corn : corners) {
                 // Start an element named "corner" as child of border.
                 rc = xmlTextWriterStartElement(writer, BAD_CAST "corner");
                 if (rc < 0) {
                     printf(
                         "saveConfigs: Error at xmlTextWriterStartElement\n");
                     return;
                 }
                 memset(str, '\0', 10*sizeof(char));
                 snprintf(str, sizeof(str), "%.02f", corn.at(0));
                 rc = xmlTextWriterWriteAttribute(writer, BAD_CAST "x",
                                                             BAD_CAST str);
                 if (rc < 0) {
                     printf(
                         "saveConfigs: Error at xmlTextWriterWriteAttribute\n");
                     return;
                 }
                 memset(str, '\0', 10 * sizeof(char));
                 snprintf(str, sizeof(str), "%.02f", corn.at(1));
                 rc = xmlTextWriterWriteAttribute(writer, BAD_CAST "y",
                                                             BAD_CAST str);
                 if (rc < 0) {
                     printf(
                         "saveConfigs: Error at xmlTextWriterWriteAttribute\n");
                     return;
                 }
                 memset(str, '\0', 10 * sizeof(char));
                 snprintf(str, sizeof(str), "%.02f", corn.at(2));
                 rc = xmlTextWriterWriteAttribute(writer, BAD_CAST "z",
                                                             BAD_CAST str);
                 if (rc < 0) {
                     printf(
                         "saveConfigs: Error at xmlTextWriterWriteAttribute\n");
                     return;
                 }
                 // Close the element named corner.
                 rc = xmlTextWriterEndElement(writer);
                 if (rc < 0) {
                     printf("saveConfigs: Error at xmlTextWriterEndElement\n");
                     return;
                 }
             }
             // Close the element named border.
             rc = xmlTextWriterEndElement(writer);
             if (rc < 0) {
                 printf("saveConfigs: Error at xmlTextWriterEndElement\n");
                 return;
             }
             i++;
         }
     }
     // Close the element named exzones.
     rc = xmlTextWriterEndElement(writer);
     if (rc < 0) {
         printf("saveConfigs: Error at xmlTextWriterEndElement\n");
         return;
     }
     // Start an element named "mexzones" as child of ETOL.
     rc = xmlTextWriterStartElement(writer, BAD_CAST "mexzones");
     if (rc < 0) {
         printf("saveConfigs: Error at xmlTextWriterStartElement\n");
         return;
     }
     nzones = this->getNTracks();
     memset(str, '\0', 10 * sizeof(char));
     snprintf(str, sizeof(str), "%zu", nzones);
     rc = xmlTextWriterWriteAttribute(writer, BAD_CAST "nzones", BAD_CAST str);
     if (rc < 0) {
         printf("saveConfigs: Error at xmlTextWriterWriteAttribute\n");
         return;
     }
     i = 0;
     for (auto track : *this->getTracks()) {
         // Start an element named "border" as child of exzones.
         rc = xmlTextWriterStartElement(writer, BAD_CAST "track");
         if (rc < 0) {
             printf("saveConfigs: Error at xmlTextWriterStartElement\n");
             return;
         }
         memset(str, '\0', 10 * sizeof(char));
         snprintf(str, sizeof(str), "%s",
                     std::string("mexz" + to_string(i)).c_str());
         rc = xmlTextWriterWriteAttribute(writer, BAD_CAST "name", BAD_CAST str);
         if (rc < 0) {
             printf("saveConfigs: Error at xmlTextWriterWriteAttribute\n");
             return;
         }
         memset(str, '\0', 10 * sizeof(char));
         snprintf(str, sizeof(str), "%zu", track.trajectory.size());
         rc = xmlTextWriterWriteAttribute(writer, BAD_CAST "nwaypoints",
                                                 BAD_CAST str);
         if (rc < 0) {
             printf("saveConfigs: Error at xmlTextWriterWriteAttribute\n");
             return;
         }
         j = 0;
         for (auto  traj : track.trajectory) {
             rc = xmlTextWriterStartElement(writer, BAD_CAST "waypoint");
             if (rc < 0) {
                 printf("saveConfigs: Error at xmlTextWriterStartElement\n");
                 return;
             }
             memset(str, '\0', 10 * sizeof(char));
             snprintf(str, sizeof(str), "%s",
                         std::string("pt" + std::to_string(j)).c_str());
             rc = xmlTextWriterWriteAttribute(writer, BAD_CAST "name",
                                             BAD_CAST str);
             if (rc < 0) {
                 printf("saveConfigs: Error at xmlTextWriterWriteAttribute\n");
                 return;
             }
             memset(str, '\0', 10 * sizeof(char));
             snprintf(str, sizeof(str), "%.2f", traj.first);
             rc = xmlTextWriterWriteAttribute(writer, BAD_CAST "t",
                                                 BAD_CAST str);
             if (rc < 0) {
                 printf("saveConfigs: Error at xmlTextWriterWriteAttribute\n");
                 return;
             }
             memset(str, '\0', 10 * sizeof(char));
             snprintf(str, sizeof(str), "%zu", traj.second.size());
             rc = xmlTextWriterWriteAttribute(writer, BAD_CAST "ndatums",
                                                     BAD_CAST str);
             if (rc < 0) {
                 printf("saveConfigs: Error at xmlTextWriterWriteAttribute\n");
                 return;
             }
             for (auto pt : traj.second) {
                 rc = xmlTextWriterWriteFormatElement(writer, BAD_CAST "datum",
                                                          "%.2f", pt);
                 if (rc < 0) {
                     printf
                         ("testXmlwriterFilename: Error at WriteElement\n");
                     return;
                 }
             }
             // Close the element named waypoint.
             rc = xmlTextWriterEndElement(writer);
             if (rc < 0) {
                 printf("saveConfigs: Error at xmlTextWriterEndElement\n");
                 return;
             }
             j++;
         }
         // Close the element named track.
         rc = xmlTextWriterEndElement(writer);
         if (rc < 0) {
             printf("saveConfigs: Error at xmlTextWriterEndElement\n");
             return;
         }
         i++;
     }
     // Here we could close the elements, but since we do not want to write any
     // other elements, we simply call xmlTextWriterEndDocument, which will do
     // all the work.
     rc = xmlTextWriterEndDocument(writer);
     if (rc < 0) {
         printf("saveConfigs: Error at xmlTextWriterEndDocument\n");
         return;
     }
     xmlFreeTextWriter(writer);
 }
References ETOL::BINARY, ETOL::CONTINUOUS, getDt(), getNControls(), getNStates(), getNSteps(), getNTracks(), getObstacles(), getTracks(), getUlower(), getUrhorizon(), getUupper(), getUvartype(), getX0(), getXf(), getXlower(), getXrhorizon(), getXtol(), getXupper(), getXvartype(), ETOL::INTERGER, MAXLENGTH, and MY_ENCODING.
Referenced by main().
addParams()
void ETOL::TrajectoryOptimizer::addParams (std::list< param_t > params)
Adds a non-state or non-control variable to the problem.
Parameters
params name and settings for the new variable
Definition at line 1618 of file TrajectoryOptimizer.cpp.
{
     for (auto elem : params)
         this->_parmaeters.insert(std::make_pair(elem.first, elem.second));
 }
References _parmaeters.
Referenced by ETOL::eGLPK::createObstacles(), ETOL::eGLPK::createTracks(), obsConstraint(), and saaConstraint().
addExclZone()
void ETOL::TrajectoryOptimizer::addExclZone (border_t * border)
Add an exclusion zone to the problem.
Parameters
border a list of corners for the exclusion zone
Definition at line 1623 of file TrajectoryOptimizer.cpp.
{
     this->_obstacles_raw.push_back(*border);
     region_t obstacle = TrajectoryOptimizer::genRegion(border);
     if (!obstacle.empty())
         this->_obstacles.push_back(obstacle);
 }
References _obstacles, _obstacles_raw, and genRegion().
Referenced by loadConfigs(), and main().
addAdjTrack()
void ETOL::TrajectoryOptimizer::addAdjTrack (track_t * track)
Add the track of an adjacent or nearby object.
Parameters
track a trajectory with its minimum separation distance
Definition at line 1630 of file TrajectoryOptimizer.cpp.
{
     this->_tracks.push_back(*track);
 }
References _tracks.
Referenced by loadConfigs().
plotX()
void ETOL::TrajectoryOptimizer::plotX (const int idx)
Plot the time history of a state variable.
Parameters
idx the index of the state variable
plotU()
void ETOL::TrajectoryOptimizer::plotU (const int idx)
Plot the time history of a control variable.
Parameters
idx the index of the control variable
genRegion()
region_t ETOL::TrajectoryOptimizer::genRegion (border_t * border) static
Create convex partitions.
Parameters
border a list of corners
Returns
lower and upper segments for convex partitions
Uses CGAL's monotone_partition_2 to partition a polygon into convex polygons. Each polygon has a lower and upper segment. Each segment is sorted from left to right.
Definition at line 84 of file TrajectoryOptimizer.cpp.
{
     region_t region;
     typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
     typedef CGAL::Partition_traits_2<K>                         Traits;
     typedef Traits::Polygon_2                                   Polygon_2;
     typedef std::list<Polygon_2>                                Polygon_list;
     Polygon_2                                                   polygon;
     Polygon_list                                                partition_polys;
     border_t::iterator                                          it;
     std::list<Polygon_2>::const_iterator                        poly_it;
     // Add corners to polygon object
     for (it = border->begin(); it != border->end(); it++)
         polygon.push_back(Traits::Point_2((*it).at(0), (*it).at(1)));
     // Compute polygon partitions
     CGAL::y_monotone_partition_2(polygon.vertices_begin(),
                                     polygon.vertices_end(),
                                     std::back_inserter(partition_polys));
     // Find lower and upper segments
     for (poly_it = partition_polys.begin(); poly_it != partition_polys.end();
             poly_it++) {
         assert(CGAL::is_y_monotone_2((*poly_it).vertices_begin(),
                                        (*poly_it).vertices_end()));
         border_t seg1, seg2;
         border_t::iterator seg1_it, seg2_it;
         Polygon_2::Vertex_const_iterator v_it;
         Polygon_2::Vertex_circulator c, cleft, cright;
         // Find left and right vertices in circulator
         c = (*poly_it).vertices_circulator();
         if (c != NULL) {
             do {
                 if (*c == (*(*poly_it).left_vertex()))
                     cleft = c;
                 else if (*c == (*(*poly_it).right_vertex()))
                     cright = c;
             } while (++c != (*poly_it).vertices_circulator());
         }
         // Copy from left to right in + direction
         c = cleft;
         do {
             seg1.push_back({(*c).x(), (*c).y(), 0.});
         } while (++c != cright);
         seg1.push_back({(*c).x(), (*c).y(), 0.});
         // Copy from left to right in - direction
         c = cright;
         do {
             seg2.push_back({(*c).x(), (*c).y(), 0.});
         } while (++c !=cleft);
         seg2.push_back({(*c).x(), (*c).y(), 0.});
         seg2.reverse();
         // Find lower and upper segments
         v_it = (*poly_it).top_vertex();
         corner_t vtop = {(*v_it).x(), (*v_it).y(), 0.0};
         seg1_it = std::find(seg1.begin(), seg1.end(), vtop);
         seg2_it = std::find(seg2.begin(), seg2.end(), vtop);
         if (seg1_it != seg1.end() && seg2_it != seg2.end()) {
             v_it = (*poly_it).bottom_vertex();
             corner_t vbottom = {(*v_it).x(), (*v_it).y(), 0.};
             if (std::find(seg1.begin(), seg1.end(), vbottom) != seg1.end())
                 region.push_back({seg1, seg2});
             else
                 region.push_back({seg2, seg1});
         } else if (seg1_it != seg1.end()) {
             region.push_back({seg2, seg1});
         } else {
             region.push_back({seg1, seg2});
         }
     }
     return region;
 }
Referenced by addExclZone().
calcSlopes()
void ETOL::TrajectoryOptimizer::calcSlopes (const region_t & region, std::vector< seg_t > * lower, std::vector< seg_t > * upper) static
Computes slopes for lower and upper segments for convex partitions.
Parameters
region lower and upper segments for convex partitions
lower updated to include corners for lower segments
upper updated to include corners for lower segments
Definition at line 161 of file TrajectoryOptimizer.cpp.
{
     lowers->clear();
     uppers->clear();
     for (auto bd : region) {
         seg_t lower, upper;
         border_t::iterator it;
         it = bd.lower.begin();
         for (size_t i(0); i < bd.lower.size() - 1; i++) {
             double m;
             double dely = (*std::next(it, 1)).at(1) - (*it).at(1);
             double delx = (*std::next(it, 1)).at(0) - (*it).at(0);
             if (delx == 0.)
                 m = DBL_MAX;
             else
                 m = dely / delx;
             double len = pow(pow(delx, 2.0) + pow(dely, 2.0), 0.5);
             lower.push_back(edge_t(*it, edge_prop_t({m, len})));
             it++;
         }
         lowers->push_back(lower);
         it = bd.upper.begin();
         for (int i(0); i < bd.upper.size() - 1; i++) {
             double m;
             double dely = (*std::next(it, 1)).at(1) - (*it).at(1);
             double delx = (*std::next(it, 1)).at(0) - (*it).at(0);
             if (delx == 0.)
                 m = DBL_MAX;
             else
                 m = dely / delx;
             double len = pow(pow(delx, 2.0) + pow(dely, 2.0), 0.5);
             upper.push_back(edge_t(*it, edge_prop_t({m, len})));
             it++;
         }
         uppers->push_back(upper);
     }
 }
Referenced by ETOL::eGLPK::createObstacles(), and obsConstraint().
plot()
void ETOL::TrajectoryOptimizer::plot (traj_t * traj, const std::string title = "Time History", const std::string tlab = "t", const std::string xlab = "", double tmin = DBL_MAX, double tmax = DBL_MIN, double xmin = DBL_MAX, double xmax = DBL_MIN) static
Plots a trajectory.
Parameters
traj a pointer to a list of trajectories
title a title for the plot
tlab a label for the time axis
xlab a label for the data axis
tmin a lower bound for the time axis
tmax an upper bound for the time axis
xmin a lower bound for the data axis
xmax an upper bound for the data axis
Definition at line 203 of file TrajectoryOptimizer.cpp.
{
     Gnuplot gp;
     lines_t lines;
     std::string gpcmd;
     if (!(traj->empty())) {
         size_t n = (*(*traj).begin()).second.size();
         bool setTMin(tmin == DBL_MAX), setTMax(tmax == DBL_MIN),
                 setXMin(xmin == DBL_MAX), setXMax(xmax == DBL_MIN);
         for (size_t i(0); i < n ; i++)
             lines.push_back(line_t());
         for (auto elem : *traj) {
             double t = elem.first;
             if (tmin > t && setTMin)
                 tmin = t -1;
             if (tmax < t && setTMax)
                 tmax = t +1;
             int i = 0;
             for (double data : elem.second) {
                 lines.at(i++).push_back(std::make_pair(t, data));
                 if (xmin > data && setXMin)
                     xmin = data - 1;
                 if (xmax < data && setXMax)
                     xmax = data +1;
             }
         }
         gp << "set title '" + title + "'\n";
         gp << "set xlabel'" + xlab  + "'\nset ylabel '" + ylab + "'\n";
         gpcmd = "set xrange [" +
                 std::to_string(tmin) + ":"+    std::to_string(tmax) +
                 "]\n" + "set yrange [" +
                 std::to_string(xmin) + ":"+ std::to_string(xmax) + "]\n";
         gp << gpcmd;
         gp << "set key right bottom\n";
         gpcmd = "plot ";
         for (size_t i(0); i < n ; i++) {
             gpcmd = gpcmd + "'-' with linespoint title 'plot" +
                     std::to_string(i) + "'";
             if (i < n -1)
                 gpcmd = gpcmd + ",";
             else
                 gpcmd = gpcmd + "\n";
         }
         gp << gpcmd;
         for (size_t i(0); i < n ; i++)
             gp.send1d(lines.at(i));
     } else {
         std::cout << "No Data to Plot!!!" << std::endl;
     }
 }
Referenced by main().
plotXY()
void ETOL::TrajectoryOptimizer::plotXY (traj_t * traj, size_t xIdx = 0, size_t yIdx = 1, const std::string title = "XY Plot", const std::string xlab = "x", const std::string ylab = "y", double xmin = DBL_MAX, double xmax = DBL_MIN, double ymin = DBL_MAX, double ymax = DBL_MIN) static
Creates a XY-plot.
Parameters
traj a pointer to a list of trajectories
xIdx an index to the data for the x-axis
yIdx an index to the data for the y-axis
title a title for the plot
xlab a label for the x-axis
ylab a label for the y-axis
xmin a lower bound for the x-axis
xmax an upper bound for the x-axis
ymin a lower bound for the y-axis
ymax an upper bound for the y-axis
Definition at line 261 of file TrajectoryOptimizer.cpp.
{
     Gnuplot gp;
     if (!(traj->empty())) {
         size_t n = (*(*traj).begin()).second.size();
         bool setXMin(xmin == DBL_MAX), setXMax(xmax == DBL_MIN),
                 setYMin(ymin == DBL_MAX), setYMax(ymax == DBL_MIN);
         line_t line;
         for (auto elem : *traj) {
             double x = elem.second.at(xIdx);
             if (xmin > x && setXMin)
                 xmin = x;
             if (xmax < x && setXMax)
                 xmax = x;
             double y = elem.second.at(yIdx);
             int i = 0;
             if (ymin > y && setYMin)
                 ymin = y;
             if (ymax < y && setYMax)
                 ymax = y;
             line.push_back(std::make_pair(x, y));
         }
         double xsep = 0.1 * (xmax - xmin);
         double ysep = 0.1 * (ymax - ymin);
         if (setXMin) xmin-= xsep;
         if (setXMax) xmax+= xsep;
         if (setYMin) ymin-= ysep;
         if (setYMax) ymax+= ysep;
         gp << "set title '" + title + "'\n";
         gp << "set xlabel'" + xlab  + "'\nset ylabel '" + ylab + "'\n";
         gp << "set xrange [" +
                 std::to_string(xmin) + ":"+    std::to_string(xmax) +
                 "]\n" + "set yrange [" +
                 std::to_string(ymin) + ":"+ std::to_string(ymax) + "]\n";
         gp << "set key right bottom\n";
         gp << "plot '-' with linespoint\n ";
         gp.send1d(line);
     } else {
         std::cout << "No Data to Plot!!!" << std::endl;
     }
 }
Referenced by main().
plotXY_wExclZones()
void ETOL::TrajectoryOptimizer::plotXY_wExclZones (traj_t * traj, std::list< region_t > * zones = NULL, size_t xIdx = 0, size_t yIdx = 1, const std::string title = "XY Plot", const std::string xlab = "x", const std::string ylab = "y", double xmin = DBL_MAX, double xmax = DBL_MIN, double ymin = DBL_MAX, double ymax = DBL_MIN) static
Creates a XY-plot wth exclusion zones.
Parameters
traj a pointer to a list of trajectories
zones a pointer to a list of exclusion zones
xIdx an index to the data for the x-axis
yIdx an index to the data for the y-axis
title a title for the plot
xlab a label for the x-axis
ylab a label for the y-axis
xmin a lower bound for the x-axis
xmax an upper bound for the x-axis
ymin a lower bound for the y-axis
ymax an upper bound for the y-axis
Definition at line 312 of file TrajectoryOptimizer.cpp.
{
     Gnuplot gp;
     std::string gpcmd;
     if (!(traj->empty())) {
         size_t n = (*(*traj).begin()).second.size();
         bool setXMin(xmin == DBL_MAX), setXMax(xmax == DBL_MIN),
                 setYMin(ymin == DBL_MAX), setYMax(ymax == DBL_MIN);
         line_t line;
         for (auto elem : *traj) {
             double x = elem.second.at(xIdx);
             if (xmin > x && setXMin)
                 xmin = x;
             if (xmax < x && setXMax)
                 xmax = x;
             double y = elem.second.at(yIdx);
             int i = 0;
             if (ymin > y && setYMin)
                 ymin = y;
             if (ymax < y && setYMax)
                 ymax = y;
             line.push_back(std::make_pair(x, y));
         }
         double xsep = 0.1 * (xmax - xmin);
         double ysep = 0.1 * (ymax - ymin);
         if (setXMin) xmin-= xsep;
         if (setXMax) xmax+= xsep;
         if (setYMin) ymin-= ysep;
         if (setYMax) ymax+= ysep;
         std::list<line_t> obs_lower;
         std::list<line_t> obs_upper;
         if (zones != NULL) {
             if  (!zones->empty()) {
                 for (auto zone : *zones) {
                     for (auto bd : zone) {
                         line_t l;
                         line_t u;
                         for_each(bd.lower.begin(), bd.lower.end(),
                                     [&l](const corner_t &pt){
                             l.push_back(std::make_pair(pt.at(0), pt.at(1)));
                         });
                         for_each(bd.upper.begin(), bd.upper.end(),
                                 [&u](const corner_t &pt){
                             u.push_back(std::make_pair(pt.at(0), pt.at(1)));
                         });
                         obs_lower.push_back(l);
                         obs_upper.push_back(u);
                     }
                 }
             }
         }
         gp << "set title '" + title + "'\n";
         gp << "set xlabel'" + xlab  + "'\nset ylabel '" + ylab + "'\n";
         gp << "set xrange [" +
                 std::to_string(xmin) + ":"+    std::to_string(xmax) +
                 "]\n" + "set yrange [" +
                 std::to_string(ymin) + ":"+ std::to_string(ymax) + "]\n";
         gp << "set key right bottom\n";
         gp << "plot '-' with linespoint title 'Trajectory'";
         for (size_t i(0); i < (obs_lower.size()+ obs_upper.size()); i++) {
             gpcmd+= ",'-' with lines";
         }
         gpcmd = gpcmd + "\n";
         gp << gpcmd;
         gp.send1d(line);
         for (auto obs : obs_lower)
             gp.send1d(obs);
         for (auto obs : obs_upper)
             gp.send1d(obs);
     } else {
         std::cout << "No Data to Plot!!!" << std::endl;
     }
 }
Referenced by main().
animate2D()
std::string ETOL::TrajectoryOptimizer::animate2D (traj_t * traj, const int framerate = 2, bool toFile = false, std::string outFile = "animation.mp4", std::list< region_t > * obstacles = NULL, std::list< track_t > * tracks = NULL, size_t xIdx = 0, size_t yIdx = 1, const std::string title = "notitle", const std::string xlab = "x", const std::string ylab = "y", double xmin = DBL_MAX, double xmax = DBL_MIN, double ymin = DBL_MAX, double ymax = DBL_MIN) static
Creates a 2D animation with static and moving exclusion zones.
Parameters
traj a pointer to a list of trajectories
framerate
toFile if false a animation is displayed, if true it is saved
outFile a .mp4 filename or filepath
obstacles a pointer to the static obstacles
tracks a point to the moving obstacles
xIdx an index to the data for the x-axis
yIdx an index to the data for the y-axis
title a title for the plot
xlab a label for the x-axis
ylab a label for the y-axis
xmin a lower bound for the x-axis
xmax an upper bound for the x-axis
ymin a lower bound for the y-axis
ymax an upper bound for the y-axis
Returns
the .mp4 filepath used
Definition at line 403 of file TrajectoryOptimizer.cpp.
{
     int rc(0);
     char outfile[100];
     std::string cmd(""), gpcmd("");
     if (toFile)
         rc = system("mkdir animation");
     if (rc < 0) {
         printf("animate2D: Error at system 'mkdir'\n");
         return "";
     }
     // Braces ensure gp is collected by garbage collector before 'rm' is called
     {
         Gnuplot gp;
         if (toFile)
             gp << "set terminal png\n";
         if (!(traj->empty())) {
             size_t n = (*(*traj).begin()).second.size();
             bool setXMin(xmin == DBL_MAX), setXMax(xmax == DBL_MIN),
                     setYMin(ymin == DBL_MAX), setYMax(ymax == DBL_MIN);
             line_t line = {};
             std::vector<line_t> mexz_vec = {};
             for (auto elem : *traj) {
                 double t = elem.first;
                 double x = elem.second.at(xIdx);
                 if (xmin > x && setXMin)
                     xmin = x;
                 if (xmax < x && setXMax)
                     xmax = x;
                 double y = elem.second.at(yIdx);
                 int i = 0;
                 if (ymin > y && setYMin)
                     ymin = y;
                 if (ymax < y && setYMax)
                     ymax = y;
                 line.push_back(std::make_pair(x, y));
                 if (tracks != NULL) {
                     for (auto track : *tracks) {
                         std::vector<double> tvec = {};
                         for_each(track.trajectory.begin(),
                                 track.trajectory.end(),
                                 [&tvec](const traj_elem_t &data) {
                             double value = data.first;
                             tvec.push_back(value);
                         });
                         std::vector<double>::iterator tlo_it;
                         tlo_it = std::lower_bound(tvec.begin(), tvec.end(), t);
                         if (tlo_it != tvec.begin())
                             tlo_it = std::prev(tlo_it);
                         size_t jj = distance(tvec.begin(), tlo_it);
                         traj_t::iterator  curr, next;
                         curr = track.trajectory.begin();
                         std::advance(curr, jj);
                         next = curr;
                         if (tlo_it != prev(tvec.end()))
                             std::advance(next, 1);
                         double mx(0), my(0);
                         double delt =  next->first - curr->first;
                         double valx0 = curr->second.at(xIdx);
                         double valy0 = curr->second.at(yIdx);
                         double valx1 = next->second.at(xIdx);
                         double valy1 = next->second.at(yIdx);
                         if (delt != 0) {
                             mx = (valx1 - valx0)/ delt;
                             my = (valy1 - valy0)/ delt;
                         }
                         double cx = valx0 + mx*(t - *tlo_it);
                         double cy = valy0 + my*(t - *tlo_it);
                         double r = track.radius;
                         line_t mexz;
                         for (double alpha=0.; alpha < 1; alpha+=1./24.) {
                             double theta = alpha*2.*3.14159;
                             mexz.push_back(std::make_pair(r*cos(theta) + cx,
                                                            r*sin(theta) + cy));
                         }
                         mexz_vec.push_back(mexz);
                     }
                 }
             }
             double xsep = 0.1 * (xmax - xmin);
             double ysep = 0.1 * (ymax - ymin);
             if (setXMin) xmin-= xsep;
             if (setXMax) xmax+= xsep;
             if (setYMin) ymin-= ysep;
             if (setYMax) ymax+= ysep;
             gp << "set title '" + title + "'\n";
             gp << "set xlabel'" + xlab  + "'\nset ylabel '" + ylab + "'\n";
             gp << "set xrange [" +
                     std::to_string(xmin) + ":"+    std::to_string(xmax) +
                     "]\n" + "set yrange [" +
                     std::to_string(ymin) + ":"+ std::to_string(ymax) + "]\n";
             gp << "set key right bottom\n";
             std::list<line_t> obs;
             if (obstacles != NULL) {
                 if  (!obstacles->empty()) {
                     for (auto zone : *obstacles)
                         for (auto bd : zone) {
                             line_t l;
                             line_t u;
                             for_each(bd.lower.begin(), bd.lower.end(),
                                         [&l](const corner_t &pt){
                                 l.push_back(std::make_pair(pt.at(0), pt.at(1)));
                             });
                             for_each(bd.upper.begin(), bd.upper.end(),
                                     [&u](const corner_t &pt){
                                 u.push_back(std::make_pair(pt.at(0), pt.at(1)));
                             });
                             obs.push_back(l);
                             obs.push_back(u);
                         }
                 }
             }
             gpcmd = "";
             for (size_t i(0); i < (obs.size() + tracks->size()); i++)
                 gpcmd+= ",'-' with lines notitle";
             gpcmd = gpcmd + "\n";
             std::vector<line_t>::iterator mexz_it = mexz_vec.begin();
             for (size_t i = 0; i < line.size(); i++) {
                 if (toFile) {
                     snprintf(outfile, sizeof(outfile),
                             "'animation/my_graph_%03zu.png'", i);
                     gp << "set output " + std::string(outfile) + "\n";
                 }
                 line_t trajline(line.begin(), line.begin()+i+1);
                 gp << "plot '-' with linespoint title 'Trajectory'";
                 gp << gpcmd;
                 gp.send1d(trajline);
                 for (auto o : obs)
                     gp.send1d(o);
                 if (tracks != NULL) {
                     for (auto track : *tracks) {
                         gp.send1d(*mexz_it);
                         std::advance(mexz_it, 1);
                     }
                 }
                 gp.flush();
                 if (toFile)
                     mysleep(10);
                 else
                     mysleep((useconds_t)(1000.0 /
                             static_cast<double>(framerate)));
             }
         } else {
             std::cout << "No Data to Animate!!!" << std::endl;
             outFile = "";
         }
     }
     if (toFile) {
         if (outFile == "")
             outFile = "animation.mp4";
         cmd = "";
         cmd = cmd + "ffmpeg -r "+ std::to_string(framerate) +
                 " -f image2 -s 1920x1080 -i animation/my_graph_%03d.png "+
                 "-vcodec libx264 -crf 25  -pix_fmt yuv420p " + outFile;
         std::cout << cmd << std::endl;
         rc = system(cmd.c_str());
         if (rc < 0) {
             printf("animate2D: Error at system 'ffmpeg'\n");
             return "";
         }
         mysleep(10);
         rc = system("rm -rf animation");
         if (rc < 0) {
             printf("animate2D: Error at system 'rm'\n");
             return "";
         }
     }
     return outFile;
 }
References mexz, mysleep(), obstacles, and tracks.
Referenced by main().
save()
std::string ETOL::TrajectoryOptimizer::save (traj_t * traj, std::string fp = "traj.csv") static
Saves trajectories to a file.
Parameters
traj a pointer to a list of trajectories
fp an absolute or relative path for a file
Returns
name of file created or modified
Definition at line 605 of file TrajectoryOptimizer.cpp.
{
     if (!(traj->empty())) {
         std::string ext = fp.substr(fp.find('.'));
         // Do not overwrite file, but increment with trailing number
         struct stat buf;
         while (stat(fp.c_str(), &buf) != -1) {
             int fIdx;
             std::string fname = fp.substr(0, fp.find('.'));
             size_t last_index = fname.find_last_not_of("0123456789")+1;
             if (fname.size() == last_index)
                 fIdx = 0;
             else
                 fIdx = std::atoi(fname.substr(last_index).c_str());
             fp = fname.substr(0, last_index) + std::to_string(++fIdx) + ext;
         }
         std::ofstream f;
         f.open(fp, std::ios::out);
         size_t n = (*(*traj).begin()).second.size();
         // Write column labels
         std::string row = "time";
         for (size_t idx(0); idx < n; idx++) {
             row+= ",traj" + std::to_string(idx);
         }
         row+= "\n";
         f << row;
         size_t i(0);
         size_t length = (*traj).size();
         // Write data
         for (auto elem : *traj) {
             row = std::to_string(elem.first);
             for (auto data : elem.second) {
                 row+= "," + std::to_string(data);
             }
             if (++i != length)
                 row+= "\n";
             f << row;
         }
         f.close();
     } else {
         std::cout << "No Data to Save!!!" << std::endl;
     }
     return fp;
 }
Referenced by main().
getX0()
state_t & ETOL::TrajectoryOptimizer::getX0 ()
Get the initial state.
Returns
the inital state vector
Definition at line 1644 of file TrajectoryOptimizer.cpp.
{
     return _x0;
 }
References _x0.
Referenced by ETOL::ePSOPT::addBounds(), ETOL::eGurobi::addX0(), ETOL::eOMPL::addX0Xf(), editAlgo(), main(), saveConfigs(), ETOL::eGLPK::setup(), and ETOL::eGurobi::setup().
setX0()
void ETOL::TrajectoryOptimizer::setX0 (const state_t & x0)
Set an initial state.
Parameters
x0 the initial state vector
Definition at line 1648 of file TrajectoryOptimizer.cpp.
{
     this->_x0 = x0;
 }
References _x0.
Referenced by main().
getXf()
state_t & ETOL::TrajectoryOptimizer::getXf ()
Get the goal state.
Returns
the final (or goal) state vector
Definition at line 1652 of file TrajectoryOptimizer.cpp.
{
     return _xf;
 }
References _xf.
Referenced by ETOL::ePSOPT::addBounds(), ETOL::eOMPL::addX0Xf(), ETOL::eGurobi::addXf(), editAlgo(), main(), saveConfigs(), ETOL::eGLPK::setup(), and ETOL::eGurobi::setup().
setXf()
void ETOL::TrajectoryOptimizer::setXf (const state_t & xf)
Set the goal state.
Parameters
xf a final (or goal) state vector
Definition at line 1656 of file TrajectoryOptimizer.cpp.
{
     this->_xf = xf;
 }
References _xf.
Referenced by main().
getNControls()
const size_t ETOL::TrajectoryOptimizer::getNControls () const
Get the number of control variables.
Returns
the dimension of the control vector
Definition at line 1660 of file TrajectoryOptimizer.cpp.
{
     return _nControls;
 }
References _nControls.
Referenced by ETOL::ePSOPT::addBounds(), ETOL::eGurobi::createVars(), ETOL::eOMPL::createVars(), ETOL::ePSOPT::dae(), ETOL::eOMPL::getTraj(), ETOL::eGurobi::getTraj(), ETOL::ePSOPT::integrand_cost(), loadConfigs(), printConfigs(), saveConfigs(), ETOL::ePSOPT::setup(), and ETOL::eGLPK::setup().
getNStates()
const size_t ETOL::TrajectoryOptimizer::getNStates () const
Get the number of state variables.
Returns
the dimension of the state vector
Definition at line 1664 of file TrajectoryOptimizer.cpp.
{
     return _nStates;
 }
References _nStates.
Referenced by ETOL::ePSOPT::addBounds(), ETOL::eGurobi::addDyn(), ETOL::eGurobi::addX0(), ETOL::eOMPL::addX0Xf(), ETOL::eGurobi::addXf(), ETOL::eGurobi::createVars(), ETOL::eOMPL::createVars(), ETOL::ePSOPT::dae(), ETOL::ePSOPT::events(), ETOL::eOMPL::getTraj(), ETOL::eGurobi::getTraj(), ETOL::ePSOPT::integrand_cost(), loadConfigs(), printConfigs(), saveConfigs(), ETOL::ePSOPT::setup(), ETOL::eGurobi::setup(), and ETOL::eGLPK::setup().
getXlower()
state_t & ETOL::TrajectoryOptimizer::getXlower ()
Get the states' lower bound.
Returns
the lower bounds for the states
Definition at line 1668 of file TrajectoryOptimizer.cpp.
{
     return _xlower;
 }
References _xlower.
Referenced by ETOL::ePSOPT::addBounds(), ETOL::eGurobi::createVars(), ETOL::eOMPL::createVars(), saveConfigs(), ETOL::eGurobi::setup(), and ETOL::eGLPK::setup().
setXlower()
void ETOL::TrajectoryOptimizer::setXlower (const state_t & xlower)
Set the states' lower bound.
Parameters
xlower lower bounds for the states
Definition at line 1672 of file TrajectoryOptimizer.cpp.
{
     _xlower = xlower;
 }
References _xlower.
Referenced by main().
getXupper()
state_t & ETOL::TrajectoryOptimizer::getXupper ()
Get the states' upper bound.
Returns
the upper bounds for the states
Definition at line 1676 of file TrajectoryOptimizer.cpp.
{
     return _xupper;
 }
References _xupper.
Referenced by ETOL::ePSOPT::addBounds(), ETOL::eGurobi::createVars(), ETOL::eOMPL::createVars(), saveConfigs(), ETOL::eGurobi::setup(), and ETOL::eGLPK::setup().
setXupper()
void ETOL::TrajectoryOptimizer::setXupper (const state_t & xupper)
Set the states' upper bound.
Parameters
xupper upper bounds for the states
Definition at line 1680 of file TrajectoryOptimizer.cpp.
{
     _xupper = xupper;
 }
References _xupper.
Referenced by main().
getXvartype()
state_var_t & ETOL::TrajectoryOptimizer::getXvartype ()
Get the states' variable type.
Returns
the state variables' type
Definition at line 1684 of file TrajectoryOptimizer.cpp.
{
     return _xvartype;
 }
References _xvartype.
Referenced by ETOL::eGurobi::createVars(), saveConfigs(), ETOL::eGLPK::setup(), and ETOL::eGurobi::setup().
setXvartype()
void ETOL::TrajectoryOptimizer::setXvartype (const state_var_t & xvartype)
Set the states' variable type.
Parameters
xvartype state variables' type
Definition at line 1688 of file TrajectoryOptimizer.cpp.
{
     _xvartype = xvartype;
 }
References _xvartype.
Referenced by main().
getDt()
const double ETOL::TrajectoryOptimizer::getDt () const
Get the time step size.
Returns
the time step size
Definition at line 1692 of file TrajectoryOptimizer.cpp.
{
     return _dt;
 }
References _dt.
Referenced by ETOL::eGurobi::_dynConstr(), ETOL::eGurobi::_objfunc(), ETOL::eGurobi::_pathConstr(), ETOL::ePSOPT::addBounds(), ETOL::eGLPK::createObstacles(), ETOL::eGLPK::createTracks(), ETOL::eGurobi::createVars(), ETOL::ePSOPT::dae(), editAlgo(), ETOL::eGurobi::getTraj(), ETOL::ePSOPT::integrand_cost(), loadConfigs(), main(), obsConstraint(), printConfigs(), saaConstraint(), saveConfigs(), ETOL::eOMPL::setGradient(), and ETOL::ePSOPT::setup().
setDt()
void ETOL::TrajectoryOptimizer::setDt (double dt)
Set the time step size.
Parameters
dt a time step size
Definition at line 1696 of file TrajectoryOptimizer.cpp.
{
     _dt = dt;
 }
References _dt.
Referenced by loadConfigs(), main(), and resetConfigs().
getNSteps()
const size_t ETOL::TrajectoryOptimizer::getNSteps () const
Get the number of time steps.
Returns
the number of time steps
Definition at line 1700 of file TrajectoryOptimizer.cpp.
{
     return _nSteps;
 }
References _nSteps.
Referenced by ETOL::ePSOPT::addBounds(), ETOL::eGurobi::addConstr(), ETOL::eGurobi::addDyn(), ETOL::eGurobi::addObj(), ETOL::eGurobi::addXf(), ETOL::eGLPK::createObstacles(), ETOL::eGLPK::createTracks(), ETOL::eGurobi::createVars(), editAlgo(), ETOL::eGurobi::getTraj(), loadConfigs(), main(), obsConstraint(), printConfigs(), saaConstraint(), saveConfigs(), ETOL::eOMPL::setGradient(), and ETOL::ePSOPT::setup().
setNSteps()
void ETOL::TrajectoryOptimizer::setNSteps (const size_t nSteps)
Set the number of steps.
Parameters
nSteps number of time steps
Definition at line 1704 of file TrajectoryOptimizer.cpp.
{
     _nSteps = nSteps;
 }
References _nSteps.
Referenced by loadConfigs(), and main().
getXtol()
state_t & ETOL::TrajectoryOptimizer::getXtol ()
Get the states' error tolerance.
Returns
the error tolerance for the states
Definition at line 1708 of file TrajectoryOptimizer.cpp.
{
     return _xtol;
 }
References _xtol.
Referenced by ETOL::ePSOPT::addBounds(), ETOL::eGurobi::addXf(), and saveConfigs().
setXtol()
void ETOL::TrajectoryOptimizer::setXtol (const state_t & xtol)
Set the states' error tolerance.
Parameters
xtol error tolerance for the states
Definition at line 1712 of file TrajectoryOptimizer.cpp.
{
     _xtol = xtol;
     for_each(_xtol.begin(), _xtol.end(), [](double x){
         return fabs(x);
     });
 }
References _xtol.
Referenced by main().
getUlower()
state_t & ETOL::TrajectoryOptimizer::getUlower ()
Get the controls' lower bound.
Returns
the lower bound on the controls
Definition at line 1719 of file TrajectoryOptimizer.cpp.
{
     return _ulower;
 }
References _ulower.
Referenced by ETOL::ePSOPT::addBounds(), ETOL::eGurobi::createVars(), ETOL::eOMPL::createVars(), and saveConfigs().
setUlower()
void ETOL::TrajectoryOptimizer::setUlower (const state_t & ulower)
Set the control's lower bound.
Parameters
ulower lower bound on the controls
Definition at line 1723 of file TrajectoryOptimizer.cpp.
{
     _ulower = ulower;
 }
References _ulower.
Referenced by main().
getUupper()
state_t & ETOL::TrajectoryOptimizer::getUupper ()
Get the controls' upper bound.
Returns
the upper bound on the controls
Definition at line 1727 of file TrajectoryOptimizer.cpp.
{
     return _uupper;
 }
References _uupper.
Referenced by ETOL::ePSOPT::addBounds(), ETOL::eGurobi::createVars(), ETOL::eOMPL::createVars(), and saveConfigs().
setUupper()
void ETOL::TrajectoryOptimizer::setUupper (const state_t & uupper)
Set the controls' upper bound.
Parameters
uupper upper bound on the controls
Definition at line 1731 of file TrajectoryOptimizer.cpp.
{
     _uupper = uupper;
 }
References _uupper.
Referenced by main().
getUvartype()
state_var_t & ETOL::TrajectoryOptimizer::getUvartype ()
Get the control variables' type.
Returns
the control variables' type
Definition at line 1735 of file TrajectoryOptimizer.cpp.
{
     return _uvartype;
 }
References _uvartype.
Referenced by ETOL::eGurobi::createVars(), and saveConfigs().
setUvartype()
void ETOL::TrajectoryOptimizer::setUvartype (const state_var_t & uvartype)
Set the control variables' type.
Parameters
uvartype control variables' type
Definition at line 1739 of file TrajectoryOptimizer.cpp.
{
     _uvartype = uvartype;
 }
References _uvartype.
Referenced by main().
getUrhorizon()
const size_t ETOL::TrajectoryOptimizer::getUrhorizon () const
Get the controls' reverse time horizon.
Returns
the reverse time horizon for the control variables
The reverse time horizon is the number of time steps needed that is relative to the current time index. For example, if the current time index is 10, and nu4dyn is 2, then time index 8, 9, and 10 are used when computing the state at time index 10.
Definition at line 1743 of file TrajectoryOptimizer.cpp.
{
     return _urhorizon;
 }
References _urhorizon.
Referenced by ETOL::eGurobi::_dynConstr(), ETOL::ePSOPT::dae(), loadConfigs(), printConfigs(), and saveConfigs().
setUrhorizon()
void ETOL::TrajectoryOptimizer::setUrhorizon (const size_t nu4dyn)
Sets the reverse time horizon for control variables.
Parameters
nu4dyn an integer number of prior time indices
The reverse time horizon is the number of time steps needed that is relative to the current time index. For example, if the current time index is 10, and nu4dyn is 2, then time index 8, 9, and 10 are used when computing the state at time index 10.
Definition at line 1747 of file TrajectoryOptimizer.cpp.
{
     _urhorizon = urhorizon;
     this->_rhorizon = std::max(this->_xrhorizon, this->_urhorizon);
 }
References _rhorizon, _urhorizon, and _xrhorizon.
Referenced by loadConfigs(), main(), and resetConfigs().
getXrhorizon()
const size_t ETOL::TrajectoryOptimizer::getXrhorizon () const
Get the states' reverse time horizon.
Returns
the reverse time horizon for the state variables
The reverse time horizon is the number of time steps needed that is relative to the current time index. For example, if the current time index is 10, and nx4dyn is 2, then state at time index 8, 9, and 10 are used when computing the state at time index 10.
Definition at line 1752 of file TrajectoryOptimizer.cpp.
{
     return _xrhorizon;
 }
References _xrhorizon.
Referenced by ETOL::eGurobi::_dynConstr(), ETOL::ePSOPT::dae(), loadConfigs(), printConfigs(), and saveConfigs().
setXrhorizon()
void ETOL::TrajectoryOptimizer::setXrhorizon (const size_t nx4dyn)
Sets the reverse time horizon for state variables.
Parameters
nx4dyn an integer number of prior time indices
The reverse time horizon is the number of time steps needed that is relative to the current time index. For example, if the current time index is 10, and nx4dyn is 2, then state at time index 8, 9, and 10 are used when computing the state at time index 10.
Definition at line 1756 of file TrajectoryOptimizer.cpp.
{
     _xrhorizon = xrhorizon;
     this->_rhorizon = std::max(this->_xrhorizon, this->_urhorizon);
 }
References _rhorizon, _urhorizon, and _xrhorizon.
Referenced by loadConfigs(), main(), and resetConfigs().
getRhorizon()
size_t ETOL::TrajectoryOptimizer::getRhorizon () const
Get the maximium possible reverse time horizon.
Returns
the maximum possible reverse time horizon
Definition at line 1761 of file TrajectoryOptimizer.cpp.
{
     return _rhorizon;
 }
References _rhorizon.
Referenced by ETOL::eGurobi::addDyn(), and ETOL::eGurobi::addX0().
setNControls()
void ETOL::TrajectoryOptimizer::setNControls (const size_t nControls)
Get the number of control variables.
Parameters
nControls number of control variables
Definition at line 1765 of file TrajectoryOptimizer.cpp.
{
     _nControls = nControls;
 }
References _nControls.
Referenced by loadConfigs(), main(), and resetConfigs().
setNStates()
void ETOL::TrajectoryOptimizer::setNStates (const size_t nStates)
Get the number of state variables.
Parameters
nStates number of state variables
Definition at line 1769 of file TrajectoryOptimizer.cpp.
{
     _nStates = nStates;
 }
References _nStates.
Referenced by loadConfigs(), main(), and resetConfigs().
setEqConstraints()
void ETOL::TrajectoryOptimizer::setEqConstraints (std::vector< f_t * > constraints)
Set the equality constraints.
Parameters
constraints a vector equality constraint functions
Definition at line 1777 of file TrajectoryOptimizer.cpp.
{
     this->_eq = constraints;
 }
References _eq.
setLessEqConstraints()
void ETOL::TrajectoryOptimizer::setLessEqConstraints (std::vector< f_t * > constraints)
Set the inequality constraints.
Parameters
constraints a vector of inequality constraint functions
Definition at line 1781 of file TrajectoryOptimizer.cpp.
{
     this->_lesseq = constraints;
 }
References _lesseq.
setConstraints()
void ETOL::TrajectoryOptimizer::setConstraints (std::vector< f_t * > constraints)
Set sense-agnostic constraint functions.
Parameters
constraints a vector of constraint functions
Definition at line 1773 of file TrajectoryOptimizer.cpp.
{
     this->_constraints = constraints;
 }
References _constraints.
Referenced by main().
setGradient()
void ETOL::TrajectoryOptimizer::setGradient (std::vector< f_t * > gradient)
Set the states' time derivative function.
Parameters
gradient a vector of time derivative functions for the states
Definition at line 1785 of file TrajectoryOptimizer.cpp.
{
     this->_gradient = gradient;
 }
References _gradient.
Referenced by main().
setObjective()
void ETOL::TrajectoryOptimizer::setObjective (f_t * objective)
Set the objective function.
Parameters
objective an objective function
Definition at line 1789 of file TrajectoryOptimizer.cpp.
{
     _objective = objective;
 }
References _objective.
Referenced by main().
getUtraj()
traj_t * ETOL::TrajectoryOptimizer::getUtraj ()
Get the pointer to the computed control trajectory.
Returns
the pointer to the computed control trajectory
Definition at line 1800 of file TrajectoryOptimizer.cpp.
{
     return &(_utraj);
 }
References _utraj.
Referenced by ETOL::ePSOPT::getTraj(), ETOL::eOMPL::getTraj(), ETOL::eGurobi::getTraj(), and main().
getXtraj()
traj_t * ETOL::TrajectoryOptimizer::getXtraj ()
Get the pointer to the computed state trajectory.
Returns
the pointer to the computed state trajectory
Definition at line 1804 of file TrajectoryOptimizer.cpp.
{
     return &(_xtraj);
 }
References _xtraj.
Referenced by ETOL::ePSOPT::getTraj(), ETOL::eOMPL::getTraj(), ETOL::eGurobi::getTraj(), and main().
getObjective()
const f_t * ETOL::TrajectoryOptimizer::getObjective () const
Set the objective function.
Returns
the pointer to the objective function
Definition at line 1808 of file TrajectoryOptimizer.cpp.
{
     return _objective;
 }
References _objective.
getGradient()
std::vector< f_t * > * ETOL::TrajectoryOptimizer::getGradient ()
Get the time derivative functions for the states.
Returns
the pointer to the time derivative functions for the states
Definition at line 1812 of file TrajectoryOptimizer.cpp.
{
     return &(_gradient);
 }
References _gradient.
getEqConstraints()
std::vector< f_t * > * ETOL::TrajectoryOptimizer::getEqConstraints ()
Get the equality constraint functions.
Returns
the pointer to the inequality constraint functions
Definition at line 1816 of file TrajectoryOptimizer.cpp.
{
     return &(_eq);
 }
References _eq.
getLessEqConstraints()
std::vector< f_t * > * ETOL::TrajectoryOptimizer::getLessEqConstraints ()
Get the inequality constraint functions.
Returns
the pointer to the inequality constraint functions
Definition at line 1820 of file TrajectoryOptimizer.cpp.
{
     return &(_lesseq);
 }
References _lesseq.
getConstraints()
std::vector< f_t * > * ETOL::TrajectoryOptimizer::getConstraints ()
Get the sense-agnostic constraint functions.
Returns
the pointer to the constraint functions
Definition at line 1824 of file TrajectoryOptimizer.cpp.
{
     return &(_constraints);
 }
References _constraints.
getObstacles_Raw()
std::vector< border_t > * ETOL::TrajectoryOptimizer::getObstacles_Raw ()
Get the pointer to the unprocessed exclusion zones.
Returns
the pointer to unprocessed exclusion zones
Definition at line 1828 of file TrajectoryOptimizer.cpp.
{
     return &_obstacles_raw;
 }
References _obstacles_raw.
Referenced by ETOL::eOMPL::createVars(), obsConstraint(), and setExz().
getObstacles()
std::list< region_t > * ETOL::TrajectoryOptimizer::getObstacles ()
Get the pointer to the polygon partitioned exclusion zones.
Returns
the pointer to polygon partitioned exclusion zones
Definition at line 1832 of file TrajectoryOptimizer.cpp.
{
     return &_obstacles;
 }
References _obstacles.
Referenced by ETOL::eGLPK::createObstacles(), main(), obsConstraint(), printConfigs(), and saveConfigs().
getTracks()
std::list< track_t > * ETOL::TrajectoryOptimizer::getTracks ()
Get the pointer to the moving exclusion zones.
Returns
the pointer to moving exclusion zones
Definition at line 1836 of file TrajectoryOptimizer.cpp.
{
     return &_tracks;
 }
References _tracks.
Referenced by ETOL::eGLPK::createTracks(), main(), printConfigs(), saaConstraint(), saveConfigs(), and setMexz().
isMaximized()
bool ETOL::TrajectoryOptimizer::isMaximized () const
Get the optimization direction.
Returns
the optimization direction.
True indicates maximization. False indicates minimization
Definition at line 1840 of file TrajectoryOptimizer.cpp.
{
     return _maximize;
 }
References _maximize.
Referenced by ETOL::eGurobi::addObj(), and ETOL::ePSOPT::integrand_cost().
setMaximize()
void ETOL::TrajectoryOptimizer::setMaximize (const bool maximize)
Set the optimization direction.
Parameters
maximize a optimization direction
True indicates maximization. False indicates minimization
Definition at line 1844 of file TrajectoryOptimizer.cpp.
{
     _maximize = maximize;
 }
References _maximize.
Referenced by main().
getNExclZones()
size_t ETOL::TrajectoryOptimizer::getNExclZones ()
Get the number of exclusion zones.
Returns
the number of exclusion zones
Definition at line 1848 of file TrajectoryOptimizer.cpp.
{
     return _obstacles.size();
 }
References _obstacles.
Referenced by printConfigs().
getNTracks()
size_t ETOL::TrajectoryOptimizer::getNTracks ()
Get the number of moving exclusion zones.
Returns
the number of moving exclusion zones
Definition at line 1852 of file TrajectoryOptimizer.cpp.
{
     return _tracks.size();
 }
References _tracks.
Referenced by printConfigs(), and saveConfigs().
errorHandler()
void ETOL::TrajectoryOptimizer::errorHandler () protected
An error handler that is called in try-catch blocks.
Definition at line 1793 of file TrajectoryOptimizer.cpp.
{
     if (this->_eAny != NULL) {
         fprintf(stderr, "%s", this->_eAny->what());
         exit(EXIT_FAILURE);
     }
 }
References _eAny.
Referenced by ETOL::ePSOPT::dae(), ETOL::eGurobi::errorHandler(), and ETOL::ePSOPT::integrand_cost().
setScore()
void ETOL::TrajectoryOptimizer::setScore (const double score) protected
Stores the eSovler's objective function result.
Parameters
score an eSolver's objective function result
Definition at line 1640 of file TrajectoryOptimizer.cpp.
{
     _score = score;
 }
References _score.
Referenced by ETOL::ePSOPT::solve(), ETOL::eGurobi::solve(), ETOL::eGLPK::solve(), and ETOL::eOMPL::solve().
Member Data Documentation
_maximize
bool ETOL::TrajectoryOptimizer::_maximize protected
maximize objective if TRUE
Definition at line 567 of file TrajectoryOptimizer.hpp.
Referenced by isMaximized(), setMaximize(), and TrajectoryOptimizer().
_score
double ETOL::TrajectoryOptimizer::_score protected
optimization result
Definition at line 568 of file TrajectoryOptimizer.hpp.
Referenced by getScore(), setScore(), and TrajectoryOptimizer().
_dt
double ETOL::TrajectoryOptimizer::_dt protected
time step
Definition at line 569 of file TrajectoryOptimizer.hpp.
Referenced by getDt(), setDt(), and TrajectoryOptimizer().
_nSteps
size_t ETOL::TrajectoryOptimizer::_nSteps protected
number of time steps
Definition at line 570 of file TrajectoryOptimizer.hpp.
Referenced by getNSteps(), setNSteps(), and TrajectoryOptimizer().
_nStates
size_t ETOL::TrajectoryOptimizer::_nStates protected
number of state variables
Definition at line 571 of file TrajectoryOptimizer.hpp.
Referenced by ETOL::eGurobi::_dynConstr(), ETOL::eGurobi::_objfunc(), ETOL::eGurobi::_pathConstr(), getNStates(), setNStates(), and TrajectoryOptimizer().
_nControls
size_t ETOL::TrajectoryOptimizer::_nControls protected
number of control variables
Definition at line 572 of file TrajectoryOptimizer.hpp.
Referenced by ETOL::eGurobi::_dynConstr(), ETOL::eGurobi::_objfunc(), ETOL::eGurobi::_pathConstr(), getNControls(), setNControls(), and TrajectoryOptimizer().
_x0
state_t ETOL::TrajectoryOptimizer::_x0 protected
initial state
Definition at line 573 of file TrajectoryOptimizer.hpp.
Referenced by getX0(), loadConfigs(), printConfigs(), resetConfigs(), setX0(), and TrajectoryOptimizer().
_xlower
state_t ETOL::TrajectoryOptimizer::_xlower protected
state lower bound
Definition at line 574 of file TrajectoryOptimizer.hpp.
Referenced by getXlower(), loadConfigs(), printConfigs(), setXlower(), and TrajectoryOptimizer().
_xupper
state_t ETOL::TrajectoryOptimizer::_xupper protected
state upper bound
Definition at line 575 of file TrajectoryOptimizer.hpp.
Referenced by getXupper(), loadConfigs(), printConfigs(), setXupper(), and TrajectoryOptimizer().
_xvartype
state_var_t ETOL::TrajectoryOptimizer::_xvartype protected
state variables' type
Definition at line 576 of file TrajectoryOptimizer.hpp.
Referenced by getXvartype(), loadConfigs(), printConfigs(), resetConfigs(), setXvartype(), and TrajectoryOptimizer().
_xtol
state_t ETOL::TrajectoryOptimizer::_xtol protected
states' error tolerance
Definition at line 577 of file TrajectoryOptimizer.hpp.
Referenced by getXtol(), loadConfigs(), printConfigs(), resetConfigs(), setXtol(), and TrajectoryOptimizer().
_xf
state_t ETOL::TrajectoryOptimizer::_xf protected
goal state
Definition at line 578 of file TrajectoryOptimizer.hpp.
Referenced by getXf(), loadConfigs(), printConfigs(), resetConfigs(), setXf(), and TrajectoryOptimizer().
_ulower
state_t ETOL::TrajectoryOptimizer::_ulower protected
control lower bound
Definition at line 579 of file TrajectoryOptimizer.hpp.
Referenced by getUlower(), loadConfigs(), printConfigs(), resetConfigs(), setUlower(), and TrajectoryOptimizer().
_uupper
state_t ETOL::TrajectoryOptimizer::_uupper protected
control upper bound
Definition at line 580 of file TrajectoryOptimizer.hpp.
Referenced by getUupper(), loadConfigs(), printConfigs(), resetConfigs(), setUupper(), and TrajectoryOptimizer().
_uvartype
state_var_t ETOL::TrajectoryOptimizer::_uvartype protected
control variables' type
Definition at line 581 of file TrajectoryOptimizer.hpp.
Referenced by getUvartype(), loadConfigs(), printConfigs(), resetConfigs(), setUvartype(), and TrajectoryOptimizer().
_xrhorizon
size_t ETOL::TrajectoryOptimizer::_xrhorizon protected
state's reverse time horizon
Definition at line 582 of file TrajectoryOptimizer.hpp.
Referenced by getXrhorizon(), setUrhorizon(), setXrhorizon(), and TrajectoryOptimizer().
_urhorizon
size_t ETOL::TrajectoryOptimizer::_urhorizon protected
control's reverse time horizon
Definition at line 583 of file TrajectoryOptimizer.hpp.
Referenced by getUrhorizon(), setUrhorizon(), setXrhorizon(), and TrajectoryOptimizer().
_rhorizon
size_t ETOL::TrajectoryOptimizer::_rhorizon protected
Maximum reverse time horizon
Definition at line 584 of file TrajectoryOptimizer.hpp.
Referenced by getRhorizon(), setUrhorizon(), setXrhorizon(), and TrajectoryOptimizer().
_parmaeters
paramset_t ETOL::TrajectoryOptimizer::_parmaeters protected
parameter key/value map
Definition at line 585 of file TrajectoryOptimizer.hpp.
Referenced by ETOL::ePSOPT::addBounds(), addParams(), ETOL::eGurobi::createVars(), and ETOL::ePSOPT::setup().
_obstacles_raw
std::vector<border_t> ETOL::TrajectoryOptimizer::_obstacles_raw protected
raw exclusion zones
Definition at line 586 of file TrajectoryOptimizer.hpp.
Referenced by addExclZone(), getObstacles_Raw(), resetConfigs(), and TrajectoryOptimizer().
_obstacles
std::list<region_t> ETOL::TrajectoryOptimizer::_obstacles protected
partitioned exclusion zones
Definition at line 587 of file TrajectoryOptimizer.hpp.
Referenced by addExclZone(), getNExclZones(), getObstacles(), resetConfigs(), and TrajectoryOptimizer().
_tracks
std::list<track_t> ETOL::TrajectoryOptimizer::_tracks protected
moving exclusion zones
Definition at line 588 of file TrajectoryOptimizer.hpp.
Referenced by addAdjTrack(), getNTracks(), getTracks(), resetConfigs(), and TrajectoryOptimizer().
_constraints
std::vector<f_t*> ETOL::TrajectoryOptimizer::_constraints protected
sense-agnostic constraints
Definition at line 589 of file TrajectoryOptimizer.hpp.
Referenced by ETOL::eGurobi::_pathConstr(), ETOL::eGurobi::addConstr(), ETOL::ePSOPT::dae(), getConstraints(), and setConstraints().
_eq
std::vector<f_t*> ETOL::TrajectoryOptimizer::_eq protected
equality constraints
Definition at line 590 of file TrajectoryOptimizer.hpp.
Referenced by getEqConstraints(), and setEqConstraints().
_lesseq
std::vector<f_t*> ETOL::TrajectoryOptimizer::_lesseq protected
inequality constraints
Definition at line 591 of file TrajectoryOptimizer.hpp.
Referenced by getLessEqConstraints(), and setLessEqConstraints().
_gradient
std::vector<f_t*> ETOL::TrajectoryOptimizer::_gradient protected
state time derivatives
Definition at line 592 of file TrajectoryOptimizer.hpp.
Referenced by ETOL::eGurobi::_dynConstr(), ETOL::ePSOPT::dae(), getGradient(), and setGradient().
_objective
f_t* ETOL::TrajectoryOptimizer::_objective protected
objective function
Definition at line 593 of file TrajectoryOptimizer.hpp.
Referenced by ETOL::eGurobi::_objfunc(), getObjective(), ETOL::ePSOPT::integrand_cost(), setObjective(), and TrajectoryOptimizer().
_xtraj
traj_t ETOL::TrajectoryOptimizer::_xtraj protected
state trajectory
Definition at line 594 of file TrajectoryOptimizer.hpp.
Referenced by getXtraj(), and TrajectoryOptimizer().
_utraj
traj_t ETOL::TrajectoryOptimizer::_utraj protected
control trajectory
Definition at line 595 of file TrajectoryOptimizer.hpp.
Referenced by getUtraj(), and TrajectoryOptimizer().
_eAny
std::bad_any_cast* ETOL::TrajectoryOptimizer::_eAny protected
bad cast exception
Definition at line 596 of file TrajectoryOptimizer.hpp.
Referenced by ETOL::eGurobi::_dynConstr(), ETOL::eGurobi::_objfunc(), ETOL::eGurobi::_pathConstr(), ETOL::ePSOPT::dae(), errorHandler(), ETOL::ePSOPT::integrand_cost(), and TrajectoryOptimizer().
The documentation for this class was generated from the following files:
C:/Users/admin/git/ETOL/include/ETOL/TrajectoryOptimizer.hpp
C:/Users/admin/git/ETOL/src/TrajectoryOptimizer/TrajectoryOptimizer.cpp