ETOL: C:/Users/admin/git/ETOL/src/Examples/Gurobi/etol_gurobi_example3.cpp File Reference
etol_gurobi_example3.cpp File Reference
Loads ETOL XML configs, edits it, and saves a ETOL XML file.
#include <ETOL/eGurobi.hpp>
Macros
#define XSHIFT 10.0
Functions
int main (int argc, char **argv)
Detailed Description
Loads ETOL XML configs, edits it, and saves a ETOL XML file.
Copyright
2020 Olatunde Sanni
Author
Olatunde Sanni olasa.nosp@m.nni1.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Date
1 May 2020
Version
1.0.0
DESCRIPTION
Adds a constant to each state's initial and terminal value. This is accomplished without requiring ETOL to perform an optimization!!!
Definition in file etol_gurobi_example3.cpp.
Macro Definition Documentation
XSHIFT
#define XSHIFT 10.0
Definition at line 17 of file etol_gurobi_example3.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 22 of file etol_gurobi_example3.cpp.
{
     if (!(argc == 2 || argc == 3)) {
         printf("Usage: %s <ETOL configuration xml filepath> ", argv[0]);
         printf("or <old path> <new path> \n");
         exit(EXIT_FAILURE);
     }
     TrajectoryOptimizer* t;
     eGurobi tg = eGurobi();
     t = &tg;
     t->loadConfigs(argv[1]);
     printf("\nLoaded Configs\n");
     t->printConfigs();
     // Shifts the initial and terminal values by XSHIFT
     for_each(t->getX0().begin(), t->getX0().end(), [](double &x){
         x+=XSHIFT;
     });
     for_each(t->getXf().begin(), t->getXf().end(), [](double &x){
         x+=XSHIFT;
     });
     t->saveConfigs(argv[argc - 1]);
     printf("New Configs\n");
     t->printConfigs();
     t->close();
     return EXIT_SUCCESS;
 }
References ETOL::TrajectoryOptimizer::close(), ETOL::TrajectoryOptimizer::getX0(), ETOL::TrajectoryOptimizer::getXf(), ETOL::TrajectoryOptimizer::loadConfigs(), ETOL::TrajectoryOptimizer::printConfigs(), and ETOL::TrajectoryOptimizer::saveConfigs().