ETOL: C:/Users/admin/git/ETOL/src/Examples/GLPK/etol_glpk_example1.cpp File Reference
etol_glpk_example1.cpp File Reference
Loads a ETOL Config XML file and uses GLPK to solve a ETOL.
#include <re2/re2.h>
#include <iostream>
#include <ETOL/eGLPK.hpp>
Macros
#define M_PI 3.14159265358979323846
#define BIGM 1000
#define NSIDES 4
Functions
ETOL::scalar_t objFunction (F_ARGS)
ETOL::scalar_t dxConstraint (F_ARGS)
ETOL::scalar_t dyConstraint (F_ARGS)
ETOL::scalar_t absConstraint (F_ARGS)
ETOL::f_t obsConstraint (ETOL::TrajectoryOptimizer *)
ETOL::f_t saaConstraint (ETOL::TrajectoryOptimizer *)
int main (int argc, char **argv)
Variables
std::vector< ETOL::closure_t > obstacles
std::vector< ETOL::track_t > tracks
Detailed Description
Loads a ETOL Config XML file and uses GLPK to solve a ETOL.
Copyright
2020 Thanakorn Khamvilai
Author
Thanakorn Khamvilai thana.nosp@m.korn.nosp@m.khamv.nosp@m.ilai.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Date
6 May 2020
Version
1.0.0
DESCRIPTION
Solves the following MILP minimize sum(u_k_2 + u_k_3) for k = 0 to NSteps subject to x_k = x_(k-1) + dt * u_k_0 for k = 0 to Nsteps y_k = y_(k-1) + dt * u_k_1 for k = 0 to Nsteps u_k_2 = |u_k_0| for k = 0 to Nsteps u_k_3 = |u_k_1| for k = 0 to Nsteps (x_k, y_k) notin Obstacle for k = 0 to Nsteps (x_k, y_k) notin Moving Obstacle for k = 0 to Nsteps
Definition in file etol_glpk_example1.cpp.
Macro Definition Documentation
M_PI
#define M_PI 3.14159265358979323846
Definition at line 26 of file etol_glpk_example1.cpp.
BIGM
#define BIGM 1000
Definition at line 28 of file etol_glpk_example1.cpp.
NSIDES
#define NSIDES 4
Definition at line 29 of file etol_glpk_example1.cpp.
Function Documentation
objFunction()
ETOL::scalar_t objFunction (F_ARGS)
Definition at line 95 of file etol_glpk_example1.cpp.
{
     int tIdx = std::any_cast<int>(k);
     std::vector<ETOL::glpk_t> obj;
     obj.emplace_back("u", tIdx, 2, 1);
     obj.emplace_back("u", tIdx, 3, 1);
     return obj;
 }
Referenced by main().
dxConstraint()
ETOL::scalar_t dxConstraint (F_ARGS)
Definition at line 103 of file etol_glpk_example1.cpp.
{
     int tIdx = std::any_cast<int>(k);
     std::vector<ETOL::glpk_t> dx;
     dx.emplace_back("x", tIdx, 0, -1);
     dx.emplace_back("x", tIdx-1, 0, 1);
     dx.emplace_back("u", tIdx, 0, std::any_cast<double>(dt));
     return dx;
 }
Referenced by main().
dyConstraint()
ETOL::scalar_t dyConstraint (F_ARGS)
Definition at line 112 of file etol_glpk_example1.cpp.
{
     int tIdx = std::any_cast<int>(k);
     std::vector<ETOL::glpk_t> dy;
     dy.emplace_back("x", tIdx, 1, -1);
     dy.emplace_back("x", tIdx-1, 1, 1);
     dy.emplace_back("u", tIdx, 1, std::any_cast<double>(dt));
     return dy;
 }
Referenced by main().
absConstraint()
ETOL::scalar_t absConstraint (F_ARGS)
Definition at line 121 of file etol_glpk_example1.cpp.
{
     int tIdx = std::any_cast<int>(k);
     std::vector<ETOL::glpk_t> abs_c;
     std::vector<std::pair<std::vector<ETOL::glpk_t>, ETOL::glpk_bnd_t>>
                                                                         abs_cv;
     abs_c.emplace_back("u", tIdx, 0, 1);
     abs_c.emplace_back("u", tIdx, 2, 1);
     abs_cv.emplace_back(abs_c, ETOL::glpk_bnd_t(0.0, GLPK_UNBOUND));
     abs_c.clear();
     abs_c.emplace_back("u", tIdx, 0, -1);
     abs_c.emplace_back("u", tIdx, 2, 1);
     abs_cv.emplace_back(abs_c, ETOL::glpk_bnd_t(0.0, GLPK_UNBOUND));
     abs_c.clear();
     abs_c.emplace_back("u", tIdx, 1, 1);
     abs_c.emplace_back("u", tIdx, 3, 1);
     abs_cv.emplace_back(abs_c, ETOL::glpk_bnd_t(0.0, GLPK_UNBOUND));
     abs_c.clear();
     abs_c.emplace_back("u", tIdx, 1, -1);
     abs_c.emplace_back("u", tIdx, 3, 1);
     abs_cv.emplace_back(abs_c, ETOL::glpk_bnd_t(0.0, GLPK_UNBOUND));
     abs_c.clear();
     return abs_cv;
 }
References GLPK_UNBOUND.
Referenced by main().
obsConstraint()
ETOL::f_t obsConstraint (ETOL::TrajectoryOptimizer * t)
Definition at line 150 of file etol_glpk_example1.cpp.
{
     obstacles = ETOL::eGLPK::createObstacles(t);
     ETOL::f_t o = [](F_ARGS) {
         int tIdx = std::any_cast<int>(k);
         std::vector<ETOL::glpk_t> abs_obs;
         std::vector<std::pair<std::vector<ETOL::glpk_t>,
             ETOL::glpk_bnd_t>> abs_obsv, abs_obsv_bot, abs_obsv_top,
                                     abs_obsv_sum;
         int ii = 0;
         for (auto bd : obstacles) {
             int jj = 0;
             for (const auto& lower : bd.first) {
                 abs_obsv_bot = ETOL::eGLPK::addObstacleSides(lower, -1,
                                             "bot", ii, jj, tIdx, pnames, BIGM);
                 abs_obsv.insert(abs_obsv.end(),
                         abs_obsv_bot.begin(), abs_obsv_bot.end());
                 ETOL::seg_t upper = bd.second.at(jj);
                 abs_obsv_top = ETOL::eGLPK::addObstacleSides(upper, 1,
                                             "top", ii, jj, tIdx, pnames, BIGM);
                 abs_obsv.insert(abs_obsv.end(),
                             abs_obsv_top.begin(), abs_obsv_top.end());
                 abs_obsv_sum = ETOL::eGLPK::addObstacleSum("^(?:bot|top)",
                                                     ii, jj, tIdx, pnames, 0);
                 abs_obsv.insert(abs_obsv.end(),
                             abs_obsv_sum.begin(), abs_obsv_sum.end());
                 jj++;
             }
             ii++;
         }
         return abs_obsv;
     };
     return o;
 }
References ETOL::eGLPK::addObstacleSides(), ETOL::eGLPK::addObstacleSum(), BIGM, ETOL::eGLPK::createObstacles(), F_ARGS, and obstacles.
Referenced by main().
saaConstraint()
ETOL::f_t saaConstraint (ETOL::TrajectoryOptimizer * t)
Definition at line 186 of file etol_glpk_example1.cpp.
{
     tracks = ETOL::eGLPK::createTracks(t, NSIDES);
     ETOL::f_t saa = [](F_ARGS){
         auto delta = std::any_cast<double>(dt);
         int tIdx = std::any_cast<int>(k);
         double t = delta * tIdx;
         std::vector<ETOL::glpk_t> abs_saa;
         std::vector<std::pair<std::vector<ETOL::glpk_t>,
                     ETOL::glpk_bnd_t>> abs_saav, abs_saav_sum;
         int ii = 0;
         for (auto track : tracks) {
             double radius = track.radius;
             std::vector<double> tvec;
             for_each(track.trajectory.begin(), track.trajectory.end(), [&tvec]
                     (const ETOL::traj_elem_t& data){
                 double value = data.first;
                 tvec.push_back(value);
             });
             std::vector<double>::iterator tlo_it;
             tlo_it = std::lower_bound(tvec.begin(), tvec.end(), t);
             if (tlo_it != tvec.begin() && *tlo_it > t)
                 tlo_it = std::prev(tlo_it);
             size_t jj = distance(tvec.begin(), tlo_it);
             ETOL::traj_t::iterator  curr, next;
             curr = track.trajectory.begin();
             std::advance(curr, jj);
             next = curr;
             if (tlo_it != prev(tvec.end()))
                 std::advance(next, 1);
             double delt =  next->first - curr->first;
             double rhs;
             for (int kk = 0; kk < NSIDES; kk++) {
                 std::string r(ETOL::eGLPK::getParamName(
                     ETOL::eGLPK::getParamName("d", ii, jj, kk), tIdx));
                 int i = 0;
                 for (const auto& pname : pnames) {
                     if (re2::RE2::FullMatch(pname, r)) {
                         abs_saa.emplace_back(pname, tIdx, -1, BIGM);
                         break;
                     }
                     i++;
                 }
                 double c0 = cos(2. * M_PI * static_cast<double>(kk) /
                         static_cast<double>(NSIDES));
                 double c1 = sin(2. * M_PI * static_cast<double>(kk) /
                         static_cast<double>(NSIDES));
                 double mx(0), my(0);
                 double valx0 = curr->second.at(0);
                 double valy0 = curr->second.at(1);
                 double valx1 = next->second.at(0);
                 double valy1 = next->second.at(1);
                 if (delt != 0) {
                     mx = (valx1 - valx0)/ delt;
                     my = (valy1 - valy0)/ delt;
                 }
                 double cx = valx0 + mx*(t - *tlo_it);
                 double cy = valy0 + my*(t - *tlo_it);
                 rhs =  c0*cx + c1*cy + radius;
                 abs_saa.emplace_back("x", tIdx, 0, c0);  // x
                 abs_saa.emplace_back("x", tIdx, 1, c1);  // y
                 abs_saav.emplace_back(abs_saa,
                         ETOL::glpk_bnd_t(rhs, GLPK_UNBOUND));
                 abs_saa.clear();
             }
             abs_saav_sum = ETOL::eGLPK::addObstacleSum("^d", ii, jj, tIdx,
                                                                 pnames, NSIDES);
             abs_saav.insert(abs_saav.end(), abs_saav_sum.begin(),
                                                         abs_saav_sum.end());
             ii++;
         }
         return abs_saav;
     };
     return saa;
 }
References ETOL::eGLPK::addObstacleSum(), BIGM, ETOL::eGLPK::createTracks(), F_ARGS, ETOL::eGLPK::getParamName(), GLPK_UNBOUND, M_PI, NSIDES, and tracks.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 42 of file etol_glpk_example1.cpp.
{
     if (argc != 2) {
         printf("Usage: %s <ETOL configuration xml filepath>\n", argv[0]);
         exit(EXIT_FAILURE);
     }
     std::cout << "GLPK" << std::endl;
     ETOL::TrajectoryOptimizer* t;
     ETOL::eGLPK tg = ETOL::eGLPK();
     t = &tg;
     t->loadConfigs(argv[1]);
     // t->printConfigs();
     t->setMaximize(false);
     ETOL::f_t obj = &objFunction;
     t->setObjective(&obj);
     ETOL::f_t dx = &dxConstraint;
     ETOL::f_t dy = &dyConstraint;
     t->setGradient({&dx, &dy});
     ETOL::f_t absv, obs, saa;
     absv = &absConstraint;
     obs = obsConstraint(t);
     saa = saaConstraint(t);
     t->setConstraints({&absv, &obs, &saa});
     // Setup
     t->setup();
     // Debug
     t->debug();
     // Solve
     t->solve();
     // Result
     std::cout << "\n!!!!!!!!!!!!!!!!!Results!!!!!!!!!!!!!!!!!" << std::endl;
     std::cout << "Minimization Score:\t" << t->getScore() << std::endl;
     std::cout << "Plotting..." << std::endl;
     ETOL::TrajectoryOptimizer::plotXY_wExclZones(t->getXtraj(),
                                                     t->getObstacles());
 //    ETOL::TrajectoryOptimizer::animate2D(t->getXtraj(), 1, false,
 //            "animation.mp4", t->getObstacles(), t->getTracks());
     // Release resources e.g. memory
     t->close();
     return EXIT_SUCCESS;
 }
References absConstraint(), ETOL::TrajectoryOptimizer::close(), ETOL::TrajectoryOptimizer::debug(), dxConstraint(), dyConstraint(), ETOL::TrajectoryOptimizer::getObstacles(), ETOL::TrajectoryOptimizer::getScore(), ETOL::TrajectoryOptimizer::getXtraj(), ETOL::TrajectoryOptimizer::loadConfigs(), objFunction(), obsConstraint(), ETOL::TrajectoryOptimizer::plotXY_wExclZones(), saaConstraint(), ETOL::TrajectoryOptimizer::setConstraints(), ETOL::TrajectoryOptimizer::setGradient(), ETOL::TrajectoryOptimizer::setMaximize(), ETOL::TrajectoryOptimizer::setObjective(), ETOL::TrajectoryOptimizer::setup(), and ETOL::TrajectoryOptimizer::solve().
Variable Documentation
obstacles
std::vector<ETOL::closure_t> obstacles
Definition at line 31 of file etol_glpk_example1.cpp.
Referenced by ETOL::TrajectoryOptimizer::animate2D(), ETOL::eGLPK::createObstacles(), and obsConstraint().
tracks
std::vector<ETOL::track_t> tracks
Definition at line 32 of file etol_glpk_example1.cpp.
Referenced by ETOL::TrajectoryOptimizer::animate2D(), ETOL::eGLPK::createTracks(), and saaConstraint().