ETOL: C:/msys64/home/admin/ETOL/src/Examples/PSOPT/etol_psopt_example1.cpp File Reference
etol_psopt_example1.cpp File Reference
Loads a ETOL Config XML file and uses PSOPT to solve a ETOL.
#include <iostream>
#include <ETOL/ePSOPT.hpp>
Functions
void editAlgo (ETOL::TrajectoryOptimizer *)
ETOL::scalar_t objFunction (F_ARGS)
ETOL::scalar_t dxdt (F_ARGS)
ETOL::scalar_t dydt (F_ARGS)
ETOL::f_t obsConstraint (ETOL::TrajectoryOptimizer *)
ETOL::f_t saaConstraint (ETOL::TrajectoryOptimizer *t)
std::string paramName (const std::string, const size_t &, const size_t &, const size_t &)
int main (int argc, char **argv)
string paramName (const string name, const size_t &i, const size_t &j, const size_t &k)
Variables
std::vector< ETOL::border_t > * obstacles
std::vector< std::pair< double, DMatrix > > tracks = {}
Detailed Description
Loads a ETOL Config XML file and uses PSOPT to solve a ETOL.
Copyright
2020 Olatunde Sanni
Author
Olatunde Sanni olasa.nosp@m.nni1.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Date
5 May 2020
Version
1.0.1
DESCRIPTION
Solves the following OCP minimize integral (u0(t) *u0(t) + u1(t) *u1(t)) from t0 to tf subject to dx/dt = u0(t) for t in {t0,tf} dy/dt = u1(t) for t in {t0,tf} <x(t) y(t)> notin Obstacle for t in {t0,tf} <x(t),y(t)> notin Moving Obstacle for t in {t0,tf}
Definition in file etol_psopt_example1.cpp.
Function Documentation
editAlgo()
void editAlgo (ETOL::TrajectoryOptimizer * t)
Definition at line 82 of file etol_psopt_example1.cpp.
{
     ETOL::ePSOPT* ptr = dynamic_cast<ETOL::ePSOPT*>(t);
     if (ptr) {
         Alg* algo = ptr->getAlgorithm();
         algo->defect_scaling                 = "jacobian-based";
         algo->ipopt_max_cpu_time            = 100;
         algo->mr_max_iterations                = 40;
         algo->ode_tolerance                    = 1.e-3;
     } else {
         std::cout << "EditAlgo only works for ePSOPT!" << std::endl;
         exit(EXIT_FAILURE);
     }
 }
References ETOL::ePSOPT::getAlgorithm().
Referenced by main().
objFunction()
ETOL::scalar_t objFunction (F_ARGS)
Definition at line 96 of file etol_psopt_example1.cpp.
{
     adouble obj;
     try {
         adouble u0, u1;
         u0 = *std::any_cast<adouble*>(u.at(0));
         u1 = *std::any_cast<adouble*>(u.at(1));
         obj = u0 *u0 + u1*u1;
     } catch(std::bad_any_cast& e ) {
         cout << "Error in obj" << std::endl;
         cout << e.what() << endl;;
         exit(EXIT_FAILURE);
     }
     return obj;
 }
Referenced by main().
dxdt()
ETOL::scalar_t dxdt (F_ARGS)
Definition at line 111 of file etol_psopt_example1.cpp.
{
     adouble* xdot;
     try {
         xdot = std::any_cast<adouble*>(u.at(0));
     } catch(std::bad_any_cast& e ) {
         cout << "Error in dxdt" << std::endl;
         cout << e.what() << endl;;
         exit(EXIT_FAILURE);
     }
     return *xdot;
 }
Referenced by main().
dydt()
ETOL::scalar_t dydt (F_ARGS)
Definition at line 123 of file etol_psopt_example1.cpp.
{
     adouble* ydot;
     try {
         ydot = std::any_cast<adouble*>(u.at(1));
     } catch(std::bad_any_cast& e ) {
         cout << "Error in dydt" << std::endl;
         cout << e.what() << endl;;
         exit(EXIT_FAILURE);
     }
     return *ydot;
 }
Referenced by main().
obsConstraint()
ETOL::f_t obsConstraint (ETOL::TrajectoryOptimizer * t)
Definition at line 135 of file etol_psopt_example1.cpp.
{
     ETOL::f_t obs;
     double tspan = t->getDt() * t->getNSteps();
     obstacles = t->getObstacles_Raw();
     size_t i(0);
     for (auto obs : *t->getObstacles_Raw()) {
         size_t j(0);
         for (auto bd : obs)
             t->addParams({std::pair<PARAM_PAIR>(paramName("side", i, j++, 0),
                         {ETOL::var_t::CONTINUOUS, -1000., 0., 0., tspan})});
         i++;
     }
     obs = [](F_ARGS) {
         ETOL::fout_psopt_t fout;
         try {
             adouble xk, yk;
             xk = *std::any_cast<adouble*>(x.at(0));
             yk = *std::any_cast<adouble*>(x.at(1));
             for (auto bd : *obstacles) {
                 std::list<ETOL::corner_t>::iterator curr = bd.begin();
                 std::list<ETOL::corner_t>::iterator next = std::next(
                                                                     curr, 1);
                 for (size_t i=0; i < bd.size(); i++) {
                     double xa = curr->at(0);
                     double ya = curr->at(1);
                     double xb = next->at(0);
                     double yb = next->at(1);
                     double xc = (xb + xa)/2.;
                     double    m = (yb - ya)/(xb-xa);
                     double yc = ya + m*(xc - xa);
                     double radsq = pow(xc - xa, 2.0) + pow(yc - ya, 2.0);
                     double tt = -1.0 * atan2(yc - ya, xc - xa);
                     adouble dx = xk - xc;
                     adouble dy = yk - yc;
                     adouble delx = cos(tt) * dx  - sin(tt) * dy;
                     adouble dely = sin(tt) * dx  + cos(tt) * dy;
                     double asq = radsq;
                     double bsq = .2 * radsq;
                     adouble out;
                     out = asq*bsq - (bsq*pow(delx, 2.) +asq*pow(dely, 2.));
                     fout.push_back(out);
                     curr++;
                     next++;
                     if (next == bd.end())
                         next = bd.begin();
                 }
             }
         } catch(std::bad_any_cast& e ) {
             std::cout << "Error in obs" << std::endl;
             std::cout << e.what() << std::endl;;
             exit(EXIT_FAILURE);
         }
         return fout;
     };
     return obs;
 }
References ETOL::TrajectoryOptimizer::addParams(), ETOL::CONTINUOUS, F_ARGS, ETOL::TrajectoryOptimizer::getDt(), ETOL::TrajectoryOptimizer::getNSteps(), ETOL::TrajectoryOptimizer::getObstacles_Raw(), obstacles, and paramName().
Referenced by main().
saaConstraint()
ETOL::f_t saaConstraint (ETOL::TrajectoryOptimizer * t)
Definition at line 194 of file etol_psopt_example1.cpp.
{
     ETOL::f_t saa;
     tracks.clear();
     double tspan = t->getDt() * t->getNSteps();
     // Construct a table for each track e.g.
     // time state1     state2     state 3 ...
     // 0    1        2        3
     // 1.5    2        4        5
     size_t i(0);
     for (auto track : *t->getTracks()) {
         DMatrix tbl = zeros(track.trajectory.size(),
                     track.trajectory.front().second.size()+1);
         size_t j(1);
         for (auto data : track.trajectory) {
             double& t = tbl.elem(j, 1);
             t = data.first;
             size_t k(2);
             for (auto state : data.second) {
                 double& val = tbl.elem(j, k);
                 val = state;
                 k++;
             }
             j++;
         }
         tracks.push_back(std::pair<double, DMatrix>(track.radius, tbl));
         t->addParams({std::pair<PARAM_PAIR>(paramName("ball", i, 0, 0),
                         {ETOL::var_t::CONTINUOUS, -1000., 0., 0., tspan})});
         i++;
     }
     saa = [](F_ARGS){
         ETOL::fout_psopt_t fout;
         try {
             adouble xk, yk;
             xk = *std::any_cast<adouble*>(x.at(0));
             yk = *std::any_cast<adouble*>(x.at(1));
             adouble tval = *std::any_cast<adouble*>(k);
             for (auto track : tracks) {
                 adouble xc, yc;
                 linear_interpolation(&xc, tval, track.second.Column(1),
                         track.second.Column(2), track.second.GetNoRows());
                 linear_interpolation(&yc, tval, track.second.Column(1),
                         track.second.Column(3), track.second.GetNoRows());
                 adouble dx = xk - xc;
                 adouble dy = yk - yc;
                 adouble dist = pow(dx, 2.0) + pow(dy, 2.0);
                 adouble circ = dist * (-1.) + pow(track.first, 2.0);
                 fout.push_back(circ);
             }
         } catch(std::bad_any_cast& e ) {
             std::cout << "Error in saa" << std::endl;
             std::cout << e.what() << endl;;
             exit(EXIT_FAILURE);
         }
         return fout;
     };
     return saa;
 }
References ETOL::TrajectoryOptimizer::addParams(), ETOL::CONTINUOUS, F_ARGS, ETOL::TrajectoryOptimizer::getDt(), ETOL::TrajectoryOptimizer::getNSteps(), ETOL::TrajectoryOptimizer::getTracks(), paramName(), and tracks.
Referenced by main().
paramName() [1/2]
std::string paramName (const std::string , const size_t & , const size_t & , const size_t &)
Definition at line 459 of file etol_gurobi_example1.cpp.
{
     return (name + "_" + std::to_string(i) + "_" + std::to_string(j) + "_" +
             std::to_string(k));
 }
Referenced by obsConstraint(), and saaConstraint().
main()
int main (int argc, char ** argv)
Definition at line 36 of file etol_psopt_example1.cpp.
{
     if (argc != 2) {
         printf("Usage: %s <ETOL configuration xml filepath>\n", argv[0]);
         exit(EXIT_FAILURE);
     }
     ETOL::TrajectoryOptimizer* t;
     ETOL::ePSOPT tp = ETOL::ePSOPT();
     t = &tp;
     t->loadConfigs(argv[1]);
     t->printConfigs();
     t->setMaximize(false);
     ETOL::f_t obj = &objFunction;
     t->setObjective(&obj);
     ETOL::f_t xdot = &dxdt;
     ETOL::f_t ydot = &dydt;
     t->setGradient({&xdot, &ydot});
     // Obstacle Constraint
     ETOL::f_t obs, saa;
     obs = obsConstraint(t);
     saa = saaConstraint(t);
     t->setConstraints({&obs, &saa});
     // Setup
     t->setup();
     editAlgo(t);
     t->debug();
     // Solve
     t->solve();
     // Results
     printf("\n!!!!!!!!!!!!!!!!!Results!!!!!!!!!!!!!!!!!\n");
     printf("Minimization Score:\t%f\n", t->getScore());
     printf("Animating...\n");
     ETOL::TrajectoryOptimizer::animate2D(t->getXtraj(), 10 , false,
             "animation.mp4", t->getObstacles(), t->getTracks());
     // Gracefully release resources e.g. memory, file handles, etc
     t->close();
     return EXIT_SUCCESS;
 }
References ETOL::TrajectoryOptimizer::animate2D(), ETOL::TrajectoryOptimizer::close(), ETOL::TrajectoryOptimizer::debug(), dxdt(), dydt(), editAlgo(), ETOL::TrajectoryOptimizer::getObstacles(), ETOL::TrajectoryOptimizer::getScore(), ETOL::TrajectoryOptimizer::getTracks(), ETOL::TrajectoryOptimizer::getXtraj(), ETOL::TrajectoryOptimizer::loadConfigs(), objFunction(), obsConstraint(), ETOL::TrajectoryOptimizer::printConfigs(), saaConstraint(), ETOL::TrajectoryOptimizer::setConstraints(), ETOL::TrajectoryOptimizer::setGradient(), ETOL::TrajectoryOptimizer::setMaximize(), ETOL::TrajectoryOptimizer::setObjective(), ETOL::TrajectoryOptimizer::setup(), and ETOL::TrajectoryOptimizer::solve().
paramName() [2/2]
string paramName (const string name, const size_t & i, const size_t & j, const size_t & k)
Definition at line 255 of file etol_psopt_example1.cpp.
{
     return (name + "_" + std::to_string(i) + "_" + std::to_string(j) +
             "_" + std::to_string(k));
 }
Variable Documentation
obstacles
std::vector<ETOL::border_t>* obstacles
Definition at line 23 of file etol_psopt_example1.cpp.
Referenced by obsConstraint().
tracks
std::vector<std::pair<double, DMatrix> > tracks = {}
Definition at line 24 of file etol_psopt_example1.cpp.
Referenced by saaConstraint().