ETOL: C:/msys64/home/admin/ETOL/src/Examples/OMPL/etol_ompl_example1.cpp File Reference
etol_ompl_example1.cpp File Reference
Loads a ETOL Config XML file and uses GLPK to solve a ETOL.
#include <ETOL/eOMPL.hpp>
Functions
void dynConstraint (OMPL_DYN_ARGS)
ompl::base::OptimizationObjectivePtr optObjFunc (const ompl::base::SpaceInformationPtr &si)
int main (int argc, char **argv)
Detailed Description
Loads a ETOL Config XML file and uses GLPK to solve a ETOL.
Copyright
2020 Thanakorn Khamvilai
Author
Thanakorn Khamvilai thana.nosp@m.korn.nosp@m.khamv.nosp@m.ilai.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Date
6 May 2020
Version
1.0.0
DESCRIPTION
Solves the following optimization problem minimize path length subject to x_dot = u_0, y_dot = u_1, (x_k, y_k) Static Obstacle (x_k, y_k) Moving Obstacle
Definition in file etol_ompl_example1.cpp.
Function Documentation
dynConstraint()
void dynConstraint (OMPL_DYN_ARGS)
Definition at line 59 of file etol_ompl_example1.cpp.
{
     const double *u = control->
             as<ompl::control::RealVectorControlSpace::ControlType>()->values;
     // Zero out xdot
     xdot.resize(x.size(), 0);
     // single integrator dynamics
     xdot[0] = u[0];
     xdot[1] = u[1];
 }
Referenced by main().
optObjFunc()
ompl::base::OptimizationObjectivePtr optObjFunc (const ompl::base::SpaceInformationPtr & si)
Definition at line 71 of file etol_ompl_example1.cpp.
{
     return ompl::base::OptimizationObjectivePtr(
             new ompl::base::PathLengthOptimizationObjective(si));
 }
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 25 of file etol_ompl_example1.cpp.
{
     std::cout << "OMPL" << std::endl;
     ETOL::TrajectoryOptimizer* t;
     ETOL::eOMPL tg = ETOL::eOMPL();
     t = &tg;
     t->loadConfigs(argv[1]);
     // t->printConfigs();
     // see a list of planners here: https://ompl.kavrakilab.org/planners.html
     tg.setPlanner("SST");  // sparse stable RRT
     tg.setGradient(&dynConstraint);
     tg.pdef_->setOptimizationObjective(optObjFunc(tg.si_));
     // Setup
     t->setup();
     // Solve
     t->solve();
     // Result
     std::cout << "\n!!!!!!!!!!!!!!!!!Results!!!!!!!!!!!!!!!!!" << std::endl;
     std::cout << "Minimization Score:\t" << t->getScore() << std::endl;
     std::cout << "Plotting..." << std::endl;
     ETOL::TrajectoryOptimizer::plotXY_wExclZones(t->getXtraj(),
             t->getObstacles());
     // Release resources e.g. memory
     t->close();
     return 0;
 }
References ETOL::TrajectoryOptimizer::close(), dynConstraint(), ETOL::TrajectoryOptimizer::getObstacles(), ETOL::TrajectoryOptimizer::getScore(), ETOL::TrajectoryOptimizer::getXtraj(), ETOL::TrajectoryOptimizer::loadConfigs(), optObjFunc(), ETOL::eOMPL::pdef_, ETOL::TrajectoryOptimizer::plotXY_wExclZones(), ETOL::eOMPL::setGradient(), ETOL::eOMPL::setPlanner(), ETOL::TrajectoryOptimizer::setup(), ETOL::eOMPL::si_, and ETOL::TrajectoryOptimizer::solve().